### ISSUE TITLE
Buy and Sell functions dont work

### ISSUE THREAD

**Issue by wild99** [jaggedsoft/php-binance-api#10]
Hi!

When i try to buy or sell some ticker i've get an error:
Array
(
    [code] => -1101
    [msg] => Too many parameters; expected '6' and received '7'.
)

**Comment by wild99** [comment]
$orderbuy=$binance->marketBuy($ticker,$quantity);

**Comment by jaggedsoft** [comment]
Thank you for the report! This is fixed (I think) in the latest release. Please keep me updated
