### ISSUE TITLE
Allowed memory

### ISSUE THREAD

**Issue by wybitnygracz** [jaggedsoft/php-binance-api#100]
everytime, after 2 hours i get error: 

PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 77824 bytes) in .../jaggedsoft/vendor/ratchet/rfc6455/src/Messaging/Message.php on line 107

PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 86016 bytes) in .../jaggedsoft/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php on line 205

**Comment by jaggedsoft** [comment]
Thanks for the report!
Will look in to this
in the mean time I suppose you could try running with `memory_limit(0)`

**Comment by dmzoneill** [comment]
Hey, could you provide your php version?

If you stick http://php.net/manual/en/function.memory-get-usage.php

In your call back function, does the memory increase for each callback?  We may need to submit a bug to ratchet. 🤔
