### ISSUE TITLE
Fatal error: Default value for parameters with a class type hint can only be NULL

### ISSUE THREAD

**Issue by michielkoers** [jaggedsoft/php-binance-api#101]
Hello,
I've been using this api wrapper for quite some time now, and it worked great. I've updated to the latest version using composer and now I get the following error:

_Fatal error: Default value for parameters with a class type hint can only be NULL in /Applications/MAMP/htdocs/dagobot/vendor/jaggedsoft/php-binance-api/php-binance-api.php on line 60_

Just to make sure I created a really simple script that just pulls in some data using `$ticker = $api->prices();` but I still get the error.

Could you maybe try and fix this?
Thanks a lot in advance!
Michiel

**Comment by dmzoneill** [comment]
can you post the code you are using please? thanks
```
<?php
// code
```

**Comment by jaggedsoft** [comment]
This same thing happened to me when we switched the requirements to PHP 7
I'd recommend upgrading. The improvements dmzoneill has been making are worth it

Otherwise your only option is rolling back to version `v0.1.8`

**Comment by dmzoneill** [comment]
im looking into it

**Comment by dmzoneill** [comment]
unfortunately i just spent a chunk of time tryng to fix it for php 5.6 :(

can only type hint abstract types in php , php hinting of primitives, int, flotat, bool ,, and string (char*) was added in 7

**Comment by jaggedsoft** [comment]
it's ok as long as we update the requirement in composer.json, the upgrade process to php 7 is very simple now. Painless. And php 7 is much faster

**Comment by michielkoers** [comment]
Thanks for the comments and the work you've put in! I'm away for the weekend, but I assume the problem will be fixed after updating PHP. Shouldn't be a problem but I have to check with my webhost. I will try it when I get back. Thanks again!

**Comment by jaggedsoft** [comment]
<3 Glad to hear it, thanks for the kind words! @dmzoneill has been doing great work 🥇 🏆
