### ISSUE TITLE
Zero price in the response of a Sell order but also in the response of the order info call 

### ISSUE THREAD

**Issue by vreesie18** [jaggedsoft/php-binance-api#102]
When a issue a sell order (->marketSell) I get a response array back but the price contains 0.00 ([price] => 0.00000000). Is this a bug on the side of binance or in this library ???
When I accordingly issue an order info request (->orderStatus) I get a response but again then price contains 0.00. ([price] => 0.00000000)

In the  binance website I can see the real price as part of the order.

What might be wrong?

**Comment by vreesie18** [comment]
I understand that there is not one price when the order is fragmented executed but at least there should be a way to get the details on de second level of execution.

**Comment by vreesie18** [comment]
I managed to do it with the trading history call. It has all the details I need. Thank you for let me talk to you!!!

**Comment by jaggedsoft** [comment]
Best way to handle this is with `newOrderRespType`

You can set 'newOrderRespType' to "FULL" when placing market orders
I will add some examples. It returns a response of "fills" indicating the price you paid
![36094574-acb15ae6-0fa3-11e8-9209-e6f528e09e84](https://user-images.githubusercontent.com/4283360/38383467-6fc28686-38c1-11e8-9410-e59983c87723.png)

**Comment by vreesie18** [comment]
Numer=0.91441316
Type=string
signedRequest error: {"code":-1013,"msg":"Filter failure: LOT_SIZE"} Array ( [code] => -1013 [msg] => Filter failure: LOT_SIZE )

**Comment by vreesie18** [comment]
Very strange, I sliced off one decimal at the time and with number 0.91441 (5 dec) it worked. Very strange with having a standard of 8 decimals for quantities of coins. Any clue ?! I need to sell all my coins with one sell statement.

**Comment by jaggedsoft** [comment]
Yeah LOT_SIZE error is when you are not buying/selling enough
The way binance handles this is silly and I intend to make it easier in the future

You can call `exchangeInfo` function to see the minimums needed for every symbol
![example](https://image.ibb.co/bz5KAG/notationals.png)

I will add support  for `newOrderRespType` and update you
