### ISSUE TITLE
key+password file outside of www: www-data and multi user

### ISSUE THREAD

**Issue by vreesie18** [jaggedsoft/php-binance-api#103]
2 Questions regarding key + password file outside of www:
1) what is the home folder voor de linux www-data user running Apache ? To this home folder is referred in the php-binance-api to obtain the key + password
2) What is the solution for multiple binance accounts regarding this subject ?

**Comment by vreesie18** [comment]
@jaggedsoft: so this is gonna be a feature request :-)

**Comment by dmzoneill** [comment]
Patch: 
[code](https://github.com/jaggedsoft/php-binance-api/commit/c750049f2b12a319264a45f3b5de588ddf0eb27)

Documentation: 
[doc 1](https://github.com/jaggedsoft/php-binance-api/wiki/1.-Getting-Started)
[doc 2](https://github.com/jaggedsoft/php-binance-api/wiki/5.-$HOME-Config-(API---Proxy))

Close this per your discretion
@jaggedsoft @vreesie18

**Comment by jaggedsoft** [comment]
I love these improvements! Thanks!!
