### ISSUE TITLE
Code consistency

### ISSUE THREAD

**Issue by dmzoneill** [jaggedsoft/php-binance-api#107]
enable jackson linter for php and set coding style to verify

set travis job to fail on coding standard failure.

![image](https://user-images.githubusercontent.com/15192260/38570805-9c2a7fe8-3ce6-11e8-97b1-3dcb41a1e86b.png)

**Comment by jaggedsoft** [comment]
Need anything from me?
You keep blowing me away with your work. Good stuff!

**Comment by dmzoneill** [comment]
all good man

enjoy

**Comment by dmzoneill** [comment]
@jaggedsoft 

Please note the build conditions in travis.

```
  - php fmt.phar -v --psr2 --indent_with_space=4 -o=php-binance-api.php.fmt php-binance-api.php
  - diff php-binance-api.php.fmt php-binance-api.php
```

since you said you are using this, 
i installed the plugin "phpfmt" in vscode and used the same default settings as in that plugin.
https://github.com/kokororin/vscode-phpfmt

format document in vscode (right lick -> format document / CTRL + SHIFT + I)

Please close the ticket per your convenience.
