### ISSUE TITLE
constcurt

### ISSUE THREAD

**Issue by baranovskiy** [jaggedsoft/php-binance-api#109]
*/
   public function __construct() {
      $param = func_get_args();
      switch( func_num_args() ) {
         case 0:
            $this->__construct0();
         break;
         case 1:
            $this->__construct1( $param[ 0 ] );
         break;
         case 2:
            $this->__construct2( $param[ 0 ], $param[ 1 ] );
         break;
         **case 3:
            $this->__construct2( $param[ 0 ], $param[ 1 ], $param[ 2 ] );
         break;
         case 4:
            $this->__construct2( $param[ 0 ], $param[ 1 ], $param[ 2 ], $param[ 3 ] );
         break;**
      }
   }

construct3/4 will be never used ?

**Comment by dmzoneill** [comment]
Thanks.. need a unit test and code coverage for these constructors
