### ISSUE TITLE
Websocket trades() multi symbol

### ISSUE THREAD

**Issue by oscarmlage** [jaggedsoft/php-binance-api#11]
As I've seen in the code, the trades() method allows multiple symbols:

	// Trades WebSocket Endpoint
	public function trades($symbols, $callback) {
		foreach ( $symbols as $symbol ) {
                ...

But in the end it seems to be connected only to the stream of first symbol passed in the array and I'm not able to retrieve information about the other ones. My call:

`$api->trades(['TRXETH', 'ADAETH'], function($api, $symbol, $trades) {...`

What am I doing wrong?

**Comment by jaggedsoft** [comment]
Thank you for the report. I'm looking in to this. Will get back to you!

**Comment by jaggedsoft** [comment]
Hmm. I am having the same exact problem. I suspect this is an issue with my dependency RatchetPHP
It also happens when you do this:
```php
$api->trades(["BTCUSDT"], function($api, $symbol, $trades) {
    echo "{$symbol} trades update".PHP_EOL;
    print_r($trades);
});
$api->trades(["BNBBTC"], function($api, $symbol, $trades) {
    echo "{$symbol} trades update".PHP_EOL;
    print_r($trades);
});
```

**Comment by jaggedsoft** [comment]
Resolved in commit # https://github.com/jaggedsoft/php-binance-api/commit/b43ec761a070ebe2542071f7d6ecd2545b467f8b
You can update with `composer update` from inside the project directory

**Comment by oscarmlage** [comment]
Thank you so much. I'll try it later today :-)

**Comment by oscarmlage** [comment]
It works like a charm!! Thank you so much @jaggedsoft, it's awesome!!
