### ISSUE TITLE
Can we have option to disable ssl?

### ISSUE THREAD

**Issue by andrewpros** [jaggedsoft/php-binance-api#110]
The title says it all, i'm testing on localhost but there is that annoying curl ssl cert error and after every update i need to manually add this again in httpRequest method

#ssl hackfix
curl_setopt( $ch, CURLOPT_SSL_VERIFYPEER, false );

**Comment by dmzoneill** [comment]
```
dave@dave-laptop:~/Desktop/crypto/php-binance-api$ cat /home/dave/.config/jaggedsoft/php-binance-api-1.json
{
    "// no money in this account": "dream on",
    "api-key": "z5RQZ9n8JcS3HLDQmPpfLQIGGQN6TTs5pCP5CTnn4nYk2ImFcew49v4ZrmP3MGl5",
    "api-secret": "ZqePF1DcLb6Oa0CfcLWH0Tva59y8qBBIqu789JEY27jq0RkOKXpNl9992By1PN9Z",
    "curlOpts": {
	    "CURLOPT_SSL_VERIFYPEER": 0,
	    "INVALID_CONSTANT_NAME": 42
    }
}
```

load via constructor, filename or paramters
```
new Binance( null,null, $options[ 'curlOpts' = [] ]);
// or
new Binance( "apth to file above" );
```

**Comment by dmzoneill** [comment]
@jaggedsoft 
@andrewpros

**Comment by andrewpros** [comment]
@dmzoneill 
Now that was fast, thx

**Comment by andrewpros** [comment]
@dmzoneill 
i was happy too quickly there is a typo making it impossible to use it

https://github.com/jaggedsoft/php-binance-api/commit/46d2642e18bb14f529aee561305f8be5878d5b13#diff-5dbeba22e806b45539eff4e47a00a391R132

https://github.com/jaggedsoft/php-binance-api/commit/46d2642e18bb14f529aee561305f8be5878d5b13#diff-5dbeba22e806b45539eff4e47a00a391R153

**Comment by dmzoneill** [comment]
fixed

**Comment by andrewpros** [comment]
Still needs fixing
there is another https://github.com/jaggedsoft/php-binance-api/blob/master/php-binance-api.php#L153
and useServerTime() must be always after assigning curlOpts

also construct3 doesn't have proxyConf var

**Comment by dmzoneill** [comment]
thanks for the feedback, this is resolved

the actual constructor calls ___constructX depending on number of parameters passed.
___construct4 if you pass 4 parameters, 
___construct3 if you pass 3 parameters

```
public function __construct() {
      $param = func_get_args();
      switch( func_num_args() ) {
         case 0:
            $this->__construct0();
         break;
         case 1:
            $this->__construct1( $param[ 0 ] );
         break;
         case 2:
            $this->__construct2( $param[ 0 ], $param[ 1 ] );
         break;
         case 3:
            $this->__construct3( $param[ 0 ], $param[ 1 ], $param[ 2 ] );
         break;
         case 4:
            $this->__construct4( $param[ 0 ], $param[ 1 ], $param[ 2 ], $param[ 3 ] );
         break;
      }
   }
```

__construct3
```
__construct4( string $api_key = null, string $api_secret = null, array $options = ["useServerTime"=>false], array $proxyConf = null ) 
```
___construct4
```
__construct4( string $api_key = null, string $api_secret = null, array $options = ["useServerTime"=>false] ) 
```

**Comment by andrewpros** [comment]
Well i know this, i know php, but i feel we are not on the same page here.

This is a bug and it was there from the start, multiple constructors was introduced just couple of days ago https://github.com/jaggedsoft/php-binance-api/commit/c750049f2b12a319264a45f3b5de588ddf0eb27d#diff-5dbeba22e806b45539eff4e47a00a391R122 and following commits changes/fixes , maybe no one noticed it yet, but there is no $proxyConf parameter in construct3 function, so it will throw Undefined variable.
We can just use construct4 with null proxy parameter, but then, why we even have construct3?

But this is a non issue really, as it works with 4th parameter, we don't really need costruct4, 3 can have the same parameters with def null proxy.

The most important bug now is still wrong function order, UseServerTime() function MUST BE called always after assigning curlOpts https://github.com/jaggedsoft/php-binance-api/blob/master/php-binance-api.php#L129

in every constructor it is used, as it makes a binance api call to get time, so curlOpts must be already assigned to prevent for example ssl cert error by adding CURLOPT_SSL_VERIFYPEER =>false

Hope i explained it clearly now.

**Comment by jaggedsoft** [comment]
Thank you for your report
useServerTime can also be used outside of the constructor, which will probably solve your problem in this case:

```php
require 'vendor/autoload.php';
$api = new Binance\API("<api key>", "<secret>", $options[ 'curlOpts' = [] ]);
$api->useServerTime();
```

**Comment by andrewpros** [comment]
still, should be also fixed in all constructors as it is a bug

**Comment by jaggedsoft** [comment]
construct3 doesn't have these lines but everything else should be ok:
```php
      $this->setupApiConfigFromFile();
      $this->setupProxyConfigFromFile();
      $this->setupCurlOptsFromFile();
```

**Comment by jaggedsoft** [comment]
His fixes are available in `v0.2.6`

**Comment by dmzoneill** [comment]
Hi @andrewpros 

would greatly appreciate a pull requests!  seems like you are on the ball.

I've been getting the units test and coverage in place for node-binance-api.  Once i have it up for a fair standard, i plan to come back here to complete the remaining coverage tests and checks for PHP.

If you could help, that would be aweomse!

Thanks again dude @andrewpros

**Comment by andrewpros** [comment]
@jaggedsoft @dmzoneill 

Wow, just wow, so you will insist on not fixing a know bug... This is beyond my understanding, if there is a function that can be called but i doesn't work as expected even if someone provide valid parameters then it is a bug and it cant stay like that.

The function order is still not fixed, the expected result is to work with any valid parameters, also we don't need construct3 at all, i didn't bother with a PR as i assumed it is a simple fix, i assumed it will be fixed in no time.

In fact everything should be set always before making the first and any binance api call, as that setup may have impact on any call just like with those ssl cert errors, so useServerTime should be called always last.

So so you don't say i did nothing here it is, my pr

https://github.com/jaggedsoft/php-binance-api/pull/111

**Comment by dmzoneill** [comment]
Thanks for the feedback again man.  
As i said, i plan to finish out the remaining unit tests and coverage tests very soon.
Rest assured your concerns will be actioned! Enjoy

**Comment by andrewpros** [comment]
Well ok then, thx.
