### ISSUE TITLE
problem with ssl in wamp environment

### ISSUE THREAD

**Issue by abc36222** [jaggedsoft/php-binance-api#113]
I work with wamp the latest version PHP 7 included.
I used miniticker and had no problem, but when I siwtched to candlesticks it says:

Curl error: SSL certificate problem: unable to get local issuer certificate 

your help would be appreciated

**Comment by dmzoneill** [comment]
Hey 

this most likely some issue on your xammp install..

https://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate

Number of post online complaining out it.

Our travis test runs the test just fine.
You can pass options into curl 

https://github.com/jaggedsoft/php-binance-api/wiki/5.-$HOME-Config-(API---Proxy)

Try disabling the ssl verification temporarily, work the problem from there. Once you identify the issue

**Comment by abc36222** [comment]
Actually I tried the instruction on stackoverflow thread before and the problem still is there. I try pass the options

**Comment by abc36222** [comment]
the funny thing is I get the data when I use miniticker. that's weird. isn't it.

**Comment by abc36222** [comment]
thanks a lot. I'm waiting for your solution ...

**Comment by dmzoneill** [comment]
there you go

https://github.com/jaggedsoft/php-binance-api/commit/eb4841bf4c1a885d3565f76c5df2b292bfab153f

Please close the ticket if this is satisfactory

**Comment by abc36222** [comment]
thanks buddy. the previous error is gone, but there is another error, when I run candles.php which say:
Curl error: SSL certificate problem: self signed certificate in certificate chain 

and by running web_socket_kline.php I get this message:
kline(BTCUSDT,5m)) Could not connect: Unable to complete SSL/TLS handshake: stream_socket_enable_crypto(): this stream does not support SSL/crypto

I'm working on it to find out where is the problem. would be appreciated if you could also help on this one too. Thanks in advance

**Comment by dmzoneill** [comment]
Sounds like there is a problem with the certificate bundle being used by your curl installation...

 i dont use windows so i dont see these sort of problems with third party packaging of AMP....

Did you try updating the certificate bundle provided with that wamp installation.

Note if you are using self signed certs updating. The bundle will most likely wipe our your self signed certs.

https://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate

**Comment by abc36222** [comment]
ok. At last I got the websocket kline working. thanks. I guess the problem of the second error message was my wamp settings. 
just one more questions. I have some variables in output. of course some of the are obvious but I don't know about the others. I placed question mark on those I don't know what are they. (sorry for such a simple question) 

  public 't' => int 1523885700000  ->?
  public 'T' => int 1523885999999 ->?
  public 's' => string 'BTCUSDT' (length=7) 
  public 'i' => string '5m' (length=2) is Interval
  public 'f' => int 35919394 -> ?
  public 'L' => int 35920784 -> ?
  public 'o' => string '7920.00000000' (length=13) Candle Open
  public 'c' => string '7945.03000000' (length=13) Candle Close
  public 'h' => string '7949.00000000' (length=13) Candle High
  public 'l' => string '7908.60000000' (length=13) Candle Low
  public 'v' => string '214.44717400' (length=12) ->?
  public 'n' => int 1391 -> ?
  public 'x' => boolean false -> ?
  public 'q' => string '1699732.89070656' (length=16) -> ?
  public 'V' => string '118.68597700' (length=12) ->?
  public 'Q' => string '940886.87377972' (length=15) -> ?
  public 'B' => string '0' (length=1) ->?

**Comment by dmzoneill** [comment]
glad you got sorted man,

Binancedocuments these variables over on there documentation

you can find it here:  
https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md

**Comment by abc36222** [comment]
thank you for your time ...
