### ISSUE TITLE
 parameters for querying the Withdraw History

### ISSUE THREAD

**Issue by dormadekhin-denis** [jaggedsoft/php-binance-api#114]
In the description of the official documentation, I found that for the method of obtaining the history of withdrawals it is possible to indicate not only a coin but also other parameters. Is it possible to add these parameters to the withdrawHistory method?
link the official documentation: https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#withdraw-history-user_data

**Comment by jaggedsoft** [comment]
Absolutely, thank you for the suggestion. These parameters were added after we made our initial implementation

**Comment by dormadekhin-denis** [comment]
Thanks for the quick reply! I will wait for updates))

**Comment by jaggedsoft** [comment]
Added in https://github.com/jaggedsoft/php-binance-api/commit/44d8026cd9dfd1cf2b1a9d6dba8fdbeeea71d7e6
Available in `v0.2.8`
