### ISSUE TITLE
referral program

### ISSUE THREAD

**Issue by dormadekhin** [jaggedsoft/php-binance-api#115]
Hello!
Is there a way to get information on profit for the referral program?

**Comment by dormadekhin-denis** [comment]
I'm interested in the possibility of obtaining this information on the API, as far as I understand it is not currently implemented?

**Comment by dormadekhin-denis** [comment]
The fact is that because of the lack of information on referral accruals, I have negative information on the balance of some coins, after the calculation of all transactions on the account
