### ISSUE TITLE
Detecting Volume Changes - Realiable way

### ISSUE THREAD

**Issue by darito21** [jaggedsoft/php-binance-api#116]
Hi
I have a question about detecting volume changes in sales or buys. As you can see on the image, every minute Binance informs the volume for a given coin, in Red if sales were more than buys or in Green if buys were more than sales.
![captura](https://user-images.githubusercontent.com/26126371/39063615-0c64a244-44a2-11e8-806f-5f23cb78631a.JPG)

Is there any reliable way to get that info? 
Im using candlestick and prevday functions but none of them help me (or Im doing something wrong)

Candlestick returns volume and prices for a given period, let say 1m, but it always is positive. There is no way to detect if this minute was red or green other than the price and its variation.
Prevday also returns volume for the last 24hours, but this is no reliable because when a new minute is added, the first one (24h+1m) is deleted from the count, so the variation is useless to detect variations.

Im using your code in my trading bot, it works as expected, but I want to limit my bot to place an order in a pump and I believe the volume fact is more reliable than price chances.

Any idea? Any hidden function Im not seeing?
Thank you

**Comment by jaggedsoft** [comment]
Hi there
this will show you an example on how to get buying demand (how much volume was buy volume)

```php
$api->kline(["BTCUSDT", "EOSBTC"], "5m", function($api, $symbol, $chart) {
  //echo "{$symbol} ({$interval}) candlestick update\n";
	$interval = $chart->i;
	$tick = $chart->t;
	$open = $chart->o;
	$high = $chart->h;
	$low = $chart->l;
	$close = $chart->c;
	$volume = $chart->q;
	$baseVolume = $chart->v; // base asset volume
	$trades = $chart->n; // number of trades
	$closed = $chart->x; // is this kline closed?
	$quoteVolume = $chart->q; // Quote asset volume
	$buyVolume = $chart->V; // Taker buy base asset volume
	$perc = round(percent($buyVolume, $baseVolume), 2);
	echo "{$symbol} price: {$close}\t volume: {$volume}\t demand: {$perc}%\n";
});

function percent($min,$max,$width=100) { // 50,100,100 = 50.  1,2,100 = 50.  1,2,10 = 5.
	return ($min*0.01)/($max*0.01)*intval($width);
}
```

> BTCUSDT price: $8509.95000000     volume: 605683.78885078         buying demand: 67.53%
> EOSBTC price: 0.00131860         volume: 60.50545311     buying demand: 45.95%

**Comment by darito21** [comment]
Thank you
Is there any way of doing this without websocks and only in rest api?

**Comment by jaggedsoft** [comment]
Yes you can get candlestick information like this:
```php
$ticks = $api->candlesticks("BTCUSDT", "1h");
$tick = array_pop($ticks); // Get last item from array
print_r($tick);
```
Response:
```
(
    [open] => 8505.04000000
    [high] => 8539.63000000
    [low] => 8505.00000000
    [close] => 8525.06000000
    [volume] => 6239114.57135650
    [openTime] => 1524250800000
    [closeTime] => 1524254399999
    [assetVolume] => 731.92109900
    [baseVolume] => 6239114.57135650
    [trades] => 6197
    [assetBuyVolume] => 423.17981100
    [takerBuyVolume] => 3607435.20619479
    [ignored] => 0
)
```

Final example:
```php
$ticks = $api->candlesticks("BTCUSDT", "1h");
$tick = array_pop($ticks); // Get last item from array
$perc = round(percent($tick['assetBuyVolume'], $tick['assetVolume']), 2);
echo "price: {$tick['close']} buying demand: {$perc}%\n";
```

> price: 8520.97000000 buying demand: 57.2%
