### ISSUE TITLE
Timestamp Conversion to regular time and date

### ISSUE THREAD

**Issue by abc36222** [jaggedsoft/php-binance-api#118]
Hi
I got a question, how can I convert the binance timestamp to regular time and date?
I don't know what are those numbers and what is the unit. I couldn't find any source which explains it.

your help would be appreciated

**Comment by dmzoneill** [comment]
http://php.net/manual/en/function.microtime.php
http://php.net/manual/en/function.time.php

**Comment by jaggedsoft** [comment]
@abc36222 The binance timestamp uses javascript format which includes microseconds
To convert it to the date friendly format that PHP prefers, just divide it by 1000:

$seconds = $timestamp / 1000

see https://github.com/jaggedsoft/php-binance-api/issues/9

**Comment by jaggedsoft** [comment]
Hi @kaduiceman as stated in the last message, binance timestamps use javascript time, which has milliseconds
![image](https://user-images.githubusercontent.com/4283360/46938032-5fac3700-d06b-11e8-88b3-7baa13820de1.png)

to convert these numbers into php time, just divide by 1000
`$seconds = $timestamp / 1000`
