### ISSUE TITLE
Recive last trade history

### ISSUE THREAD

**Issue by afsharsafavi** [jaggedsoft/php-binance-api#119]
Hello
I need to receive my last trade history.
I binance api wiki, if you remove fromId parameter from myTrades request, it will response most recent trade history.
But in your code, It's default value is 1 and when I run history function without third parameter, It show trade history from the begin.
If it possible, please add an option for receiving most recent history (I think by removing fromId parameter)

**Comment by jaggedsoft** [comment]
Available in v0.3.0 https://github.com/jaggedsoft/php-binance-api/commit/897c9bbc0a09b0da080fec141b61d464898cc293

**Comment by jaggedsoft** [comment]
Thank you for the report!
