### ISSUE TITLE
balances not returning

### ISSUE THREAD

**Issue by barisyesilcimen** [jaggedsoft/php-binance-api#12]
Hi,
balances not returning.  Notice: Undefined index: balances in C:\wamp\www\btc\php-binance-api.php on line 178

**Comment by ComeLC** [comment]
I think the problem is with the Binance platform, which is today saturated due to extreme activity.

**Comment by jaggedsoft** [comment]
Thank you for the report. I can verify that it is working for me right now. Perhaps this was a temporary outage
