### ISSUE TITLE
USDT to BCC problem

### ISSUE THREAD

**Issue by afsharsafavi** [jaggedsoft/php-binance-api#120]
Hello
I have problem when I want to purchase BCC from USDT with API
I used below code:
`$order1 = $api1 -> buy("BCCUSDT", 0.725754, 0, "MARKET");
`
But I received this error
`Array
(
    [code] => -1013
    [msg] => Filter failure: LOT_SIZE
)
`
I checked LOT size of BCC:
`[125] => Array
                (
                    [symbol] => BCCUSDT
                    [status] => TRADING
                    [baseAsset] => BCC
                    [baseAssetPrecision] => 8
                    [quoteAsset] => USDT
                    [quotePrecision] => 8
                    [orderTypes] => Array
                        (
                            [0] => LIMIT
                            [1] => LIMIT_MAKER
                            [2] => MARKET
                            [3] => STOP_LOSS_LIMIT
                            [4] => TAKE_PROFIT_LIMIT
                        )
                    [icebergAllowed] => 
                    [filters] => Array
                        (
                            [0] => Array
                                (
                                    [filterType] => PRICE_FILTER
                                    [minPrice] => 0.01000000
                                    [maxPrice] => 10000000.00000000
                                    [tickSize] => 0.01000000
                                )
                            [1] => Array
                                (
                                    [filterType] => LOT_SIZE
                                    [minQty] => 0.00001000
                                    [maxQty] => 10000000.00000000
                                    [stepSize] => 0.00001000
                                )
                            [2] => Array
                                (
                                    [filterType] => MIN_NOTIONAL
                                    [minNotional] => 10.00000000
                                )
                        )
                )`

**Comment by jaggedsoft** [comment]
Your problem here is `tickSize`

the tickSize for BCC is `0.01` meaning that you can only order multiples of .01 for some reason...

You would need to round your numbers like this for example: `number_format(0.012345,2,'.','');`

I am sorry there's not an easier way. The javascript version of my API has a roundStep() function which does this for you. We should add the same function to the PHP version

**Comment by afsharsafavi** [comment]
`tisksize` of BCCUSDT is same as BTCUSDT, But I don't have problem in BTC! 
Also numberformat is not suitable for some numbers for example if you want to buy all of your balance, and number is 0.725754 , `number_format(0.725754,2,'.','');` return 0.73 and you will get insufficient balance error. I think you should cut number not rounding them.

**Comment by jaggedsoft** [comment]
See if this works
```php
$order = marketBuy("BCCUSDT", 0.01, ["newOrderRespType"=>"FULL"]);
print_r($order);
```

**Comment by afsharsafavi** [comment]
I'm in USDT at this time (in loss) and I can't test it.
What does newOrderRespType=FULL do?

**Comment by jaggedsoft** [comment]
For market trades, returns the price you paid

**Comment by afsharsafavi** [comment]
I can't mean it.
Can you explain it by example, if it possible?
