### ISSUE TITLE
Implement roundstep()

### ISSUE THREAD

**Issue by dmzoneill** [jaggedsoft/php-binance-api#121]
**Title**
- enhancement: Enable roundstep behavior as seen in node-binance-api

**Short Description:**
- This is in relation to issue https://github.com/jaggedsoft/php-binance-api/issues/120

**Comment by jaggedsoft** [comment]
```php
    function roundStep($value, $stepSize = 0.1) {
        $precision = strlen(substr(strrchr(rtrim($value,'0'), '.'), 1));
        return round((($value / $stepSize) | 0) * $stepSize, $precision);
    }
```

**Comment by eppenga** [comment]
Mmmm....you sure? I rewrote since it gave me incorrect results, what do you think?

`/** Round value to the nearest stepSize **/
function roundStep($value, $stepSize = 0.1) {

  $precision = log10((1 / $stepSize));
  $value = round($value, $precision);
  
  return $value;
}
`
