### ISSUE TITLE
Orders should support the 'newOrderRespType' parameter

### ISSUE THREAD

**Issue by dmzoneill** [jaggedsoft/php-binance-api#122]
One suggestion I have, been too busy to implement this but it's a really simple change:
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade
Orders should support the 'newOrderRespType' parameter
This is especially useful for placing market orders

For the node js version I have a "flags" parameter to pass to the functions, such as marketBuy and marketSell. ["newOrderRespType"=>"FULL"]

![image](https://user-images.githubusercontent.com/15192260/39147371-5499f73a-4731-11e8-90b5-089340a83ddc.png)

​This allows you to get an array of "fills"
which tells you the price you paid for market orders​

**Comment by jaggedsoft** [comment]
I think this is already supported
$order = marketBuy('BNBBTC', 1, ["newOrderRespType"=>"FULL"]);

**Comment by jaggedsoft** [comment]
Looks like it
https://github.com/jaggedsoft/php-binance-api/blob/master/php-binance-api.php#L1043

**Comment by dmzoneill** [comment]
cool
