### ISSUE TITLE
Cannot connect on local machine

### ISSUE THREAD

**Issue by MrDevBC** [jaggedsoft/php-binance-api#125]
Getting signedRequest error: {"code":-1022,"msg":"Signature for this request is not valid."} balanceData error: Please make sure your system time is synchronized, or pass the useServerTime option.

I have try using the useServerTime too but no luck

**Platform:**
- windows
- XamPP

**php version:**
- 7.2.4

**code**
```
require 'vendor/autoload.php';
$api = new Binance\API( "xxxxx", "xxxxx" );
$api->useServerTime();

// Get latest price of a symbol
$ticker = $api->prices();
echo '<pre>';
print_r($ticker); // List prices of all symbols
echo '</pre>';
echo "Price of BNB: {$ticker['BNBBTC']} BTC.\n";

// Get all of your positions, including estimated BTC value  - This is where the api doesn't work..
$balances = $api->balances($ticker);
print_r($balances);
```

thank you

**Comment by jaggedsoft** [comment]
This was working before he upgraded past PHP 7. Not sure what would change other than switching to cURL

**Comment by dmzoneill** [comment]
https://travis-ci.org/jaggedsoft/php-binance-api
- 7.0
- 7.1
- 7.2
- nightly 

Most likely xamp. The ca bundle on the thing is out of date

https://gist.github.com/odan/07c110028111647ee9615ae85cb7e71d

**Comment by MrDevBC** [comment]
One of 3 things
    double check your api key 
    I have double check the api key and its working.

    double check xamp. The ca bundle on the thing is out of date
    - I have updated the ca bundle fix and still no go.

    clock is wildly off on your machine and useservertime is not doing the job
    - It's weird that the old version work fine.

- any other suggestion?

**Comment by dmzoneill** [comment]
yes,  half the time people report issues its related to composer

```
git clone https://github.com/jaggedsoft/php-binance-api.git
cd php-binance-api
php examples/get_prices.php 
```

**Comment by MrDevBC** [comment]
I ran composer and it installed:
C:\Downloads\binance>composer require jaggedsoft/php-binance-api
Using version ^0.3.0 for jaggedsoft/php-binance-api
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 13 installs, 0 updates, 0 removals
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing ratchet/rfc6455 (v0.2.3): Loading from cache
  - Installing evenement/evenement (v3.0.1): Loading from cache
  - Installing react/event-loop (v0.5.2): Loading from cache
  - Installing react/stream (v0.7.7): Loading from cache
  - Installing react/promise (v2.5.1): Loading from cache
  - Installing react/promise-timer (v1.3.0): Loading from cache
  - Installing react/cache (v0.4.2): Loading from cache
  - Installing react/dns (v0.4.13): Loading from cache
  - Installing react/socket (v0.8.11): Loading from cache
  - Installing ratchet/pawl (v0.3.1): Loading from cache
  - Installing jaggedsoft/php-binance-api (v0.3.0): Loading from cache
react/event-loop suggests installing ext-event (~1.0 for ExtEventLoop)
react/event-loop suggests installing ext-pcntl (For signal handling support when using the StreamSelectLoop)
ratchet/pawl suggests installing reactivex/rxphp (~2.0)
Writing lock file
Generating autoload files

**Comment by dmzoneill** [comment]
what happens when you use my suggested method?

**Comment by MrDevBC** [comment]
Updating dependencies (including require-dev)
Package operations: 45 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-mbstring (v1.7.0): Downloading (100%)
  - Installing symfony/console (v4.0.8): Downloading (100%)
  - Installing symfony/process (v4.0.8): Downloading (100%)
  - Installing gitonomy/gitlib (v1.0.4): Downloading (100%)
  - Installing codacy/coverage (dev-master 4988cd0): Cloning 4988cd098d from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing ratchet/rfc6455 (v0.2.3): Loading from cache
  - Installing evenement/evenement (v3.0.1): Loading from cache
  - Installing react/event-loop (v0.5.2): Loading from cache
  - Installing react/stream (v0.7.7): Loading from cache
  - Installing react/promise (v2.5.1): Loading from cache
  - Installing react/promise-timer (v1.3.0): Loading from cache
  - Installing react/cache (v0.4.2): Loading from cache
  - Installing react/dns (v0.4.13): Loading from cache
  - Installing react/socket (v0.8.11): Loading from cache
  - Installing ratchet/pawl (v0.3.1): Loading from cache
  - Installing sebastian/version (2.0.1): Downloading (100%)
  - Installing sebastian/resource-operations (1.0.0): Downloading (100%)
  - Installing sebastian/recursion-context (3.0.0): Downloading (100%)
  - Installing sebastian/object-reflector (1.1.1): Downloading (100%)
  - Installing sebastian/object-enumerator (3.0.3): Downloading (100%)
  - Installing sebastian/global-state (2.0.0): Downloading (100%)
  - Installing sebastian/exporter (3.1.0): Downloading (100%)
  - Installing sebastian/environment (3.1.0): Downloading (100%)
  - Installing sebastian/diff (2.0.1): Downloading (100%)
  - Installing sebastian/comparator (2.1.3): Downloading (100%)
  - Installing doctrine/instantiator (1.1.0): Downloading (100%)
  - Installing phpunit/php-text-template (1.2.1): Downloading (100%)
  - Installing phpunit/phpunit-mock-objects (5.0.6): Downloading (100%)
  - Installing phpunit/php-timer (1.0.9): Downloading (100%)
  - Installing phpunit/php-file-iterator (1.4.5): Downloading (100%)
  - Installing theseer/tokenizer (1.1.0): Downloading (100%)
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Downloading (100%)
  - Installing phpunit/php-token-stream (2.0.2): Downloading (100%)
  - Installing phpunit/php-code-coverage (5.3.2): Downloading (100%)
  - Installing webmozart/assert (1.3.0): Downloading (100%)
  - Installing phpdocumentor/reflection-common (1.0.1): Downloading (100%)
  - Installing phpdocumentor/type-resolver (0.4.0): Downloading (100%)
  - Installing phpdocumentor/reflection-docblock (4.3.0): Downloading (100%)
  - Installing phpspec/prophecy (1.7.6): Downloading (100%)
  - Installing phar-io/version (1.0.1): Downloading (100%)
  - Installing phar-io/manifest (1.0.1): Downloading (100%)
  - Installing myclabs/deep-copy (1.7.0): Downloading (100%)
  - Installing phpunit/phpunit (6.5.8): Downloading (100%)
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/lock ()
symfony/console suggests installing psr/log (For using the console logger)
gitonomy/gitlib suggests installing psr/log (Add some log)
react/event-loop suggests installing ext-event (~1.0 for ExtEventLoop)
react/event-loop suggests installing ext-pcntl (For signal handling support when using the StreamSelectLoop)
ratchet/pawl suggests installing reactivex/rxphp (~2.0)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit-mock-objects suggests installing ext-soap (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.5)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
Writing lock file
Generating optimized autoload files

**Comment by dmzoneill** [comment]
@jaggedsoft 
@MrDevBC 

These Xampps / Wamps have issues which is unfortunate, becuase so many of our users use windows and use these install methods.

I'll need to look into some type of travis build for windows.

However if you look below, on linux there is zero issues, even using hte composer method.
There is no problem with the code.

**Getting started**
```
dave@dave-pc:~/Desktop$ php composer-setup.php
All settings correct for using Composer
Downloading...

Composer (version 1.6.4) successfully installed to: /home/dave/Desktop/composer.phar
Use it: php composer.phar

dave@dave-pc:~/Desktop$ php -r "unlink('composer-setup.php');"
dave@dave-pc:~/Desktop$ chmod +x composer.phar 
dave@dave-pc:~/Desktop$ ./composer.phar require jaggedsoft/php-binance-api
Using version ^0.3.0 for jaggedsoft/php-binance-api
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 13 installs, 0 updates, 0 removals
  - Installing psr/http-message (1.0.1): Downloading (100%)         
  - Installing guzzlehttp/psr7 (1.4.2): Downloading (100%)         
  - Installing ratchet/rfc6455 (v0.2.3): Downloading (100%)         
  - Installing evenement/evenement (v3.0.1): Downloading (100%)         
  - Installing react/event-loop (v0.5.2): Downloading (100%)         
  - Installing react/stream (v0.7.7): Downloading (100%)         
  - Installing react/promise (v2.5.1): Downloading (100%)         
  - Installing react/promise-timer (v1.3.0): Downloading (100%)         
  - Installing react/cache (v0.4.2): Downloading (100%)         
  - Installing react/dns (v0.4.13): Downloading (100%)         
  - Installing react/socket (v0.8.11): Downloading (100%)         
  - Installing ratchet/pawl (v0.3.1): Downloading (100%)         
  - Installing jaggedsoft/php-binance-api (v0.3.0): Downloading (100%)         
react/event-loop suggests installing ext-event (~1.0 for ExtEventLoop)
ratchet/pawl suggests installing reactivex/rxphp (~2.0)
Writing lock file
Generating autoload files
dave@dave-pc:~/Desktop$ ls

```
**code**
```
dave@dave-pc:~/Desktop$ cat test.php 
<?php

require 'vendor/autoload.php';

$apikey = "z5RQZ9n8JcS3HLDQmPpfLQIGGQN6TTs5pCP5CTnn4nYk2ImFcew49v4ZrmP3MGl5";
$apisecret = "ZqePF1DcLb6Oa0CfcLWH0Tva59y8qBBIqu789JEY27jq0RkOKXpNl9992By1PN9Z";
$config_file = getenv("HOME") . "/.config/jaggedsoft/php-binance-api.json";
file_put_contents($config_file, "{ \"api-key\": \"" . $apikey . "\", \"api-secret\": \"" . $apisecret . "\" }");

$api = new Binance\API();
$ticker = $api->prices();
print_r($ticker); // List prices of all symbols
echo "Price of BNB: {$ticker['BNBBTC']} BTC.\n";

$balances = $api->balances($ticker);
print_r($balances);
```

**result**
```
dave@dave-pc:~/Desktop$ php test.php 
Array
(
    [ETHBTC] => 0.06791000
    [XEMBTC] => 0.00004023
..........
    [XEMETH] => 0.00059661
    [XEMBNB] => 0.02719000
)
Price of BNB: 0.00148310 BTC.
Array
(
    [BTC] => Array
        (
            [available] => 0.00000000
            [onOrder] => 0.00000000
            [btcValue] => 0
            [btcTotal] => 0
        )

.........................

    [STORM] => Array
        (
            [available] => 0.00000000
            [onOrder] => 0.00000000
            [btcValue] => 0
            [btcTotal] => 0
        )

)
```

**Comment by MrDevBC** [comment]
Array
(
    [ETHBTC] => 0.06809700
    [LTCBTC] => 0.01627700
    [BNBBTC] => 0.00148990
    [NEOBTC] => 0.00787700
    [QTUMETH] => 0.03065400
    [EOSETH] => 0.02219300
    [SNTETH] => 0.00021516
    [BNTETH] => 0.00678400
    [BCCBTC] => 0.14080600
    [GASBTC] => 0.00276500
    [BNBETH] => 0.02183200
    [BTCUSDT] => 8860.49000000
    [ETHUSDT] => 602.74000000
    [HSRBTC] => 0.00097500
    [OAXETH] => 0.00113450
    [DNTETH] => 0.00014635
    [MCOETH] => 0.01805000
    [ICNETH] => 0.00217510
    [MCOBTC] => 0.00122500
    [WTCBTC] => 0.00141000
    [WTCETH] => 0.02066000
    [LRCBTC] => 0.00007668
    [LRCETH] => 0.00112305
    [QTUMBTC] => 0.00208500
    [YOYOBTC] => 0.00001262
    [OMGBTC] => 0.00168600
    [OMGETH] => 0.02485900
    [ZRXBTC] => 0.00010511
    [ZRXETH] => 0.00154759
    [STRATBTC] => 0.00063070
    [STRATETH] => 0.00930200
    [SNGLSBTC] => 0.00000978
    [SNGLSETH] => 0.00014365
    [BQXBTC] => 0.00034107
    [BQXETH] => 0.00501070
    [KNCBTC] => 0.00020178
    [KNCETH] => 0.00295060
    [FUNBTC] => 0.00000466
    [FUNETH] => 0.00006850
    [SNMBTC] => 0.00002185
    [SNMETH] => 0.00032056
    [NEOETH] => 0.11569300
    [IOTABTC] => 0.00019690
    [IOTAETH] => 0.00290583
    [LINKBTC] => 0.00004903
    [LINKETH] => 0.00072361
    [XVGBTC] => 0.00000678
    [XVGETH] => 0.00009942
    [SALTBTC] => 0.00037990
    [SALTETH] => 0.00558300
    [MDABTC] => 0.00011816
    [MDAETH] => 0.00174070
    [MTLBTC] => 0.00048780
    [MTLETH] => 0.00718100
    [SUBBTC] => 0.00007170
    [SUBETH] => 0.00105500
    [EOSBTC] => 0.00150870
    [SNTBTC] => 0.00001460
    [ETCETH] => 0.03021100
    [ETCBTC] => 0.00205900
    [MTHBTC] => 0.00001226
    [MTHETH] => 0.00018002
    [ENGBTC] => 0.00024869
    [ENGETH] => 0.00365440
    [DNTBTC] => 0.00001000
    [ZECBTC] => 0.03028400
    [ZECETH] => 0.44600000
    [BNTBTC] => 0.00046338
    [ASTBTC] => 0.00005680
    [ASTETH] => 0.00083730
    [DASHBTC] => 0.05153300
    [DASHETH] => 0.75770000
    [OAXBTC] => 0.00007700
    [ICNBTC] => 0.00014741
    [BTGBTC] => 0.00764600
    [BTGETH] => 0.11200100
    [EVXBTC] => 0.00016394
    [EVXETH] => 0.00240340
    [REQBTC] => 0.00002480
    [REQETH] => 0.00036549
    [VIBBTC] => 0.00002042
    [VIBETH] => 0.00029810
    [HSRETH] => 0.01440300
    [TRXBTC] => 0.00000748
    [TRXETH] => 0.00011004
    [POWRBTC] => 0.00005616
    [POWRETH] => 0.00082565
    [ARKBTC] => 0.00034010
    [ARKETH] => 0.00502400
    [YOYOETH] => 0.00018508
    [XRPBTC] => 0.00008690
    [XRPETH] => 0.00127699
    [MODBTC] => 0.00027520
    [MODETH] => 0.00403400
    [ENJBTC] => 0.00001480
    [ENJETH] => 0.00021843
    [STORJBTC] => 0.00011051
    [STORJETH] => 0.00162730
    [BNBUSDT] => 13.21060000
    [VENBNB] => 0.27450000
    [YOYOBNB] => 0.00857000
    [POWRBNB] => 0.03780000
    [VENBTC] => 0.00040766
    [VENETH] => 0.00599741
    [KMDBTC] => 0.00039140
    [KMDETH] => 0.00574900
    [NULSBNB] => 0.20010000
    [RCNBTC] => 0.00001422
    [RCNETH] => 0.00020849
    [RCNBNB] => 0.00953000
    [NULSBTC] => 0.00029828
    [NULSETH] => 0.00439188
    [RDNBTC] => 0.00020948
    [RDNETH] => 0.00306930
    [RDNBNB] => 0.14062000
    [XMRBTC] => 0.02837100
    [XMRETH] => 0.41527000
    [DLTBNB] => 0.01919000
    [WTCBNB] => 0.95200000
    [DLTBTC] => 0.00002851
    [DLTETH] => 0.00042029
    [AMBBTC] => 0.00006202
    [AMBETH] => 0.00091421
    [AMBBNB] => 0.04235000
    [BCCETH] => 2.06517000
    [BCCUSDT] => 1245.55000000
    [BCCBNB] => 94.92000000
    [BATBTC] => 0.00004354
    [BATETH] => 0.00063765
    [BATBNB] => 0.02924000
    [BCPTBTC] => 0.00005899
    [BCPTETH] => 0.00086500
    [BCPTBNB] => 0.03975000
    [ARNBTC] => 0.00016505
    [ARNETH] => 0.00242803
    [GVTBTC] => 0.00221800
    [GVTETH] => 0.03249800
    [CDTBTC] => 0.00000617
    [CDTETH] => 0.00009094
    [GXSBTC] => 0.00036790
    [GXSETH] => 0.00542000
    [NEOUSDT] => 69.62900000
    [NEOBNB] => 5.29800000
    [POEBTC] => 0.00000563
    [POEETH] => 0.00008268
    [QSPBTC] => 0.00001926
    [QSPETH] => 0.00028149
    [QSPBNB] => 0.01300000
    [BTSBTC] => 0.00002819
    [BTSETH] => 0.00041288
    [BTSBNB] => 0.01893000
    [XZCBTC] => 0.00447500
    [XZCETH] => 0.06569000
    [XZCBNB] => 3.03700000
    [LSKBTC] => 0.00119860
    [LSKETH] => 0.01761100
    [LSKBNB] => 0.80410000
    [TNTBTC] => 0.00001180
    [TNTETH] => 0.00017308
    [FUELBTC] => 0.00000962
    [FUELETH] => 0.00014134
    [MANABTC] => 0.00001396
    [MANAETH] => 0.00020534
    [BCDBTC] => 0.00318300
    [BCDETH] => 0.04669000
    [DGDBTC] => 0.02886900
    [DGDETH] => 0.42314000
    [IOTABNB] => 0.13233000
    [ADXBTC] => 0.00010198
    [ADXETH] => 0.00149560
    [ADXBNB] => 0.06876000
    [ADABTC] => 0.00002969
    [ADAETH] => 0.00043516
    [PPTBTC] => 0.00238790
    [PPTETH] => 0.03528300
    [CMTBTC] => 0.00001614
    [CMTETH] => 0.00023715
    [CMTBNB] => 0.01085000
    [XLMBTC] => 0.00003690
    [XLMETH] => 0.00054201
    [XLMBNB] => 0.02480000
    [CNDBTC] => 0.00001017
    [CNDETH] => 0.00014951
    [CNDBNB] => 0.00686000
    [LENDBTC] => 0.00000784
    [LENDETH] => 0.00011570
    [WABIBTC] => 0.00012948
    [WABIETH] => 0.00190000
    [WABIBNB] => 0.08690000
    [LTCETH] => 0.23885000
    [LTCUSDT] => 143.29000000
    [LTCBNB] => 10.88000000
    [TNBBTC] => 0.00000519
    [TNBETH] => 0.00007643
    [WAVESBTC] => 0.00057230
    [WAVESETH] => 0.00838400
    [WAVESBNB] => 0.38590000
    [GTOBTC] => 0.00003429
    [GTOETH] => 0.00050190
    [GTOBNB] => 0.02300000
    [ICXBTC] => 0.00040260
    [ICXETH] => 0.00592600
    [ICXBNB] => 0.27000000
    [OSTBTC] => 0.00002479
    [OSTETH] => 0.00036356
    [OSTBNB] => 0.01665000
    [ELFBTC] => 0.00011393
    [ELFETH] => 0.00167530
    [AIONBTC] => 0.00037550
    [AIONETH] => 0.00551600
    [AIONBNB] => 0.25314000
    [NEBLBTC] => 0.00128010
    [NEBLETH] => 0.01879700
    [NEBLBNB] => 0.86272000
    [BRDBTC] => 0.00007316
    [BRDETH] => 0.00107680
    [BRDBNB] => 0.04938000
    [MCOBNB] => 0.82954000
    [EDOBTC] => 0.00023120
    [EDOETH] => 0.00339200
    [WINGSBTC] => 0.00005972
    [WINGSETH] => 0.00087340
    [NAVBTC] => 0.00013560
    [NAVETH] => 0.00199100
    [NAVBNB] => 0.09135000
    [LUNBTC] => 0.00135850
    [LUNETH] => 0.01975900
    [TRIGBTC] => 0.00015610
    [TRIGETH] => 0.00230900
    [TRIGBNB] => 0.10486000
    [APPCBTC] => 0.00005684
    [APPCETH] => 0.00083590
    [APPCBNB] => 0.03858000
    [VIBEBTC] => 0.00002948
    [VIBEETH] => 0.00043490
    [RLCBTC] => 0.00014450
    [RLCETH] => 0.00215400
    [RLCBNB] => 0.09754000
    [INSBTC] => 0.00018830
    [INSETH] => 0.00276900
    [PIVXBTC] => 0.00055520
    [PIVXETH] => 0.00817100
    [PIVXBNB] => 0.37511000
    [IOSTBTC] => 0.00000490
    [IOSTETH] => 0.00007200
    [CHATBTC] => 0.00001326
    [CHATETH] => 0.00019521
    [STEEMBTC] => 0.00038170
    [STEEMETH] => 0.00560100
    [STEEMBNB] => 0.25604000
    [NANOBTC] => 0.00075930
    [NANOETH] => 0.01117200
    [NANOBNB] => 0.50990000
    [VIABTC] => 0.00024940
    [VIAETH] => 0.00369800
    [VIABNB] => 0.16790000
    [BLZBTC] => 0.00005347
    [BLZETH] => 0.00078462
    [BLZBNB] => 0.03583000
    [AEBTC] => 0.00024780
    [AEETH] => 0.00364200
    [AEBNB] => 0.16898000
    [RPXBTC] => 0.00001159
    [RPXETH] => 0.00017003
    [RPXBNB] => 0.00777000
    [NCASHBTC] => 0.00000435
    [NCASHETH] => 0.00006374
    [NCASHBNB] => 0.00292000
    [POABTC] => 0.00006002
    [POAETH] => 0.00088337
    [POABNB] => 0.04041000
    [ZILBTC] => 0.00000905
    [ZILETH] => 0.00013290
    [ZILBNB] => 0.00604000
    [ONTBTC] => 0.00051790
    [ONTETH] => 0.00762000
    [ONTBNB] => 0.34800000
    [STORMBTC] => 0.00000716
    [STORMETH] => 0.00010525
    [STORMBNB] => 0.00482000
    [QTUMBNB] => 1.39587000
    [QTUMUSDT] => 18.50900000
    [XEMBTC] => 0.00003991
    [XEMETH] => 0.00059002
    [XEMBNB] => 0.02716000
    [WANBTC] => 0.00077630
    [WANETH] => 0.01139900
    [WANBNB] => 0.52104000
    [WPRBTC] => 0.00001600
    [WPRETH] => 0.00023485
    [QLCBTC] => 0.00002110
    [QLCETH] => 0.00031147
    [SYSBTC] => 0.00005450
    [SYSETH] => 0.00079868
    [SYSBNB] => 0.03680000
    [QLCBNB] => 0.01416000
    [GRSBTC] => 0.00014153
    [GRSETH] => 0.00208805
    [ADAUSDT] => 0.26135000
    [ADABNB] => 0.01990000
    [CLOAKBTC] => 0.00137160
    [CLOAKETH] => 0.02023500
)

Price of BNB: 0.00148990 BTC.
balanceData error: Please make sure your system time is synchronized, or pass the useServerTime option.
balanceData error: Please make sure your system time is synchronized, or pass the useServerTime option.
143.29000000

**Comment by MrDevBC** [comment]
I have even try using Linux web hosting and still getting:
signedRequest error: {"code":-1022,"msg":"Signature for this request is not valid."} balanceData error: Please make sure your system time is synchronized, or pass the useServerTime option. 145.04000000

**Comment by dmzoneill** [comment]
this eror ris output when the array you pass into blances() is empty of null.

Check your array

```
        if (empty($array) || empty($array['balances'])) {
            // WPCS: XSS OK.
            echo "balanceData error: Please make sure your system time is synchronized, or pass the useServerTime option." . PHP_EOL;
            return [];
        }
```

**Comment by MrDevBC** [comment]
i'm using the following code:

// Get all of your positions, including estimated BTC value
$balances = $api->balances($ticker);
//print_r($balances);

$ticker = $api->prices();
$balances = $api->balances($ticker);
$BTCUSDT = $ticker['BTCUSDT'];
$ETHUSDT = $ticker['ETHUSDT'];
$LTCUSDT = $ticker['LTCUSDT'];

**Comment by dmzoneill** [comment]
Can you pull the lested version please?

added an additional check for your balance information

https://github.com/jaggedsoft/php-binance-api/commit/0be3376ba9a71f26fdcd39a74d405594811efa9a

```
git clone https://github.com/jaggedsoft/php-binance-api.git

```

**Comment by MrDevBC** [comment]
it's working now!!!... It was my api all this time -_-.. 

I'm so sorry guys.. 

Do you guys have api checking to make it correct?

I think it would be a good thing to have....

**Comment by dmzoneill** [comment]
https://travis-ci.org/jaggedsoft/php-binance-api

Yes travis automatically checks php v7.0 v7.1 v7.2 and php nightly.

See the link

@jaggedsoft

**Comment by jaggedsoft** [comment]
Thank you for your help @dmzoneill I really appreciate everything you are doing to help people and help this project. You are outstanding

@MrDevBC it was the api key? Maybe we can make the error message more friendly

I have installed this on windows with no problems, not using XAMPP though. Just php

**Comment by MrDevBC** [comment]
@jaggedsoft 
Yes it was the api keys. Maybe you can make a more friendly error message saying: 
Invalid API/Secret keys. Please check your keys and try again.
