### ISSUE TITLE
No response from buyTest/buy method

### ISSUE THREAD

**Issue by NikitaKurdin** [jaggedsoft/php-binance-api#128]
Hello.
I create a request to make test buy. If I have an error in request I receive an error from API like this: http://joxi.ru/MAjeOMYF4Wlxy2
But if I do it right I have no any response, just empty array http://joxi.ru/Vm63BbqCDGlvx2

What I do wrong?

**Comment by dmzoneill** [comment]
Response the the test is '{}' per the Binance documentation

https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#test-new-order-trade

**Comment by jaggedsoft** [comment]
Yeah, I know. Test orders should return _something_ right? This would sure eliminate a lot of confusion for people. However, this is how it's designed. Test orders are always blank responses.

**Comment by NikitaKurdin** [comment]
But problem in both methods. The same result in buy method (not in test).

**Comment by dmzoneill** [comment]
Hi please repost your issue, fill in the full details of the issue,  including.. platform, php version, your code and result.

Please use the format provided helps us answer you more effectively
