### ISSUE TITLE
syntax error, did I do something wrong?

### ISSUE THREAD

**Issue by duduzhu** [jaggedsoft/php-binance-api#13]
PHP Parse error:  syntax error, unexpected '[' in /home/ec2-user/php-binance-api/examples/binance-api-single.php on line 18

The code is as following.
```
        public function cancel($symbol, $orderid) {
                return $this->signedRequest("v3/order",["symbol"=>$symbol, "orderId"=>$orderid], "DELETE");

```

**Comment by jaggedsoft** [comment]
Thank you for the report
I am not seeing any syntax errors. Please make sure your project is up to date with `composer update` ran from the project directory.

**Comment by duduzhu** [comment]
I am running the single example, did not install from the composer. It is also supposed to work well, right?

**Comment by jaggedsoft** [comment]
Yes it should work, I can verify there are no syntax errors inside. Maybe this is a problem with your development environment
I recommend using a $5 VPS at DigitalOcean. Here is a coupon for $10 off: https://m.do.co/c/ea5bf7b795d6

**Comment by duduzhu** [comment]
I find the rootcause, it is because of the php version, which should be above 5.4. Other wise a initialization of array like `[]` does not work.
