### ISSUE TITLE
Keep-alive function for userDataStream not work after upgrade from apiRequest to httpRequesst

### ISSUE THREAD

**Issue by mrsantran** [jaggedsoft/php-binance-api#130]
Call Keep-alive evary 30 minutes, but listenKey not alive when upgrade from apiRequest to httpRequesst

![screen shot 2018-04-26 at 2 08 11 pm](https://user-images.githubusercontent.com/21286108/39290899-579b4c1e-495b-11e8-8ca2-302ee7f5af1a.png)

**Comment by jaggedsoft** [comment]
Thanks!

**Comment by jaggedsoft** [comment]
Needs to be a PUT request of USER_STREAM type (api key only, no timestamp)
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#keepalive-user-data-stream-user_stream

**Comment by jaggedsoft** [comment]
It looks like it is. So I believe this issue comes down to having more than one React websocket loop

**Comment by dmzoneill** [comment]
most likely resolved in https://github.com/jaggedsoft/php-binance-api/commit/13a57be1fdea749f24267de440345e27f060b87a
@jaggedsoft 
@mrsantran 

please repoen ticket if necessary

**Comment by AboliOneStar** [comment]
> Call Keep-alive evary 30 minutes, but listenKey not alive when upgrade from apiRequest to httpRequesst
> 
> ![screen shot 2018-04-26 at 2 08 11 pm](https://user-images.githubusercontent.com/21286108/39290899-579b4c1e-495b-11e8-8ca2-302ee7f5af1a.png)

Please write a tutorial how to use the keepAlive
