### ISSUE TITLE
Error with Web Socket

### ISSUE THREAD

**Issue by NikitaKurdin** [jaggedsoft/php-binance-api#133]
Hello. When i'm using method depthCache I receive an error:

> depthCache(BTCUSDT)) Could not connect: Unable to complete SSL/TLS handshake: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

PHP 5.6
Windows 7 x64

**Comment by dmzoneill** [comment]
Your bug says php 5.6, our latest version does not support php 5.6. The code does not run on anything less than php 7.

Please update to the current version and post a full bug report.

**Comment by NikitaKurdin** [comment]
Thx for answer. Problem is resolved.
