### ISSUE TITLE
require 'vendor/autoload.php'; - 500 Error

### ISSUE THREAD

**Issue by dankellys** [jaggedsoft/php-binance-api#134]
require 'vendor/autoload.php'; - 500 Error

**Short Description:**
- Unable to use Library as I get a 500 error.
  
**Platform:**
- linux

**php version:**
- 7.2

**Long descrption**
- I currently have shared hosting with SSH enabled and Composer installed already.  I have ran 

```
composer require jaggedsoft/php-binance-api
```
 and the library appears ot be installed in 'vendor/jaggedsoft/php-binance-api' on the root of my server.

-  My website is located in 'public_html/'

- Within public_html I have 1 file called 'binance_test.php'. The content of that file is below.  When i browse to www.MyURL.com/binance_test.php I get a 500 error.

**code**
```php
require 'vendor/autoload.php';
$api = new Binance\API( "MyKey", "MySecret" );

// Get latest price of a symbol
$ticker = $api->prices();
echo '<pre>';
print_r($ticker); // List prices of all symbols
echo '</pre>';
echo "Price of BNB: {$ticker['BNBBTC']} BTC.\n";

```
I have also tried the following, but get the same issue:
```php
require '../vendor/autoload.php';
```
**result**
```
HTTP ERROR 500
```

thank you

**Comment by dmzoneill** [comment]
Can you login to the server console and run
```
php binance_test.php
```

If you can't login to the server, you can try enable error reporting
```
<?php
ini_set ( 'error_reporting', true )
```

500 is most likely from your server and not the binance servers.

**Comment by dmzoneill** [comment]
Also the vendor directory needs to be in the same directory as your script.


I would highly recommend you use the configuration file as opposed to hard coding your key in a publicly accessible location

**Comment by dankellys** [comment]
Hi,

Running 
`php public_html/binance_test.php` 
works successully and I get the output I would expect from the browser.

So the vendor directory needs to be in the "public_html" directory.  Can I literally just copy/paste it into there, or do I need to get composer to install the library there?

**Comment by dankellys** [comment]
thanks for all your help, i really appeciate it.

phpconfig(); throws a 500 error too in the browser, however Cli outputs the following:

Configuration File (php.ini) Path: /opt/alt/php72/etc
Loaded Configuration File:         /opt/alt/php72/etc/php.ini
Scan for additional .ini files in: /opt/alt/php72/link/conf
Additional .ini files parsed:      /opt/alt/php72/link/conf/alt_php.ini

**Comment by dankellys** [comment]
phpinfo(); gives me an output.  Noticed it looks the same as what i see in cli:

Configuration File (php.ini) Path | /opt/alt/php72/etc
Loaded Configuration File | /opt/alt/php72/etc/php.ini
Scan this dir for additional .ini files | /opt/alt/php72/link/conf
Additional .ini files parsed | /opt/alt/php72/link/conf/alt_php.ini

**Comment by dmzoneill** [comment]
Enjoy.

Once again.. i will highly recommend you dont put your key inside the php script.. in cases it errors and spits it out on the screen
Or something...

Use a config file instead
https://github.com/jaggedsoft/php-binance-api/wiki/5.-Advanced-config-&-Proxy
