### ISSUE TITLE
Help: Websocket Connection Refused

### ISSUE THREAD

**Issue by jlfree** [jaggedsoft/php-binance-api#135]
I'm sorry if I'm missing something obvious, but every time I try to use a websocket method, I get a response "[METHOD]: Could not connect: Connection refused". Any idea what this could be?

Thanks in advance

**Comment by jaggedsoft** [comment]
Are you on WAMP? What system are you running this on?

**Comment by jlfree** [comment]
Apache on a Linux VPS

**Comment by jlfree** [comment]
Sorry, thought this was a quick fix like "uncomment line ##" or something. Template below:

Title: Websocket connection refusals

Short Description: Unable to open and maintain websocket connections through methods

Platform: linux

PHP version: 7.1.14

Calling web_socket_[example] from examples dir within php-binance-api dir results in an error failure to connect. The web_socket_dpeth gives an initial response before bugging out, others act like the miniticker and trades below:


XXXXXX@p3plvcpnl54019 [~/XXX/YYY/ZZZ/AAA/vendor/jaggedsoft/php-binance-api/examples]$ php web_socket_depth.php
BNBBTC depth cache update
asks:
0.00155600         38      0.05917468
0.00155590         14      0.02131583
0.00155560          2      0.00320454
0.00155520          5      0.00774490
0.00155480         10      0.01498827
0.00155470          1      0.00087063
0.00155440         63      0.09784948
0.00155400         59      0.09134412
0.00155380         43      0.06640941
0.00155370         12      0.01864440
0.00155360        574      0.89215480
bids:
0.00155130         53      0.08291699
0.00155120        152      0.23572035
0.00155080         24      0.03721920
0.00155070         52      0.08000061
0.00155060        198      0.30683273
0.00155050         69      0.10696900
0.00155040        286      0.44336789
0.00155020         19      0.02962432
0.00155010      1,588      2.46135729
0.00155000        316      0.48933500
0.00154990          1      0.00100744
ask: 0.00155360
bid: 0.00155130
depthCache(BNBBTC)) Could not connect: Connection refused
XXXX@p3plvcpnl54019 [~/XXX/YYY/ZZZ/AAA/vendor/jaggedsoft/php-binance-api/examples]$ php web_socket_trades.php
trades(BNBBTC) Could not connect: Connection refused
XXX@p3plvcpnl54019 [~/XXX/YYY/ZZZ/AAA/vendor/jaggedsoft/php-binance-api/examples]$ php web_socket_miniticker.php
miniticker: Could not connect: Connection refused

**Comment by dmzoneill** [comment]
okay, excellent man, thank you very much for this.
if you could be so kinda as to humour a small bit more

You are hitting this line:
https://github.com/jaggedsoft/php-binance-api/blob/12a62693e9fcb871ff04df81f3291dd7a257b7fe/php-binance-api.php#L2080

To understand remove my uncertainty as to the setup here..  
I'm going to assume to git clone as opposed to used composer to uninstall.
as such can you please follow these steps?

```php
cd ..
composer -vvv install
php examples/web_socket_miniticker.php
```

**Comment by dmzoneill** [comment]
once you confirm this 

```
nmap - p 9443 -Pn stream.binance.com
```

your output
```bash
dave@dave-laptop:~/Desktop/crypto/binancebot$ nmap - p 9443 -Pn stream.binance.com

Starting Nmap 7.40 ( https://nmap.org ) at 2018-05-02 04:54 IST
Failed to resolve "-".
Failed to resolve "p".
Strange read error from 0.0.36.227 (22 - 'Invalid argument')
Strange read error from 0.0.36.227 (22 - 'Invalid argument')
Strange read error from 0.0.36.227 (22 - 'Invalid argument')
Strange read error from 0.0.36.227 (22 - 'Invalid argument')
Strange read error from 0.0.36.227 (22 - 'Invalid argument')
Strange read error from 0.0.36.227 (22 - 'Invalid argument')
Strange read error from 0.0.36.227 (22 - 'Invalid argument')
Strange read error from 0.0.36.227 (22 - 'Invalid argument')
Strange read error from 0.0.36.227 (22 - 'Invalid argument')
Strange read error from 0.0.36.227 (22 - 'Invalid argument')
Strange read error from 0.0.36.227 (22 - 'Invalid argument')
Strange read error from 0.0.36.227 (22 - 'Invalid argument')

```

**Comment by jlfree** [comment]
Ran those commands and this is my output: 

XXX@p3plvcpnl54019 [~/CCC/DDD/EEE/FFF/vendor/jaggedsoft/php-binance-api] $ composer -vvv install
Reading ./composer.json
Loading config file /AAA/BBB/.composer/config.json
Loading config file /AAA/BBB/.composer/auth.json
Loading config file ./composer.json
Checked CA file /etc/pki/tls/certs/ca-bundle.crt: valid
Executing command (/AAA/BBB/CCC/DDD/EEE/FFF/vendor/jaggedsoft/php-binance-api): git branch --no-color --no-abbrev -v
Executing command (/AAA/BBB/CCC/DDD/EEE/FFF/vendor/jaggedsoft/php-binance-api): git describe --exact-match --tags
Failed to initialize global composer: Composer could not find the config file: /AAA/BBB/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /AAA/BBB/CCC/DDD/EEE/FFF/vendor/jaggedsoft/php-binance-api/vendor/composer/installed.json
Running 1.1.1 (2016-05-17 12:25:44) with PHP 7.1.14 on Linux / 2.6.32-896.16.1.lve1.4.51.el6.x86_64
Reading ./composer.lock
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Reading ./composer.lock
Resolving dependencies through SAT
Dependency resolution completed in 0.002 seconds
Analyzed 149 packages to resolve dependencies
Analyzed 397 rules to resolve dependencies
Nothing to install or update
Generating optimized autoload files

XXX@p3plvcpnl54019 [~/CCC/DDD/EEE/FFF/vendor/jaggedsoft/php-binance-api]$ php examples/web_socket_miniticker.php
miniticker: Could not connect: Connection refused

**Comment by dmzoneill** [comment]
once you confirm this, can you please run this command

```
nmap -p 9443 -Pn stream.binance.com
```

I need to see something like this
```bash
dave@dave-laptop:~/Desktop/crypto/binancebot$ nmap -p 9443 -Pn stream.binance.com

Starting Nmap 7.40 ( https://nmap.org ) at 2018-05-02 04:56 IST
Nmap scan report for stream.binance.com (54.65.194.89)
Host is up (0.26s latency).
Other addresses for stream.binance.com (not scanned): 54.65.136.43 54.64.211.159 54.64.5.205 54.65.187.206 54.250.240.115 54.65.80.217 54.65.214.112
rDNS record for 54.65.194.89: ec2-54-65-194-89.ap-northeast-1.compute.amazonaws.com
PORT     STATE SERVICE
9443/tcp open  tungsten-https

Nmap done: 1 IP address (1 host up) scanned in 0.42 seconds


```

**Comment by jlfree** [comment]
I don't have the nmap command available to me--is there an alternative I can use?

**Comment by dmzoneill** [comment]
Okay so you indicated you wer on a VPS.
on a debian debian based machine, ubuntu, mint, 

```
sudo apt-get install nmap
```

redhat based machine, fedora, centos
```
sudo dnf install nmap
sudo yum install nmap
```
curl might be enough
```
dave@dave-laptop:~/Desktop/crypto/binancebot$ curl -vvv https://stream.binance.com:9443
* Rebuilt URL to: https://stream.binance.com:9443/
*   Trying 54.92.50.113...
* TCP_NODELAY set
* Connected to stream.binance.com (54.92.50.113) port 9443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.binance.com
*  start date: May 24 00:00:00 2017 GMT
*  expire date: May 24 23:59:59 2018 GMT
*  subjectAltName: host "stream.binance.com" matched cert's "*.binance.com"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55ab9eb80ce0)
> GET / HTTP/1.1
> Host: stream.binance.com:9443
> User-Agent: curl/7.52.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 404 
< date: Wed, 02 May 2018 04:48:58 GMT
< content-type: text/html;charset=iso-8859-1
< content-length: 232
< cache-control: must-revalidate,no-cache,no-store
< 
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /. Reason:
<pre>    Not Found</pre></p>
</body>
</html>
* Curl_http_done: called premature == 0
* Connection #0 to host stream.binance.com left intact

```

**Comment by jlfree** [comment]
Having trouble with the nmap installation, but here is the CURL result:

AAA@p3plvcpnl54019 [/]$ curl -vvv https://stream.binance.com:9443
* About to connect() to stream.binance.com port 9443 (#0)
*   Trying 13.112.252.243... Connection refused
*   Trying 13.112.96.141... Connection refused
*   Trying 13.113.172.23... Connection refused
*   Trying 13.113.118.159... Connection refused
*   Trying 13.112.17.212... Connection refused
*   Trying 13.112.142.147... Connection refused
*   Trying 13.113.42.170... Connection refused
*   Trying 13.113.206.233... Connection refused
* couldn't connect to host
* Closing connection #0
curl: (7) couldn't connect to host
AAA@p3plvcpnl54019 [/]$

**Comment by jaggedsoft** [comment]
You can try setting up different name servers: https://1.1.1.1
This might work for you, it has worked for others

Otherwise you can use any number of VPS's that are $5/month or less, or run it on your own computer

Digitalocean, vultr, lunanode, all good choices

**Comment by jlfree** [comment]
Ok, sorry for the confusion and I sincerely appreciate both of your help. Pretty sure the issue didn’t originate with volume of calls from my end since I literally just set up this VPS. Am now reading Godaddy is known to do this kind of thing. Was leaning toward  AWS, but @Jon is there a reason you mentioned those 3 in particular?

**Comment by milyas2323** [comment]
Hi, i have some  issue in Trade Socket Call, give me this error "trades(BNBBTC) Could not connect: Connection refused" can you please help me?

**Comment by oveysrostami** [comment]
> can you please run this command
> 
> ```
> nmap -p 9443 -Pn stream.binance.com
> ```
> 
> I need to see something like this
> 
> ```shell
> dave@dave-laptop:~/Desktop/crypto/binancebot$ nmap -p 9443 -Pn stream.binance.com
> 
> Starting Nmap 7.40 ( https://nmap.org ) at 2018-05-02 04:56 IST
> Nmap scan report for stream.binance.com (54.65.194.89)
> Host is up (0.26s latency).
> Other addresses for stream.binance.com (not scanned): 54.65.136.43 54.64.211.159 54.64.5.205 54.65.187.206 54.250.240.115 54.65.80.217 54.65.214.112
> rDNS record for 54.65.194.89: ec2-54-65-194-89.ap-northeast-1.compute.amazonaws.com
> PORT     STATE SERVICE
> 9443/tcp open  tungsten-https
> 
> Nmap done: 1 IP address (1 host up) scanned in 0.42 seconds
> ```

Hi, I have same problem and run nmap and this is my result:
```
Starting Nmap 6.40 ( http://nmap.org ) at 2021-04-08 17:39 +0430
nmap: nsock_pool.c:227: nsp_delete: Assertion `nse->iod->events_pending >= 0' failed.
Aborted
```

what should I do ?!
