### ISSUE TITLE
Api keys not working

### ISSUE THREAD

**Issue by saadamin** [jaggedsoft/php-binance-api#137]
**Title**
- bug: api response nill
- feature: please add
- enhancement: add this to existing features

**Short Description:**
- Unable to get a result from api

I am sure my API keys are fine and balance is not empty .API's were working perfectly with old version of the php-binance-api with php5.5 , to use new version I have updated php 7.2.5 in my wamp version 2.5. Tried install by composer several times.

**Platform:**
- windows 10

**php version:**
- 7.2.5

**code**
```php
define('BINANCE_API','XXXXXXXX');
define('BINANCE_SECRET','XXXXXXXXX');
require 'vendor/autoload.php';
$api = new Binance\API(BINANCE_API,BINANCE_SECRET, ['useServerTime'=>true]);
$bookPrices = $api->bookPrices();
$ticker = $api->prices();
$balances = $api->balances($ticker);
```

**result**
```
Array ( ) Error: your balances were empty or unset balanceData error: Please make sure your system time is synchronized: call $api->useServerTime() before this function ERROR: Invalid request. Please double check your API keys and permissions.
```

$bookPrices and $ticker also returns empty array.

Getting same results in PHP Version 7.0.30

thank you

**Comment by dmzoneill** [comment]
Please see the update to the constructor.

```
    public function __construct()
    {
        $param = func_get_args();
        switch (func_num_args()) {
            case 0:
                $this->setupApiConfigFromFile();
                $this->setupProxyConfigFromFile();
                break;
            case 1:
                $this->setupApiConfigFromFile($param[0]);
                $this->setupProxyConfigFromFile($param[0]);
                $this->setupCurlOptsFromFile($param[0]);
                break;
            case 2:
                $this->api_key = $param[0];
                $this->api_secret = $param[1];
                break;
        }
    }
```
you should remove the 3rd paramter and use
```
$api->useServerTime();
```

**Comment by dmzoneill** [comment]
@jaggedsoft 

Would you like this? see switch 2,3,4

```
    public function __construct()
    {
        $param = func_get_args();
        switch (func_num_args()) {
            case 0:
                $this->setupApiConfigFromFile();
                $this->setupProxyConfigFromFile();
                break;
            case 1:
                $this->setupApiConfigFromFile($param[0]);
                $this->setupProxyConfigFromFile($param[0]);
                $this->setupCurlOptsFromFile($param[0]);
                break;
            case 2:
            case 3:
            case 4:
                $this->api_key = $param[0];
                $this->api_secret = $param[1];
                break;
        }
    }
```

**Comment by saadamin** [comment]
now my codes are
$api = new Binance\API(BINANCE_API,BINANCE_SECRET);    
$api->useServerTime();
$bookPrices = $api->bookPrices();
$ticker = $api->prices();
$balances = $api->balances($ticker);

Still same result.

**Comment by saadamin** [comment]
$bookPrices and $ticker also returns empty array

**Comment by dmzoneill** [comment]
Can you please delete your keys on the binance site and re-create them.

Ours builds for
- php 7.0.25
- https://travis-ci.org/jaggedsoft/php-binance-api/jobs/373879845
- php 7.1.11
- https://travis-ci.org/jaggedsoft/php-binance-api/jobs/373879846
- php 7.2.5
- https://travis-ci.org/jaggedsoft/php-binance-api/jobs/373879847
- php 7.3.0-dev
- https://travis-ci.org/jaggedsoft/php-binance-api/jobs/373879848

Don't concur with your report.

I ran this a moment ago on my local laptop
https://pastebin.com/gqiLRKWk

In the last week or so we've had to help with 2 issues related to incorrect keys and w've created a enhancement task
https://github.com/jaggedsoft/php-binance-api/issues/129

specifically for this scenario to help people

**Comment by saadamin** [comment]
I have checked a savarel time API keys , actually its defined few days ago in a constant so they are unchanged and I have tried also with new keys . same constants are working fine with other api https://github.com/baitercel/binance-api-php ,

**Comment by dmzoneill** [comment]
can you please try the following

```
git clone https://github.com/jaggedsoft/php-binance-api.git
cd php-binance-api
mkdir -vp ~/.config/jaggedsoft/

cat >  ~/.config/jaggedsoft/php-binance-api.json << EOF
{
    "api-key": "z5RQZ9n8JcS3HLDQmPpfLQIGGQN6TTs5pCP5CTnn4nYk2ImFcew49v4ZrmP3MGl5",
    "api-secret": "ZqePF1DcLb6Oa0CfcLWH0Tva59y8qBBIqu789JEY27jq0RkOKXpNl9992By1PN9Z"
}
EOF

php examples/balances.php
```

please use the keys above.

**Comment by saadamin** [comment]
same error http://bit.ly/2JLlP1r 

![image](https://user-images.githubusercontent.com/4682435/39535081-d83b524e-4e54-11e8-9d3f-959e9510e899.png)

**Comment by saadamin** [comment]
same error
![image](https://user-images.githubusercontent.com/4682435/39535553-00cc702a-4e56-11e8-9c4f-fee8f41c8158.png)

**Comment by saadamin** [comment]
![image](https://user-images.githubusercontent.com/4682435/39536594-ddf16242-4e58-11e8-9d85-98bda11f9bbf.png)
![image](https://user-images.githubusercontent.com/4682435/39536607-e95ed42a-4e58-11e8-88aa-e2a562f02a88.png)
![image](https://user-images.githubusercontent.com/4682435/39536635-fc9c30dc-4e58-11e8-819d-f2ff3b3ee352.png)

**Comment by jaggedsoft** [comment]
Yes the best solution is to use a json configuration
I have just updated the release if you want to try updating to the latest version

**Comment by dmzoneill** [comment]
you are one folder up.
```
cd examples 
php balances.php
```

**Comment by saadamin** [comment]
same , just cloned now

![image](https://user-images.githubusercontent.com/4682435/39537209-ab4c4940-4e5a-11e8-8a81-1be794b260f9.png)

**Comment by saadamin** [comment]
config.json generated succesfully.

![image](https://user-images.githubusercontent.com/4682435/39537477-851990d8-4e5b-11e8-9689-cbba66d58508.png)

**Comment by dmzoneill** [comment]
the path on your cygwin or whatever terminal you are using there is incorrect. 
the script cant find the config.  get the correct path and update the script.

**Comment by saadamin** [comment]
browser also showing same error , config.json generated successfully.

![image](https://user-images.githubusercontent.com/4682435/39537518-b24dddb6-4e5b-11e8-8402-e237ab4446ec.png)

**Comment by saadamin** [comment]
ok copied json.config in example folder 
![image](https://user-images.githubusercontent.com/4682435/39537582-dd51480e-4e5b-11e8-891a-865fea38f653.png)

and I am getting this

![image](https://user-images.githubusercontent.com/4682435/39537612-f2655b7c-4e5b-11e8-91e0-82975b5875e7.png)

**Comment by dmzoneill** [comment]
ive added die() to the script, if i cant find the config file

https://github.com/jaggedsoft/php-binance-api/commit/731d6abe83fc00aae56853021d9d972129403f63

**Comment by saadamin** [comment]
change line 1044
echo "balanceData error: Please make sure your system time is synchronized: call $api->useServerTime() before this function" . PHP_EOL;
to
echo 'balanceData error: Please make sure your system time is synchronized: call $api->useServerTime() before this function' . PHP_EOL;

![image](https://user-images.githubusercontent.com/4682435/39537724-3b9073ea-4e5c-11e8-9f20-01287c1e1948.png)

now this error shows

![image](https://user-images.githubusercontent.com/4682435/39537763-5b8a1bb0-4e5c-11e8-85cd-9f86759dc6bd.png)

**Comment by dmzoneill** [comment]
this already resolved, and not the source of the problem.

if you look at the last commit above and checkout the code.  The script will now tell you it cant find the file.

**Comment by saadamin** [comment]
ok , cloned again , no change found

![image](https://user-images.githubusercontent.com/4682435/39538010-2261341c-4e5d-11e8-8ef3-61f6c6928f26.png)

**Comment by dmzoneill** [comment]
do you hav curl on that terminal

```
dave@dave-laptop:~/Desktop/crypto/php-binance-api$ nslookup api.binance.com
Server:		192.168.1.1
Address:	192.168.1.1#53

Non-authoritative answer:
api.binance.com	canonical name = d3h36i1mno13q3.cloudfront.net.
Name:	d3h36i1mno13q3.cloudfront.net
Address: 52.85.201.186
Name:	d3h36i1mno13q3.cloudfront.net
Address: 52.85.201.37
Name:	d3h36i1mno13q3.cloudfront.net
Address: 52.85.201.113
Name:	d3h36i1mno13q3.cloudfront.net
Address: 52.85.201.180
```
curl
```
dave@dave-laptop:~/Desktop/crypto/php-binance-api$ curl -vvv https://api.binance.com
* Rebuilt URL to: https://api.binance.com/
*   Trying 52.85.201.180...
* TCP_NODELAY set
* Connected to api.binance.com (52.85.201.180) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=KY; L=Grand Cayman; O=Binance Holdings Limited; OU=IT; CN=*.binance.com
*  start date: Feb 27 00:00:00 2018 GMT
*  expire date: Feb 27 12:00:00 2020 GMT
*  subjectAltName: host "api.binance.com" matched cert's "*.binance.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=GeoTrust RSA CA 2018
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55789daf7ce0)
> GET / HTTP/1.1
> Host: api.binance.com
> User-Agent: curl/7.52.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< content-type: text/html; charset=utf-8
< content-length: 612
< date: Wed, 02 May 2018 17:08:00 GMT
< server: nginx
< last-modified: Mon, 04 Dec 2017 13:54:23 GMT
< vary: Accept-Encoding
< etag: "5a25538f-264"
< strict-transport-security: max-age=31536000; includeSubdomains
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< content-security-policy: default-src 'self'
< x-content-security-policy: default-src 'self'
< x-webkit-csp: default-src 'self'
< cache-control: no-cache, no-store, must-revalidate
< pragma: no-cache
< expires: 0
< accept-ranges: bytes
< x-cache: Miss from cloudfront
< via: 1.1 3e55621828a782063ebdaf11bf7ed303.cloudfront.net (CloudFront)
< x-amz-cf-id: QTCwGUq1sJeB1ysILxpYrXOhI8-oqRjs-XArNYXO1tUATvNCkPCk3g==
< 
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
* Curl_http_done: called premature == 0
* Connection #0 to host api.binance.com left intact
```

**Comment by saadamin** [comment]
its finds the config.json file

![image](https://user-images.githubusercontent.com/4682435/39538241-fcf13e6a-4e5d-11e8-83ab-fc27ccc197ca.png)

**Comment by dmzoneill** [comment]
yes, i've moved on from this.
are you able to run the above commands?

**Comment by saadamin** [comment]
yes
![image](https://user-images.githubusercontent.com/4682435/39538457-b6da9a9c-4e5e-11e8-9f14-300e35d64bdb.png)

**Comment by saadamin** [comment]
working fine with -k parameter , but running successfully without any problem other api , is that cause of php7 ?

![image](https://user-images.githubusercontent.com/4682435/39539088-91659ac6-4e60-11e8-8679-2b4f18526cbf.png)

**Comment by jaggedsoft** [comment]
@saadamin please revoke those api keys and generate some new ones since they were posted publicly

This package is better used from command line than in a webserver environment

**Comment by saadamin** [comment]
changing this done the job

![image](https://user-images.githubusercontent.com/4682435/39541707-5b929874-4e68-11e8-9c8b-241025f2f188.png)

**Comment by dmzoneill** [comment]
You changed out one option with a completely different option.  

If you continue to use this is will break on each successive version we release for you.

By turning off peer verification you are compromising your security.  This is not a fix.  

The fix is to update the ca bundle

**Comment by dmzoneill** [comment]
glad you have solved the CA issue, would feel bad if i left you off with security disabled.

enjoy
