### ISSUE TITLE
Unable to load config from: /root/.config/jaggedsoft/php-binance-api.json

### ISSUE THREAD

**Issue by mpjraaij** [jaggedsoft/php-binance-api#141]
**Suddenly config is unable to load**
I get Unable to load config from: /root/.config/jaggedsoft/php-binance-api.json when I try to run the package

**Platform:**
Linux

**Framework:**
Laravel

**Long description:**
I've also tried re-uploading from scratch and rolling back to previous (working) versions, but everything stopped working. How can I solve this?

Thank you

**Comment by dmzoneill** [comment]
How are you constructing the class?

```php
.......
```

**Comment by dormadekhin-denis** [comment]
I had the same problem, and apparently it appears due to the fact that if the file with the configuration is not found, then the execution stops:
```
private function setupApiConfigFromFile(string $file = null)
    {
        $file = is_null($file) ? getenv("HOME") . "/.config/jaggedsoft/php-binance-api.json" : $file;

        if (empty($this->api_key) === false || empty($this->api_key) === false) {
            return;
        }
        if (file_exists($file) === false) {
            die("Unable to load config from: " . $file . PHP_EOL);
        }
        $contents = json_decode(file_get_contents($file), true);
        $this->api_key = isset($contents['api-key']) ? $contents['api-key'] : "";
        $this->api_secret = isset($contents['api-secret']) ? $contents['api-secret'] : "";
    }
```

**Comment by dormadekhin-denis** [comment]
and still the same line with the stoppage of the script in several other functions

**Comment by dmzoneill** [comment]
Please the code you are using for your constructors

The only valid ones in the current releae are:
https://github.com/jaggedsoft/php-binance-api/blob/master/examples/constructor.php

**Comment by dormadekhin-denis** [comment]
I call the constructor like this:
`$api = new Binance\API();`

**Comment by dmzoneill** [comment]
If you call the constructor with no parameters. Then you must provide the file with valid configuration

```
~/.config/jaggedsoft/php-binane-api.json
```

**Comment by dormadekhin-denis** [comment]
and where can I take an example of a standard configuration?

**Comment by dmzoneill** [comment]
**wiki**
https://github.com/jaggedsoft/php-binance-api/wiki

**config file page**
https://github.com/jaggedsoft/php-binance-api/wiki/5.-Advanced-config-&-Proxy

**examples**
https://github.com/jaggedsoft/php-binance-api/blob/master/examples/constructor.php

**Comment by dormadekhin-denis** [comment]
@dmzoneill, If I do not use API-keys, do I leave fields with them in the value `false`?

**Comment by dmzoneill** [comment]
author hasn't followed up in 5 days. moving to close

**Comment by dormadekhin-denis** [comment]
@dmzoneill, Well, after all, I gave an example of how I create a class, without argument, and such a call leads to error
Let's review the constructor code:
```
 public function __construct()
    {
        $param = func_get_args();
        switch (func_num_args()) {
            case 0:
                $this->setupApiConfigFromFile();
                $this->setupProxyConfigFromFile();
                $this->setupCurlOptsFromFile();
                break;
            case 1:
                $this->setupApiConfigFromFile($param[0]);
                $this->setupProxyConfigFromFile($param[0]);
                $this->setupCurlOptsFromFile($param[0]);
                break;
            case 2:
                $this->api_key = $param[0];
                $this->api_secret = $param[1];
                break;
            default:
                echo 'Please see valid constructors here: https://github.com/jaggedsoft/php-binance-api/blob/master/examples/constructor.php';
        }
    }
```
I call the constructor without parameters, we get into 
```
    case 0:
            $this->setupApiConfigFromFile();
            $this->setupProxyConfigFromFile();
            $this->setupCurlOptsFromFile();
            break;
```
call the first function
```
 private function setupApiConfigFromFile(string $file = null)
    {
        $file = is_null($file) ? getenv("HOME") . "/.config/jaggedsoft/php-binance-api.json" : $file;
        if (empty($this->api_key) === false || empty($this->api_key) === false) {
            return;
        }
        if (file_exists($file) === false) {
            die("Unable to load config from: " . $file . PHP_EOL);
        }
        $contents = json_decode(file_get_contents($file), true);
        $this->api_key = isset($contents['api-key']) ? $contents['api-key'] : "";
        $this->api_secret = isset($contents['api-secret']) ? $contents['api-secret'] : "";
    }
```
and in the first line we see that if the file is not transferred then we try to get it on the standard path, but if this file is not found, then execution is terminated:
```
if (file_exists($file) === false) {
            die("Unable to load config from: " . $file . PHP_EOL);
        }
```
That is it turns out it is impossible to cause the designer without parameters though in the message above wrote that so it is possible to cause, and in the documentation such call is:
```
$api1 = new Binance\API();
$balances1 = $api1->balances();
print count($balances1) . "\n";
```
In previous versions of this was not

**Comment by dmoneil2** [comment]
Sorry, I'm having difficulty understanding the premise of this statement 

```
That is it turns out it is impossible to cause the designer without parameters though in the message above wrote that so it is possible to cause, and in the documentation such call is:```

Can you please rephrase it?

What does the output of the following give you?
```bash
result=$(php -r "print getenv(\"HOME\") . \"/.config/jaggedsoft/php-binance-api.json\";")
if [ ! -f $result ]; then echo "File does not exist"; fi
```

Please provide valid debug

Thank you

**Comment by jaggedsoft** [comment]
I think he wants to run this with no api key and no file

**Comment by jaggedsoft** [comment]
@dmzoneill 
Yes if the config file is not found it would be desirable to continue operation. The necessary functions will complain if an API key is not found or return the proper invalid response

**Comment by jaggedsoft** [comment]
@dmoneil2 For now you can use the constructor like this
```php
$api = new Binance\API('','');
```


dmzoneill:
> Test with no constructor
```php
require 'vendor/autoload.php';
$api = new Binance\API();
if ( $ticker && count($ticker) > 0 ) echo "prices(): successful\n";
```

Thank you!!!

**Comment by dormadekhin-denis** [comment]
@dmzoneill, Yes I want to use without configuration file and without api-keys

**Comment by dmzoneill** [comment]
Okay.

**Comment by andrewpros** [comment]
Why was those constructors even changed like that, yes i knew constructors code will get cleaned, but why forcing anyone to use a file just to have own $curlOpts, this wont work now

`$this->api = new API(config::$apikey, config::$apisecret, [
			'curlOpts' => [
				'CURLOPT_SSL_VERIFYPEER' => false
			]
		], null);`

**Comment by jaggedsoft** [comment]
Yes I agree it was the right move to make. There are only a few insecure WAMP installations out there and this problem can be solved simply by installing the certificate authority bundles

**Comment by andrewpros** [comment]
Well i just extended API and now have access to curlOpts from this class, so either make curlOpts public or add function to set it manually, im sure a lot less ppl are using it on dev env so u could at least provide access to curlOpts from API class and just dont make it harder that it really needs to be.
On most hosting providers a config in file is not making any difference, it is not more secure if something happens with web server anything can go wrong.
Besides u know, u can still use a file even if u use 2 parameter constructor, it is just your file, read by your code.

**Comment by andrewpros** [comment]
Ha, yeah, totally forgot that.

**Comment by antimech** [comment]
How to ignore the config. I want to use public methods only.

**Comment by andrewpros** [comment]
@antimech just provide empty api key and secret

**Comment by antimech** [comment]
@andrewpros I tried, it doesn't work. Also it created two ca.pem files, one of them is in the public directory.

**Comment by andrewpros** [comment]
@antimech then its something else u are probably asking, it works even without any params

**Comment by antimech** [comment]
@andrewpros thanks. I found [the answer](https://github.com/jaggedsoft/php-binance-api/blob/1d22afb4bcf60d2321403433b18726ba1e50380d/php-binance-api.php#L866).

**Comment by wirut2522** [comment]
Help Me.

Unable to load config from: /.config/jaggedsoft/php-binance-api.json
No proxies will be used 
Unable to load config from: /.config/jaggedsoft/php-binance-api.json
No curl options will be set

**Comment by wirut2522** [comment]
don't have /.config/jaggedsoft/php-binance-api.json   in  folder project
