### ISSUE TITLE
code":-1021,"msg":"Timestamp for this request is outside of the recvWindow.

### ISSUE THREAD

**Issue by LiveRock** [jaggedsoft/php-binance-api#143]
**Error 1021**
- bug: signedRequest error
- feature: how to fix
- enhancement: 

**Short Description:**
Tried the 0.example with valid credentials with the following errors:
signedRequest error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."} balanceData error: Please make sure your system time is synchronized, or pass the useServerTime option. 
  
**Platform:**
CentOS

**php version:**
- 7.0.24

**Long descrption**
Tried the 0.example with valid credentials with the following errors:
signedRequest error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."} balanceData error: Please make sure your system time is synchronized, or pass the useServerTime option. 

**code**
```php
require 'vendor/autoload.php';
$api = new Binance\API("<api key>","<secret>");
$ticker = $api->prices();
print_r($ticker); // List prices of all symbols
echo "Price of BNB: {$ticker['BNBBTC']} BTC";
```

**result**
Price of BNB: BTC. signedRequest error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."} balanceData error: Please make sure your system time is synchronized, or pass the useServerTime option. BTC owned: ETH owned: Estimated Value: 0 BTC

thank you

**Comment by dmzoneill** [comment]
Please see the following page

https://github.com/jaggedsoft/php-binance-api/wiki/4.-Troubleshooting

**Comment by LiveRock** [comment]
This from my OSX machine, not my server:
* Rebuilt URL to: https://api.binance.com/
*   Trying 54.230.149.128...
* TCP_NODELAY set
* Connected to api.binance.com (54.230.149.128) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=KY; L=Grand Cayman; O=Binance Holdings Limited; OU=IT; CN=*.binance.com
*  start date: Feb 27 00:00:00 2018 GMT
*  expire date: Feb 27 12:00:00 2020 GMT
*  subjectAltName: host "api.binance.com" matched cert's "*.binance.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=GeoTrust RSA CA 2018
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7faaa9804000)
> GET / HTTP/2
> Host: api.binance.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< content-type: text/html; charset=utf-8
< content-length: 612
< date: Tue, 08 May 2018 11:34:49 GMT
< server: nginx
< last-modified: Mon, 04 Dec 2017 13:54:23 GMT
< vary: Accept-Encoding
< etag: "5a25538f-264"
< strict-transport-security: max-age=31536000; includeSubdomains
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< content-security-policy: default-src 'self'
< x-content-security-policy: default-src 'self'
< x-webkit-csp: default-src 'self'
< cache-control: no-cache, no-store, must-revalidate
< pragma: no-cache
< expires: 0
< accept-ranges: bytes
< x-cache: Miss from cloudfront
< via: 1.1 4b1a1b772537d6df0d0826b5218c4f49.cloudfront.net (CloudFront)
< x-amz-cf-id: n23MmvXEOiRu43s65Y0RYB1wkiYrMSyCWLKlS7JBXfPYT7nZp3PnXg==
< 
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
* Connection #0 to host api.binance.com left intact

**Comment by dmzoneill** [comment]
Hey, the output from your osx machine is no value here.

In order to find the source of the issue, there are a number of things you need to validate/fix.

- you're not on a blocked vps hosting service
- time on your server is madly out of date
- keys are correct. Surprisingly people often have invalid keys, (read only)
- the dns is correct, binance have some weird dns issues in some parts of the world
- the certificate authority bundle is correct and up to date
- the ip address of your server is not banned

By running the above command you knock 4 of the items of the list.

**Comment by dmzoneill** [comment]
If you have no console access you could try somethibg like

```
<?php

print "<pre>";
print shell_exec ("curl -vvv https://api.binance.com 2>&1");
print "</pre>";

**Comment by LiveRock** [comment]
You are right. I copied and paste Binance API credentials again and now it works.
Many thanks!

**Comment by LiveRock** [comment]
Another question not related to the issue. Is it possible for me to extract the following information at a given date/time?
Cryptocurrency: for example, BTC
Exchange currency: for example, USDT
Volumne
% change 24 hour
High
Low

**Comment by dmzoneill** [comment]
i don't think there is a function for that or specifically exposed by the binance API.

might be a nice feature here if you want to create a full request, if i understand you correctly

**psuedo code**
```
function getPErcentageChangeBetweenDates( older, newer )
{
   // get average on these dates from candle information
   // minus the 2 averages
   $diff = ( $older-avg/ $newer-avg ) * 100;
   return $diff;
}
```
