### ISSUE TITLE
How to get the last prices from the WebSocket

### ISSUE THREAD

**Issue by Marc008** [jaggedsoft/php-binance-api#144]
Hello,

I'm wondering if it's possible to get the last price from all symbol through any WebSocket. Like you can do with the REST API:

`$api->prices();`

The idea is if a price reaches a certain value, then to trigger an action (submit an stop loss or a take profit).

If not possible, I'm checking the exchangeInfo output and it looks like I could do up to 1,200 calls per minute. The price() method, according to Binance docs, has a weight of 1, so even I check the price 1 time per second, that can't be considered abusing the API, right?

Just looking for the best way to handle this.

Thanks!

**Comment by dmzoneill** [comment]
Simple answer is no.  

Longer answer, yes: 
prices() is basically a simpler version of Candlestick Open High Low Close (OHLC) information.
OHLC infomration can be found in candlestick/kline.

**Kline/Candlestick Streams**
https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md

You can just pull a timestamp off the 24hr candlestick array for a given symbol(s)

**Comment by Marc008** [comment]
@dmzoneill thanks for your answer,

The last price would be the "Close" value of the Candlestick, right?

Again thank you very much.
