### ISSUE TITLE
Websocket is clogging up memory in Laravel

### ISSUE THREAD

**Issue by mpjraaij** [jaggedsoft/php-binance-api#145]
I'm using this package to call in information from a trading ticker. Here is my code:

        $api = new BinanceAPI($this->key, $this->secret);
        $api->ticker(false, function($api, $symbol, $ticker) {
            event(new NewTickerEvent($ticker));
        });

What happens is that a never ending loop is created. The memory gets used, but never released. I've tried everything from __destruct methods with unset, null, garbage collection, etc.

Memory just keeps clogging up, it's like it's never released inside this loop.

How can I solve this issue so that after each 'tick' the memory gets released.

The new ticker event calls this piece of code (which is helping clogging up the memory) in the Listener:

        $exchange = Exchange::where('name', 'binance')->where(function ($query) use ($symbol) {
            $query->whereHas('rules', function ($query) use ($symbol) {
                $query->ofPair($symbol)->whereHas('trades', function ($query) {
                    $query->where('active', 1)->whereHas('user.subscriptions', function ($query) {
                        $query->where('stripe_plan', '!=', 'free');
                    });
                });
            });
        })
        ->first();

        // Only continue if there's a trade active
        if ($exchange == null) {
            return;
        }

        $exchange->load([
            'rules' => function ($query) use ($symbol) { $query->ofPair($symbol); },
            'rules.trades' => function ($query) {
                $query->where('active', 1)->whereHas('user.subscriptions', function ($query) {
                    $query->where('stripe_plan', '!=', 'free');
                });
            },
            'rules.trades.user', 'rules.trades.targets.tradeApi',
            'rules.trades.buyOrder', 'rules.trades.takeProfitOrders', 
            'rules.trades.originStopLossOrder', 'rules.trades.trailingStopLossOrder',
        ]);

**Comment by GalacticSun** [comment]
I've been running this same $api->ticker code in a PHP script as a background process, and it dies / is killed every few days (Ubuntu Linux).  It's happened twice now since I set it up.  I'm guessing it is to do with memory usage (because that is a common reason why the kernel will kill a process).  Any insights?  Thanks.

**Comment by jaggedsoft** [comment]
Yes I would say the #1 cause of a killed process is an out of memory error.
I am running my code 24/7 flawlessly on a VPS with only 256mb of memory. However, I have set up a swap file so the process will never be terminated.

Calling $api->ticker is a simple web request. Nothing gets stored in memory. So there is nothing we can do to fix this issue.

**Comment by jaggedsoft** [comment]
I have not tested if websocket reconnect is implemented properly in the PHP library. I thought it was but it might not be.

**Comment by dmzoneill** [comment]
The 24hr issue we need tonadd the backlog.. issues present in node and php.

Not really something we can test in travis...
