### ISSUE TITLE
Web socket status handling

### ISSUE THREAD

**Issue by q00n** [jaggedsoft/php-binance-api#149]
Hello, i have few questions:
1) Is there some way to catch web socket connection errors?
2) Sometimes the ticker doesn't return anything (including errors, it's just broken and returns nothing until I restart it), how to handle it? It's hard to replicate

```
$api->ticker(false, function($api, $symbol, $ticker) {
    var_dump($symbol);
}
```

**Comment by jaggedsoft** [comment]
I am starting to hear more reports of connection problems. I'm not sure what happened, for months and months everything was working flawlessly with no problems. I will investigate, but my time is very limited as I'm moving to malta in the next week.

**Comment by diegovarussa** [comment]
+1

**Comment by GalacticSun** [comment]
+1

**Comment by val-rot** [comment]
Yes I have the same problem, i cant look on realtime candles....

So this example are give nothing call back:

$api->getChart(["BNBBTC"], "15m", function($api, $symbol, $chart) {
    echo "{$symbol} chart update\n";
    echo "<pre>".print_r($chart,true)."</pre>";
});

Anyone have a example how we can work with this?

**Comment by jaggedsoft** [comment]
This package needs your help. I am willing to accept any pull requests. Unfortunately my time is extremely limited recently
