### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by normtomlins** [jaggedsoft/php-binance-api#15]
Hi,

I am running your examples and I am getting the following errors when I make this call 
$balances = $api->balances($ticker);

Among other errors.

PHP Notice:  Undefined index: balances in /root/php-binance-api/php-binance-api.php on line 178
PHP Warning:  Invalid argument supplied for foreach() in /root/php-binance-api/php-binance-api.php on line 178
PHP Notice:  Undefined index: BTC in /root/php-binance-api/examples/example2.php on line 11
PHP Notice:  Undefined index: ETH in /root/php-binance-api/examples/example2.php on line 12

**Comment by jaggedsoft** [comment]
I plan to make the error reporting better in a future release
I suspect your API key is put in wrong or not working

**Comment by jaggedsoft** [comment]
Complete example

```php
$api = new Binance\API("<your key>","<your secret>");
$ticker = $api->prices();
//print_r($ticker); // List prices of all symbols
//echo "Price of BNB: {$ticker['BNBBTC']} BTC.".PHP_EOL;
$balances = $api->balances($ticker);
print_r($balances);
```

**Comment by normtomlins** [comment]
Okay, so I realized I was using the wrong key from another exchange... it was late.. :)    Anyways, everything is working except the live streaming

$api->depthCache(["BNBBTC"], function($api, $symbol, $depth) {

Gives the following errors

HP Warning:  Missing argument 2 for Binance\API::depthCache(), called in /root/php-binance-api/php-binance-api.php on line 442 and defined in /root/php-binance-api/php-binance-api.php on line 421
PHP Notice:  Undefined variable: callback in /root/php-binance-api/php-binance-api.php on line 428
PHP Notice:  Undefined variable: callback in /root/php-binance-api/php-binance-api.php on line 432
PHP Notice:  Undefined variable: callback in /root/php-binance-api/php-binance-api.php on line 456
PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, no array or string given in /root/php-binance-api/php-binance-api.php on line 456
PHP Warning:  Missing argument 2 for Binance\API::depthCache(), called in /root/php-binance-api/php-binance-api.php on line 442 and defined in /root/php-binance-api/php-binance-api.php on line 421

**Comment by jaggedsoft** [comment]
This error was a typo on my part. Sorry
If you go to your project directory and issue a `composer update` it should be fixed. Thanks :)
