### ISSUE TITLE
prices() error since this morning

### ISSUE THREAD

**Issue by vreesie18** [jaggedsoft/php-binance-api#151]
Since this morning (running for weeks succesfully) I get an error message on running the following code:

	$binance_api = new Binance\API(bncrdsfile());	

	// Get latest price of a symbol
	$binance_ticker = $binance_api->prices();

Error:

Fatal error: Uncaught TypeError: Argument 1 passed to Binance\API::priceData() must be of the type array, null given, called in /var/www/xxxx.xx/php-binance-api/php-binance-api.php on line 700 and defined in /var/www/xxxx.xx/php-binance-api/php-binance-api.php:1367 Stack trace: #0 /var/www/xxxx.xx/php-binance-api/php-binance-api.php(700): Binance\API->priceData(NULL) #1 /var/www/xxxx.xx/binance_test_websockets.php(11): Binance\API->prices() #2 {main} thrown in /var/www/xxxx.xx/php-binance-api/php-binance-api.php on line 1367

**Comment by vreesie18** [comment]
out of the blue it's working again, probably it's binance related.

**Comment by tongplates** [comment]
I am getting the same error. At the beginning I received an empty array. All others methods working fine. But after 6 hours I am receiving "null given" error like main post with all methods. It does no matter which api method I am using (balance, prices, candlestick, etc) I always getting "null given" error. Whats wrong? Is that a binance issue or php-binance-api issue?

**Comment by jaggedsoft** [comment]
Binance is down right now I believe
There is a function to check the api status, but I can't remember the name off the top of my head
