### ISSUE TITLE
Error in line 2126 php-binance-api.php

### ISSUE THREAD

**Issue by vreesie18** [jaggedsoft/php-binance-api#152]
After upgrading this morning to he newest php-binance-api version, I get the following error message:

Custom error: [2] fwrite() expects parameter 1 to be resource, boolean given
Error on line 2126 in /var/www/xxxx.xxx/vendor/jaggedsoft/php-binance-api/php-binance-api.php 

And line 2126 contains the following code (2126 is the bold part):

    private function downloadCurlCaBundle()
    {
        $output_filename = getcwd() . "/ca.pem";

        $host = "https://curl.haxx.se/ca/cacert.pem";
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, $host);
        curl_setopt($curl, CURLOPT_VERBOSE, 0);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($curl, CURLOPT_HEADER, 0);
        curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0);

        // proxy settings
        if (is_array($this->proxyConf)) {
            curl_setopt($curl, CURLOPT_PROXY, $this->getProxyUriString());
            if (isset($this->proxyConf['user']) && isset($this->proxyConf['pass'])) {
                curl_setopt($curl, CURLOPT_PROXYUSERPWD, $this->proxyConf['user'] . ':' . $this->proxyConf['pass']);
            }
        }

        $result = curl_exec($curl);
        curl_close($curl);

        $fp = fopen($output_filename, 'w');
        **fwrite($fp, $result);**               <======
        fclose($fp);
    }

**Comment by dmzoneill** [comment]
fopen returns false on fopen failure, check to see you have write permission.

To the following location.

```
dave@dave-pc:~$ php -r "echo getcwd() . \"/ca.pem\n\";"
/home/dave/ca.pem
```

**Comment by dmzoneill** [comment]
additional checks and error messages added in latest version
https://github.com/jaggedsoft/php-binance-api/commit/19faf433dcec978aadb475139b3ee4f5158ee179

**Comment by vreesie18** [comment]
Thanksss!!
