### ISSUE TITLE
Problem with buy function

### ISSUE THREAD

**Issue by payrollDevops** [jaggedsoft/php-binance-api#157]
**Title**  Problem with buy function
- bug: buy function
- feature: examples / orders  --> market order
- enhancement: add this to existing features

**Short Description:**
- Value of price stays 0.00000
  
**Platform:**
- windows with Xamp

**php version:**
- 7.0.24

**Long descrption**
 - buy doesnt return correct values

**code**
$quantity = 1;
	$ticker = $api->prices();
	
	$buyprice = $ticker['CNDBTC'];
	$order = $api->buy("CNDBTC", $quantity, $buyprice, "MARKET");

	echo "<pre>";
	print_r($order);
	echo "</pre>";

	$symbol = $order['symbol'];
	$orderid = $order['orderId'];
	$price = $order['price'];
	$time = $order['transactTime'];

returns:
    [symbol] => CNDBTC
    [orderId] => orderid
    [clientOrderId] => myorder id
    [transactTime] => 1528727561969
    [price] => 0.00000000       <--------   this is my issue here.   value of ticker returns the value of 0.0000701
    [origQty] => 1.00000000
    [executedQty] => 1.00000000
    [status] => FILLED
    [timeInForce] => GTC
    [type] => MARKET
    [side] => BUY

The value of the order history works fine.
Code used: $history = $api->history("CNDBTC");

**Comment by dmzoneill** [comment]
@jaggedsoft @payrollDevops 

I dont ebelieve there is anything we can do here, this is the response from Binanace, there are also cases were this is an empty response {}.

Suggest you put a check in your code to query the last buy order

# psuedo code such as
# get last buy order for CNDBTC
# buy CNDBTC
# get last buy order
# if the buy order is differnet
# buy order successfull
# get the price from the order

**Comment by jaggedsoft** [comment]
When doing market buys you have to set `newOrderRespType` to `FULL` in order to get the complete response of order fills, like this:
```php
$order = marketBuy('BNBBTC', 1, ["newOrderRespType"=>"FULL"]);
print_r($order);
```

This returns an array of `fills` which includes `price, qty, commission, commissionAsset, and tradeId`
![39147371-5499f73a-4731-11e8-90b5-089340a83ddc](https://user-images.githubusercontent.com/4283360/41242714-1eee7292-6d55-11e8-8801-35ab1c32f7b2.png)

**Comment by payrollDevops** [comment]
thanks a lot for your quick answer.  Keep up the good work.

**Comment by quadricanna** [comment]
Hi Jaggedsoft,

I still can't extract  price from the 'fills' array. Also is this for only applicable buy orders or both market buy and sell?.
Please see code below:

  $lastorder = $api->marketBuy(BNBUSDT, 5, ["newOrderRespType"=>"FULL"]);

				$bought_price = $lastorder['fills']['price'];
