### ISSUE TITLE
Default value for parameters with a class type hint can only be NULL

### ISSUE THREAD

**Issue by ahab1b** [jaggedsoft/php-binance-api#158]
Guys, I tried by installing via composer and manually but keep seeing this error.
I have not setup the config file in home directory so I use $api = new Binance\API("key","secret");
I still get the same error when I use $api = new Binance\API(); and according to the php-binance-api.php file, if i do not specify the api key the error should be "Detected no API KEY or SECRET, all signed requests will fail"
API key is new and just setup but i tested on the old single version and the prices loaded.
Is there something I am doing wrong?

thank you

**Comment by dmzoneill** [comment]
Hi you need to update your php version.

This error is typically related to PHP < 7

Will not work with PHP5

**Comment by jaggedsoft** [comment]
Yeah this bug was fixed awhile ago, and PHP 7.1 is actually surprisingly easy to upgrade to and much faster, so I recommend you try it! If you need any help feel free to ask

**Comment by ahab1b** [comment]
Thanks for the help. I updated php and it now works.
