### ISSUE TITLE
Autoload not working in Lumen

### ISSUE THREAD

**Issue by ilman** [jaggedsoft/php-binance-api#16]
Hi, 

I am tried to install your package in lumen, but somehow the class not autoloaded. I have check its autoloaded fine if I use simple php + composer though.

**Comment by jaggedsoft** [comment]
I will look in to getting this to work with laravel, but my time is very limited lately
I hope we can get this to work, I will let you know if I have progress

**Comment by vitoo** [comment]
FYI
With this cmd i hac an old version of your lib v0.02
`composer require "jaggedsoft/php-binance-api @dev"
`
I had to add this to composer.json
"jaggedsoft/php-binance-api": "dev-master",

So maybe the right cmd is 

`composer require "jaggedsoft/php-binance-api dev-master"`

**Comment by jaggedsoft** [comment]
Interesting, thank you!

**Comment by jsgv** [comment]
I am unable to get it to work with Laravel 5.5.
Attempted the suggestions above.

**Comment by vitoo** [comment]
I'm using Laravel 5.4 

What's your error ?

**Comment by jsgv** [comment]
@vitoo My mistake. It does work like you said above with 
`composer require "jaggedsoft/php-binance-api dev-master"`

Thanks
