### ISSUE TITLE
Order and openOrder shows "Timestamp for this request is outside of the recvWindow"

### ISSUE THREAD

**Issue by ahab1b** [jaggedsoft/php-binance-api#161]
**Short Description:**
When I use the code provided in the documentation

$openorders = $api->openOrders("GNTBTC");
print_r($openorders);
**or** 
$orders = $api->orders( "GNTBTC" );
print_r($orders);

This gives this error. But it seems this is coming from Binance directly.
signedRequest error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."} Array ( [code] => -1021 [msg] => Timestamp for this request is outside of the recvWindow. ) 

FYI. I actually do have an open order on Binance. I saw in the code that it will either throw an error if no orders show or show the order.
 
**Platform:**
- windows

**php version:**
- 7.1

thank you

**Comment by dmzoneill** [comment]
Hi and welcome,

All requests to the server are time sensitive.
Please check the time on your computer is correct and synchronizing with a good time source.

Failing that, you can use 

```
//Call this before running any functions
$api->useServerTime();

// your code
```

**Comment by ahab1b** [comment]
Thanks that worked.
