### ISSUE TITLE
bug: Signature for this request is not valid

### ISSUE THREAD

**Issue by LobachevA** [jaggedsoft/php-binance-api#163]
**Short Description:**
- Unable to get a result for account balance
  
**Platform:**
- linux

**php version:**
- 7.0.30

**Long descrption**
- Doing action for getting account balance and failing with error:
signedRequest error: {"code":-1022,"msg":"Signature for this request is not valid."}

**code**
```php
require 'vendor/autoload.php';
$api = new Binance\API("<api key>","<secret>");
$ticker = $api->prices();
$balances = $api->balances($ticker);
print_r($balances);
```

**result**
```
{
   signedRequest error: {"code":-1022,"msg":"Signature for this request is not valid."}
}
```

thank you

**Comment by ildarius** [comment]
same here, but no signature error just

array(0) { }

when trying to print out $balances

identical code

require 'binance_API/vendor/autoload.php';
$api = new Binance\API("k","s");

$ticker = $api->prices();
$balances = $api->balances($ticker);

**Comment by dmzoneill** [comment]
Binance invalidated all keys last few days.  I presume you have made new keys?

**Comment by ildarius** [comment]
just refreshed API keys and also updated to latest version of the API

it does show the value of $ticker, but the $balances is still blank

is there a way to output any message from binance when we
do $api->balances($ticker);
to make it easier to troubleshoot

**Comment by ildarius** [comment]
has to be a server issue, when I run the same code on local machine it works

not sure why binance returns $ticker, but not $balances when executing the
same script on a remote server

**Comment by dmzoneill** [comment]
Hey,

You can try

$api->httpDebug = true;

This will turn on curlopt_verbose

Im travelling at the moment, so i cant verify the report until tomorrow at the earliest..

In the last upgrade they chnage the api interface for performance.  May have broken something..

**Comment by dmzoneill** [comment]
Ticker is public api and doesnt need to be signed.. 

Balances needs to be signed.. possible that there is some blocking of your host going on.. but usually that wouod give an error indicating so

**Comment by ildarius** [comment]
and now it works on the remote server also

:-|

K i'm going to sleep now, this is just binance being binance i guess

**Comment by dmzoneill** [comment]
Cool.. the binance load balancer is flakey.  Dont assume the result to be 100% each time.. appropriate checks

**Comment by ildarius** [comment]
confirmed, thanks for the tip and the replies while traveling

good night!

**Comment by LobachevA** [comment]
Update keys and looks like working! Maybe we can close issue.
