### ISSUE TITLE
Error: Indirect modification of overloaded property Binance\API::$options has no effect

### ISSUE THREAD

**Issue by GalacticSun** [jaggedsoft/php-binance-api#165]
**Title**
I'm getting the following error:
`Indirect modification of overloaded property Binance\API::$options has no effect`
  
**Platform:**
- linux

**php version:**
- 7.1.12

**Long descrption**
I'm getting the following error:

`PHP Notice:  Indirect modification of overloaded property Binance\API::$options has no effect in /nginx/html/vendor/jaggedsoft/php-binance-api/php-binance-api.php on line 2031`

It appears to be related to this line:
`$listenKey = $this->options['listenKey'] = $response['listenKey'];`

I'm on the latest code.  Any ideas as to why this might be occurring?

I saw someone in the Binance API Telegram chat yesterday had this same error, too.

Not sure, but could this help solve the problem?
https://phpolyk.wordpress.com/2012/07/25/indirect-modification-of-overloaded-property/

**Code**
I'm using the User Data Websocket code from your Github page:

`$balance_update = function($api, $balances) {`
`	print_r($balances);`
`	echo "Balance update".PHP_EOL;`
`};`

`$order_update = function($api, $report) {`
`	echo "Order update".PHP_EOL;`
`	print_r($report);`
`	$price = $report['price'];`
`	$quantity = $report['quantity'];`
`	$symbol = $report['symbol'];`
`	$side = $report['side'];`
`	$orderType = $report['orderType'];`
`	$orderId = $report['orderId'];`
`	$orderStatus = $report['orderStatus'];`
`	$executionType = $report['orderStatus'];`
`	if ( $executionType == "NEW" ) {`
`		if ( $executionType == "REJECTED" ) {`
`			echo "Order Failed! Reason: {$report['rejectReason']}".PHP_EOL;`
`		}`
`		echo "{$symbol} {$side} {$orderType} ORDER #{$orderId} ({$orderStatus})".PHP_EOL;`
`		echo "..price: {$price}, quantity: {$quantity}".PHP_EOL;`
`		return;`
`	}`
`	//NEW, CANCELED, REPLACED, REJECTED, TRADE, EXPIRED`
`	echo "{$symbol} {$side} {$executionType} {$orderType} ORDER #{$orderId}".PHP_EOL;`
`};`
`$api->userData($balance_update, $order_update);`

thank you

**Comment by dmoneil2** [comment]
hey 

 I'm currently on business travel and i believe @jaggedsoft has limited availability.

i have reviewed the history of this function,  it was removed some time again and then re-merged

https://github.com/jaggedsoft/php-binance-api/commit/09011880abfa68b0d222f364e1c3c5636d41038f

i'm not certain it has been tested fully, i will take a look when i'm home sunday

thanks for the report.

**Comment by GalacticSun** [comment]
Ok, no problem.  Thanks.

**Comment by GalacticSun** [comment]
Any update on this, by chance?

**Comment by dmzoneill** [comment]
fixed: https://github.com/jaggedsoft/php-binance-api/commit/13a57be1fdea749f24267de440345e27f060b87a

i ran it, "swept the dust" and received web socket update

@jaggedsoft 
@GalacticSun

**Comment by GalacticSun** [comment]
Awesome, thanks guys!
