### ISSUE TITLE
Order does not work, no response at all.

### ISSUE THREAD

**Issue by aybarsm** [jaggedsoft/php-binance-api#167]
I was able to create order with my previous server with mod_php 7.1 + apache. I have ported to PHP-FPM + nginx. The only problem is ordering. I am not able to create an order with this class. I am able to use the rest of the functions such as ticker and candles. I wonder if there is a missing component for PHP in order to v3 order work but there is no error message at all, nothing. No messages in error.log either. I would be really happy if you can help me with the issue.

**[root@server logs]# php -v**
PHP 7.2.7 (cli) (built: Jun 20 2018 08:21:26) ( NTS )

**Platform:** 
[root@server logs]# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)

**Code:**
require_once "includes/vendors/binance-api/php-binance-api.php";
require_once 'includes/vendors/binance-api/vendor/autoload.php';
$api = new Binance\API('KEY', 'SECRET');
$rslt=$api->marketBuy(NPXSBTC, 1, array("newOrderRespType" => "FULL"));
print_r($rslt);

thank you.

**Comment by dmzoneill** [comment]
Ticker, candles etc dont require authentication..

When you created the key did you enable trading for the key?

To get verbose output from curl

$api->httpDebug = true:

$api->.....

**Comment by aybarsm** [comment]
@dmzoneill First of all, thank you so much for your response. I have just tried to pull my order history, that works too.  $rslt=$api->history("NPXSBTC");  -> this works. All 3 options of the key, read, trade, withdraw are enabled. The main IP of the server is whitelisted in the key.

 I have also tried;
$api->httpDebug = true;
$rslt=$api->marketBuy("NPXSBTC", 1, array("newOrderRespType" => "FULL"));
print_r($rslt);

No message at all, nothing.

**Comment by dmzoneill** [comment]
Im sorry i can't given a decent response right now, im travelling.. home tonight.

Binance upgraded there api during the last upgrade for performance reasons. There seems to be a few intermittant problems with orders doing nothing and then working again.  Just so you are aware.

Ill take a look into it when i get home..

**Comment by aybarsm** [comment]
Ohh ok, @dmzoneill thank you so much. I would be really if you can get back to me on this manner. I will give it a try on my old setup server and let you know about the outcome. I wonder if there is asomething srong with the timestamps as the old server had PHP timezone module and the new one does not have and timeoffset option in the class is always 0 as we are in UTC +3. Regards.

**Comment by aybarsm** [comment]
Update:

Yes there is something wrong with the new setup. I don't know what it is as there is no error, warning or notice message at all. Now I will compare the phpinfo states in order to understand missing or needed php module. I would be really happy if you can give me advice what module can make the difference. For example, candles and ticker does not require sign, does only order requires sign?

**Comment by aybarsm** [comment]
You can mark this thread as solved. I have resolved the the issue by updating curl package on the server. It was 7.29 and I updated to 7.60. Somehow it is probably related by either SSL or header issue. Thank you so much.

**Comment by dmzoneill** [comment]
Thanks for the update. Seems to be some minor subtleties in curl popping up. Will add it to the backlog
