### ISSUE TITLE
LOT_SIZE of pair?

### ISSUE THREAD

**Issue by LubomirKurpel** [jaggedsoft/php-binance-api#17]
Hi, thanks for a great code.

I am having trouble with LOT_SIZE, which is "minimum" rounded amount I need to send as request to Binance. Actually LOT is different for each pair (for most of them it is rounded to 2 decimal numbers), can I somehow pull the list of available LOT numbers? 

I did not however managed to find the whole lot size list, the best it would be to pull it directly from binance servers

https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#lot_size

Any way I can pull the data? Thanks a lot.

**Comment by jaggedsoft** [comment]
Yes, thank you!

$api->exchangeInfo();

See here for an example how to pull the fields into a nice format
https://github.com/jaggedsoft/node-binance-api/issues/23
I will make it easier as soon as I have time

**Comment by LubomirKurpel** [comment]
Thank you very much for a quick reply! Yes that would work. I am now writing a function to pull the data, thank you.
