### ISSUE TITLE
Trades History BUG

### ISSUE THREAD

**Issue by deadheadtn** [jaggedsoft/php-binance-api#170]
**Trades History BUG**
- bug: involded function $api->history()

**Short Description:**
- in the description it is mentioned that it is possible to grab the history trades without the pairs as parametr
  
**Platform:**
- windows
- linux

**php version:**
- 7.0.24

**Long descrption**
- Doing xyz results in ypr and failing when fph

**code**
```php
$history = $api->history();
print_r($history);
 
```

**result**
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Binance\API::history(), 0 passed in
```

thank you

**Comment by GalacticSun** [comment]
You need to pass in the currency pair, like this:
`$history = $api->history("BTCUSDT");`

As far as I know there is no way to get History for all pairs.

**Comment by dmzoneill** [comment]
Hi

The binace api says symbol is mandatory.

Get older trades.

Weight: 5

Parameters:

Name	Type	Mandatory	Description
symbol	STRING	YES	
limit	INT	NO	Default 500; max 500.
fromId	LONG	NO	TradeId to fetch from. Default gets most recen
