### ISSUE TITLE
EMA Calculation  Binance

### ISSUE THREAD

**Issue by vreesie18** [jaggedsoft/php-binance-api#171]
I know how to calculate an regular EMA but I'm not able te recalculate/check the EMA's values used by Binance. Does anyone know if the use some specific formula for their EMA's ???

No API yet to retrieve their EMA data either.

Many thanks in advance.

Regards,
André

**Comment by jaggedsoft** [comment]
these functions are built in to php
http://php.net/manual/en/function.trader-ema.php

just pass an array of 'close' values

**Comment by vreesie18** [comment]
Yes, thank you, you pointed that out to me earlier and I use that function at the moment. It works great. I checked it's results with an excel spreadsheet I made and the results match....only when I use the same data to check the Binance EMA's I don't get matches. I struggeling for many months now and I still cannot get a grip on the way Binance calculates their EMA.

**Comment by dmzoneill** [comment]
hey, 

Did you try open a support request with binance?
