### ISSUE TITLE
$api->history() doesn't work for all

### ISSUE THREAD

**Issue by fabsalito** [jaggedsoft/php-binance-api#173]
I have trades but the call to $api->history() doesn't return anything.
  
**Platform:**
- linux

**php version:**
- 7.1.19

Thank you.

**Comment by dmzoneill** [comment]
hi

"v3/myTrades" endpoint called by history() has "symbol" as mandatory.

https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

There is currently no way to query all trades via a single call, to my knowledge

@jaggedsoft 
@fabsalito
