### ISSUE TITLE
LIMIT Order not working PHP

### ISSUE THREAD

**Issue by val-rot** [jaggedsoft/php-binance-api#176]
Hello,

i tested the limit order on php, but not working.
i do this with the sample:

$quantity = 210;
$price = "0.00000480";
$order = $api->buy("TRXBTC", $quantity, $price);
print_r($order);

so the min limit for buy is 0.001 btc thats ok, but is not working.
i dont became an error or other thinks.

How i make wrong or?

thank you

**Comment by jaggedsoft** [comment]
`$price = "0.00000480";`
try changing this:
`$price = 0.00000480;`
Removing the quotes should allow it to work properly

**Comment by jaggedsoft** [comment]
you need to install with composer, since this installs required dependencies

then load the package like this
`require 'vendor/autoload.php';`

**Comment by dmzoneill** [comment]
Make sure that trading is enabled for the key.  By default when you create a key on the binance website; trading is disabled.

**Comment by val-rot** [comment]
Hello,
yes on binance are the trading enable. I need now a rootserver for ssh and can install the composer....

i think the composer are the problem. if i fixed that, i write here.

**Comment by jaggedsoft** [comment]
Yes unfortunately we had to use composer for the PHP api

Otherwise websockets don't work properly

**Comment by val-rot** [comment]
Now all right.

Thx for Help.
