### ISSUE TITLE
Symfony 4 skeleton, error on calling php binance api and php binance api rate limiter

### ISSUE THREAD

**Issue by derick222** [jaggedsoft/php-binance-api#177]
I want to call the Binance\API and Binance\RateLimiter in the controller, but because these two class have the same namespace. Symfony4 is returning an error "Attempted to load class "RateLimiter" from namespace "Binance". Did you forget a "use" statement for another namespace?"

here my sample code

<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Binance;

class LuckyController extends Controller
{
    /**
     * @Route("/lucky", name="lucky")
     */
    public function index()
    {

        $api = new Binance\API();
        $api = new Binance\RateLimiter($api);

        while(true) {
           print_r($api->history("BTCUSDT"));
           exit();
        }

    }
}

**Comment by dmzoneill** [comment]
Hi sorry, this code snippet does not help me understand the problem.

Can you elaborate further?

**Comment by dmzoneill** [comment]
Hey, 

I dont use symfony4 and have very limited time to investigate the namespace issue you are having in relation to this third party software.

If you would like to submit a patch that allows it to work with symfony4 as well as the documented usage, it would be greatly appreciated.

Maybe this might help:
https://stackoverflow.com/questions/27682446/symfony-use-statement-for-another-namespace-issue

**Comment by derick222** [comment]
Hi, I tried to put the declare the ratelimiter class in the autoload_static.php created by composer and it works but when I tried to update the composer, the composer only see the php-binance-api.ph int autoload classmap for the jaggedsoft bundle.  I included the installed.json file created by the composer after the update. Is their a way to include the ratelimiter class in the autolasd classmap when updating the composer.

{
        "name": "jaggedsoft/php-binance-api",
        "version": "v0.4.4",
        "version_normalized": "0.4.4.0",
        "source": {
            "type": "git",
            "url": "https://github.com/jaggedsoft/php-binance-api.git",
            "reference": "13a57be1fdea749f24267de440345e27f060b87a"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/jaggedsoft/php-binance-api/zipball/13a57be1fdea749f24267de440345e27f060b87a",
            "reference": "13a57be1fdea749f24267de440345e27f060b87a",
            "shasum": ""
        },
        "require": {
            "ext-curl": "*",
            "php": ">=7.0",
            "ratchet/pawl": "^0.3.0",
            "ratchet/rfc6455": "^0.2.3",
            "react/socket": "^1.0 || ^0.8 || ^0.7"
        },
        "require-dev": {
            "codacy/coverage": "dev-master",
            "phpunit/phpunit": "~6"
        },
        "time": "2018-07-14T12:09:54+00:00",
        "type": "library",
        "installation-source": "dist",
        "autoload": {
            "classmap": [
                "php-binance-api.php"
            ]
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "MIT"
        ],
        "description": "PHP Binance API is an asynchronous PHP library for the Binance API designed to be easy to use.",
        "keywords": [
            "binance",
            "cryptocurrency",
            "websocket"
        ]
    },

**Comment by derick222** [comment]
Closing for no response.
