### ISSUE TITLE
Unable to get balances

### ISSUE THREAD

**Issue by MobinSh** [jaggedsoft/php-binance-api#179]
I'm unable to get balances

```
$api = new Binance\API(env('BINANCE_API_KEY'), env('BINANCE_API_SECRET'));

// Get all of your positions, including estimated BTC value
$balances = $api->balances();
print_r($balances);
```
**Output: ERROR**
`balanceData error: Please make sure your system time is synchronized: call $api->useServerTime() before this function ERROR: Invalid request. Please double check your API keys and permissions.` 

I'm using:
- Laravel 5.6
- PHP Version PHP 7.2.5 (cli) (built: Apr 25 2018 02:39:21) ( ZTS MSVC15 (Visual C++ 2017) x86)
  Copyright (c) 1997-2018 The PHP Group
  Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
- XAMPP
- Windows 10
- Local machine

I've tried to host the website (remote server) but the error is same.
Anybody faced this issue, please help me to resolve this issue!!!

**Comment by jaggedsoft** [comment]
Easy fix i hope
```php
$api = new Binance\API(env('BINANCE_API_KEY'), env('BINANCE_API_SECRET'));
$api->useServerTime() 
// Get all of your positions, including estimated BTC value
$balances = $api->balances();
print_r($balances);
```

**Comment by MobinSh** [comment]
@jaggedsoft sorry I forgot to mention. I've tried this solution but the error is same. 

Called this `$api->useServerTime();` before calling every function. Only `$api->balances();` function is giving the error.

**Comment by dmzoneill** [comment]
One of two things here.. 

1) you're using invalid keys
2) there is a problem with the curl on your xampp install. We have had many tickets because of it.

You can begin to diagnose the curl issue with the following command. You should be able to find curl in the xammp folder
```
curl -vvv https://api.binance.com
```

**Comment by quadricanna** [comment]
@jaggedsoft estimated BTC_Value for USDT balance is not included in the $api->balances(); . I'm thinking of getting BTCUSDT price and then multiply by my USDT Balance, but I thought you might know simple way to get the estimated BTC_Value to include USDT balance. Thanks

**Comment by MobinSh** [comment]
Just passed ticker array as parameter to balances() method
```
$ticker = $api->prices();
$balances = $api->balances($ticker);
```

Still not working. I've tried debugging the issue and traced that the account's balances array is empty.

`$account = $this->httpRequest("v3/account", "GET", [], true);`

**Output:** 
```
Array
(
    [makerCommission] => 10
    [takerCommission] => 10
    [buyerCommission] => 0
    [sellerCommission] => 0
    [canTrade] => 1
    [canWithdraw] => 1
    [canDeposit] => 1
    [updateTime] => 1531391607928
    [balances] => Array
        (
        )

)
```

After getting account detail, issue is due to below code: 

```
if (empty($array) || empty($array['balances'])) {
     // WPCS: XSS OK.
     echo "balanceData error: Please make sure your system time is synchronized: call \$api->useServerTime() before this function" . PHP_EOL;
     echo "ERROR: Invalid request. Please double check your API keys and permissions." . PHP_EOL;
     return [];
}
```

Why `$array['balances']` is empty in the response of `$account = $this->httpRequest("v3/account", "GET", [], true);` ??

**Comment by jaggedsoft** [comment]
Normally it will print the reason for the error, such as "timestamp is outside of the range for this request"

Try running this code before your code
```php
$api->useServerTime();
$ticker = $api->prices();
// Get all of your positions, including estimated BTC value
$balances = $api->balances($ticker);
print_r($balances);
```

**Comment by MyZik** [comment]
Hi everyone.
I tried to use this library and have same error.

```php
$api = new Binance\API($client['api_key'], $client['secret_key']);
$api->useServerTime();
$balances = $api->balances();
$dump = var_export($balances, true);

echo "Dump: {$dump}";
```
I've got: Dump: array(
)

How can I fix that?

**Comment by jaggedsoft** [comment]
@MyZik try this. need to pass $ticker
```php
$api->useServerTime();
$ticker = $api->prices();
$balances = $api->balances($ticker);
print_r($balances);
```

**Comment by MyZik** [comment]
@jaggedsoft thanks for your answer. If I use
```php
print_r($balances);
```
I've got: 1

When I use:
```php
var_export($balances, true);
```
I've got: array(
)

:(

**Comment by dmzoneill** [comment]
works perfectly fine here, as of 60 seconds ago.
It must be incorrect key or other technical issue not related to the API on @MyZik end.

moving to close.
please see 

```
git clone https://github.com/jaggedsoft/php-binance-api.git
cd php-binance-api/examples
cat >  test.json << EOF
{
    "api-key": "5enQYcMQk2J3syHCao9xgJOnnPoGtDMhSRRAzG2Gxo90TBzXPG1itcXikQc2VRDh",
    "api-secret": "uWJQXigS3AjftKe8c6xK2t3rkTqkmfeeNPwcycBLGXXsuU4eUvLkPY9qcOnB2UYI"
}
EOF

cat >  test.php << EOF
<?php
require '../php-binance-api.php';
\$api = new Binance\API("test.json");
print_r( \$api->Balances() );
EOF

php test.php
```

**Comment by StasToken** [comment]
It is clear in General, let me the following message I will write in Russian, to convey the whole meaning of what I want to say.
Тоесть оно не работает, и вы просто положили на это хуй, потому что вам лень что то исправлять блять, и ваш ебаный сапорт за 4 дня так и не смог ответить в чем причина блять, а после этого вы хотите что бы с вами работали.
