### ISSUE TITLE
missing endpoint: POST api/v3/order/test

### ISSUE THREAD

**Issue by dxjones** [jaggedsoft/php-binance-api#18]
This implementation is missing the "order/test" endpoint.

It would be helpful to implement this as public functions:
$api->buy_test()
$api->sell_test()
which could call a new private function order_test(), ... similar to order(), but with the different endpoint.

**Comment by will83** [comment]
And also:
$api->marketBuy_test()
$api->marketSell_test()

**Comment by dxjones** [comment]
It is not necessary to add "marketBuy_test" because you can achieve that using optional "type" parameter like this:

$type="MARKET";
$result = $api->buy_test($symbol, $quantity, $price, $type);
