### ISSUE TITLE
STOP_LOSS Orders error: "Parameter 'stopPrice' sent when not required., Error Code: -1106"

### ISSUE THREAD

**Issue by GalacticSun** [jaggedsoft/php-binance-api#180]
I'm trying to place a STOP_LOSS Order (not STOP_LOSS_LIMIT), but Binance gives me the following error:

"Parameter 'stopPrice' sent when not required., Error Code: -1106"

How can 'stopPrice' not be required on a STOP_LOSS Order?  Without stopPrice it is just a regular "sell" Order, isn't it?

Can you help me understand what I'm doing wrong or if this is a Jaggedsoft PHP API issue or a Binance issue?  I'm stumped.

I also noticed this issue from back in Jan:
https://github.com/jaggedsoft/php-binance-api/issues/24
(and this nodeJS issue:)
https://github.com/jaggedsoft/node-binance-api/issues/29

Were all the issues pertaining to STOP_LOSS Orders fixed?

**Platform:**
- linux

**php version:**
- 7.1.12

**code**
```
$flags = array('stopPrice' => 7444.77);
$qty = 0.00200000;
$order = $api->marketSell('BTCUSDT', $qty, $flags);
```

Thank you

**Comment by jaggedsoft** [comment]
Yes thank you for linking that other issue. The same change needs to be done to the PHP version

1. if stopPrice exists, set the order to STOP_LOSS_LIMIT automatically
> Other valid types are STOP_LOSS, TAKE_PROFIT, TAKE_PROFIT_LIMIT.


Part of the problem is you are trying to set a stop loss on a market sell. Market sells are always executed immediately.

You can try this code. It might work
```php
$flags = ['stopPrice' => 7444.77, 'newOrderRespType' => 'FULL'];
$amount = 0.002;
$order = $api->order('SELL', 'BTCUSDT', $amount, 0, 'STOP_LOSS_LIMIT', $flags);
```

**Comment by GalacticSun** [comment]
Ok, thanks.  Maybe I just need to use STOP_LOSS_LIMIT, after all?

What I'm tying to do is place a Stop Loss order that gets triggered at a certain Stop Price, but then just sells at Market Price, not a pre-set Limit Price.  I was thinking STOP_LOSS might be right for this, but it sounds like that's not the case.

Should I execute a STOP_LOSS_LIMIT Order without "limitPrice", then (just "stopPrice")?
("stopPrice" being the price at which the Order is triggered, and "limitPrice" being the price that is placed on the books for that Order).

**Comment by jaggedsoft** [comment]
Yes I believe you are correct:

#### STOP_LOSS is what you want, used with stopPrice

**Comment by GalacticSun** [comment]
Ok.  How do I send a STOP_LOSS order with stopPrice, though?  That is what gave me the error: "Parameter 'stopPrice' sent when not required., Error Code: -1106".  Sorry, a bit confused ;)

**Comment by jaggedsoft** [comment]
Try this

```php
$flags = ['stopPrice' => 7444.77, 'newOrderRespType' => 'FULL'];
$amount = 0.002;
$order = $api->order('SELL', 'BTCUSDT', $amount, 0, 'STOP_LOSS', $flags);
```

**Comment by GalacticSun** [comment]
I get this response:
signedRequest error: {"code":-1013,"msg":"Stop loss orders are not supported for this symbol."}

**Comment by jaggedsoft** [comment]
You can view what symbols support which stop losses by doing this:

`file_put_contents("exchangeInfo.json", json_encode($api->exchangeInfo(), JSON_PRETTY_PRINT));`
then viewing exchangeInfo.json. Currently the only supported types are STOP_LOSS_LIMIT and TAKE_PROFIT_LIMIT

**Comment by GalacticSun** [comment]
Thanks again for your help!

**Comment by alexqem** [comment]
Hello from 2019
API 3 Binance
I want to play STOP_LIMIT order with stop-loss price

for example the coin is MDA
`$order = $api->buy("MDABTC", 22, 0.00020200, "LIMIT", ["stopPrice"=>0.00020100]);`
doesn't work.
