### ISSUE TITLE
Question about openOrders

### ISSUE THREAD

**Issue by rafaello9** [jaggedsoft/php-binance-api#181]
Hello.
I have a question about calling
`$openorders = $api->openOrders("BNBBTC");`
https://github.com/jaggedsoft/php-binance-api#get-open-orders
This request will return all orders in the status of "NEW".
My question is the following. Will this request return orders in the status of "PARTIALLY_FILLED"?
Thank you!

**Comment by jaggedsoft** [comment]
Yes it should return any order that is still open

**Comment by rafaello9** [comment]
Well, suppose that the exchange returned the answer to me, where there is an order in the status of "PARTIALLY_FILLED". How can I find out which part of the order is executed, and which part is not executed (in coins)?
I could not find the answer on the description page
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md
That is, there is like this:
```
[
  {
    "symbol": "LTCBTC",
    "orderId": 1,
    "clientOrderId": "myOrder1",
    "price": "0.1",
    "origQty": "1.0",
    "executedQty": "0.0",
    "cummulativeQuoteQty": "0.0",
    "status": "NEW",
    "timeInForce": "GTC",
    "type": "LIMIT",
    "side": "BUY",
    "stopPrice": "0.0",
    "icebergQty": "0.0",
    "time": 1499827319559,
    "updateTime": 1499827319559,
    "isWorking": true
  }
]
```
and what will be the answer for "PARTIALLY_FILLED"?
