### ISSUE TITLE
Questions about library

### ISSUE THREAD

**Issue by MyZik** [jaggedsoft/php-binance-api#182]
Hi everyone. I want to se this library in my Telegram bot.

But I have the some questions.
1. How can I catch and display errors? For example: my secret key or API key is wrong, and I need to get error.
2. Is that a right example, to show my BTC Balance of account?
```php
$api = new Binance\API($client['api_key'], $client['secret_key']);
$ticker = $api->prices(); // Make sure you have an updated ticker object for this to work
$balances = $api->balances($ticker);
echo "\Estimated Value: {$api->btc_value} BTC";
```
I tried to use
```php
$api = new Binance\API($client['api_key'], $client['secret_key']);
$ticker = $api->prices(); // Make sure you have an updated ticker object for this to work
$balances = $api->balances($ticker);
echo "BTC owned: ".$balances['BTC']['available'];
```

But it doesn't work for me.

Thanks in advance.

**Comment by dmzoneill** [comment]
can you please provide an error, its not clear what you are asking.
$balances will be an empty array on failure.

you can use output buffering if you really need to to capture output error messages.

https://phpfashion.com/everything-about-output-buffering-in-php

**Comment by slirx** [comment]
Isn't it better to use exceptions instead of echoing an error?

**Comment by dmzoneill** [comment]
All pull requests are welcome
