### ISSUE TITLE
Missing trades  $api->history("LTCUSDT");

### ISSUE THREAD

**Issue by vreesie18** [jaggedsoft/php-binance-api#188]
I am using the call below to get all trade data from an account....but I am missing a part of the history, not getting it all. Is this sone kind of limitation somewhere ?

$history = $api->history("LTCUSDT");

Thanks for helping.

Regards,
Andre

**Comment by jaggedsoft** [comment]
You can call it like this to get twice as much
`$history = $api->history("LTCUSDT", 1000);`

But anything beyond that you have to provide startTime,endTime or fromId

https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

Name | Type | Mandatory | Description
-- | -- | -- | --
symbol | STRING | YES |  
startTime | LONG | NO |  
endTime | LONG | NO |  
fromId | LONG | NO | TradeId to fetch from. Default gets most recent trades.
limit | INT | NO | Default 500; max 1000.
recvWindow | LONG | NO |  
timestamp | LONG | YES

**Comment by vreesie18** [comment]
Cool, I didn't know that there were extra parameters. I always use the wiki for my documentation. 

Think this will be a feature request but is it or could it be made possible to have a parameter OrderId.

For instance, I like to have only and all the trades belonging to orderid 9999999.

**Comment by jaggedsoft** [comment]
`$history = $api->history("LTCUSDT", 1000, 9999999);`

The third parameter is fromId, so it will only show numbers equal or higher than that number

**Comment by vreesie18** [comment]
But is this parameter about the TradeId or the OrderId. I am looking for the OrderId ?!
