### ISSUE TITLE
Question about PRICE_FILTER for sell

### ISSUE THREAD

**Issue by andibastian** [jaggedsoft/php-binance-api#189]
Hallo, i already read about this [post](https://github.com/jaggedsoft/php-binance-api/issues/183).
but i'm still confuse, based on official docs, PRICE_FILTER for sell will pass by 3 rules : 

> 
    minPrice defines the minimum price/stopPrice allowed.
    maxPrice defines the maximum price/stopPrice allowed.
    tickSize defines the intervals that a price/stopPrice can be increased/decreased by.

here is my code for sell : 

> $symbol_order="RDNBNB";
$minQty=$display->$symbol_order->minQty;
$minNotional=$display->$symbol_order->minNotional;
$maxQty=$display->$symbol_order->maxQty;
$stepSize=$display->$symbol_order->stepSize;
$minPrice=$display->$symbol_order->minPrice;
$maxPrice=$display->$symbol_order->maxPrice;
$price_buy=0.05938000;
$quantity=117.30000000;
$get_price_sell=$price_buy / 100 * 1.5;
$newsellprice=$price_buy + $get_price_sell=$;
$newsellprice = number_format($newsellprice, 8, '.', '');
$order = $api->sellTest($symbol_order,$jumlah_order, $hargajualbaru);
print_r($order);

its result :

> signedRequest error: {"code":-1013,"msg":"Filter failure: PRICE_FILTER"}
Array
(
    [code] => -1013
    [msg] => Filter failure: PRICE_FILTER
)

can you please give me short example for PRICE FILTER implementation in that case ?

**Comment by jaggedsoft** [comment]
I am sorry that this is not as easy as it should be for the PHP version. If my time wasn't so limited recently this would all be fixed by now


What symbol are you trying to buy/sell?

**Comment by andibastian** [comment]
I'm sorry, my mistake, here is the edit :

> $quantity=117.30000000;
$symbol_order="RDNBNB";
$minQty=$display->$symbol_order->minQty;
$minNotional=$display->$symbol_order->minNotional;
$maxQty=$display->$symbol_order->maxQty;
$stepSize=$display->$symbol_order->stepSize;
$minPrice=$display->$symbol_order->minPrice;
$maxPrice=$display->$symbol_order->maxPrice;
$price_buy=0.05938000;
$quantity=117.30000000;
$get_price_sell=$price_buy / 100 * 1.5;
$newsellprice=$price_buy + $get_price_sell;
$newsellprice = number_format($newsellprice, 8, '.', '');
$order = $api->sellTest($symbol_order,$quantity, $newsellprice);
print_r($order);

**Comment by andibastian** [comment]
i tested with your example, but its return same error. 
i understand about how to buy, but i'm still confuse about price for sell

**Comment by jaggedsoft** [comment]
I just added the roundStep function finally. It will be in the next release, for now you can add this function to your code

```php
function roundStep($value, $stepSize = 0.1) {
        $precision = strlen(substr(strrchr(rtrim($value,'0'), '.'), 1));
        return round((($value / $stepSize) | 0) * $stepSize, $precision);
    }
```
---

Ok you are doing everything right but the problem orders on the BNB pair
RDNBNB has a few extra restrictions that most pairs don't https://api.binance.com/api/v1/exchangeInfo

Specifically, the tickSize is .00001 and the stepSize is .1
tickSize defines the intervals that the price can be increased/decreased by.
stepSize defines the intervals that the quantity can be increased/decreased by.

```php
$quantity = roundStep($quantity, $stepSize);
$order = $api->sellTest($symbol_order, $quantity, $newsellprice);
```

**Comment by andibastian** [comment]
thankyou @jaggedsoft , here is my update :

> function roundStep($value, $stepSize = 0.1) {
    $precision = strlen(substr(strrchr(rtrim($value,'0'), '.'), 1));
    return round((($value / $stepSize) | 0) * $stepSize, $precision);
}
$symbol_order="RDNBNB";
$minQty=$display->$symbol_order->minQty;
$minNotional=$display->$symbol_order->minNotional;
$maxQty=$display->$symbol_order->maxQty;
$stepSize=$display->$symbol_order->stepSize;
$minPrice=$display->$symbol_order->minPrice;
$maxPrice=$display->$symbol_order->maxPrice;
$price_buy=0.05938000;
$quantity=117.30000000;
$quantity=roundStep($quantity,$stepSize);
$get_price_sell=$price_buy / 100 * 1.5;
$newsellprice=$price_buy + $get_price_sell;
$newsellprice = number_format($newsellprice, 8, '.', '');
$order = $api->sellTest($symbol_order,$quantity, $newsellprice);
print_r($order);

and the result is :
> signedRequest error: {"code":-1013,"msg":"Filter failure: PRICE_FILTER"}
Array
(
    [code] => -1013
    [msg] => Filter failure: PRICE_FILTER
)

is there any wrong of mycode ?

**Comment by andibastian** [comment]
i think, the problem is price, not quantity

**Comment by jaggedsoft** [comment]
@andibastian Yes you are correct, this is all coming down to tickSize being .00001
I think this is only a problem on the BNB pair when doing limit orders (market orders should work fine)
`$newsellprice = number_format($newsellprice, 5, '.', '');`
Try that instead. We are setting the decimal precision to 5 places which should work

I'm trying to make a roundTicks function but can't seem to get it working

**Comment by andibastian** [comment]
thankyou @jaggedsoft, its working now with number_format($newsellprice, 5, '.', '')
so, specially for BNB pair, will always use this : number_format($newsellprice, 5, '.', '') ?

**Comment by jaggedsoft** [comment]
Yeah I think the only time you are going to run into this is on the BNB pair. this could change in the future but for now I think this is the only case. I will make it much easier as soon as I have the time. cheers!

**Comment by andibastian** [comment]
thankyou so much, i really apreciate your work.

**Comment by jaggedsoft** [comment]
I have added this function to the library. If you pass the price and $tickSize (from exchangeInfo) it will round it properly for any symbol. Cheers

> roundTicks: Used to round price with tickSize. Example: `roundTicks(0.12345, '0.001') = 0.123`
```php
function roundTicks($price, $tickSize) {
        $precision = strlen(rtrim(substr($tickSize,strpos($tickSize, '.', 1) + 1), '0'));
        return number_format($price, $precision, '.', '');
}
echo roundTicks(0.00016552, '0.00000010');
```
