### ISSUE TITLE
POST operations fail because parameters passed in URL but not in content

### ISSUE THREAD

**Issue by dxjones** [jaggedsoft/php-binance-api#19]
Most Binance API endpoints use the GET method.  These work correctly, with parameters passed as a query appended to the URL.

However, these Binance API endpoints require the POST method:
/api/v3/order
/api/v3/order/test

The current implementation of $api->signedRequest fails to pass the parameters as POST data and therefore Binance.com rejects the API request.

$opt = [ "http" => [
    "method" => $method,
    ...
    "content" => $query    // <-- this line needs to be added
] ];

The following example illustrates how query parameters should be passed as http "content" in the stream_context passed to file_get_contents().

https://stackoverflow.com/questions/2445276/how-to-post-data-in-php-using-file-get-contents

**Comment by jaggedsoft** [comment]
Thank you for the reports! I am extremely behind on some projects at the moment, but I intend to fix this as soon as I can.

**Comment by dxjones** [comment]
I have forked this, and I have fixed this issue.  After some more testing, I will do a pull request so you can incorporate my fixes into your own version.

**Comment by jaggedsoft** [comment]
Thank you!!!

**Comment by jaggedsoft** [comment]
Awesome work friend. You are very talented and thank you again
