### ISSUE TITLE
Websocket and too many request info

### ISSUE THREAD

**Issue by andibastian** [jaggedsoft/php-binance-api#195]
I'm using websocket like this :

> $file_pair="pair.json";
  $list_symbol=file_get_contents($file_pair);
  $list_symbol=json_decode($list_symbol);
  foreach ($list_symbol as $key => $value) {
    $getsymbol[]=$value->pair;
  }
$api->depthCache($getsymbol, function($api, $symbol, $depth) {
$file="$symbol.json";
echo "Generate $symbol ...\n";
$limit = 100;
$sorted = $api->sortDepth($symbol, $limit);
$bids=$sorted['bids'];
$bids=array_flip($bids);
    $n=0;
    foreach ($bids as $value) {
      $n++;
        $price['bids'][]=$value;
    }
    $ask=$sorted['asks'];
    $n=0;
    $ask=array_flip($ask);
    foreach ($ask as $value) {
      $n++;
      $price['asks'][]=$value;
    }
    $output=json_encode($price);
    file_put_contents($file,$output);
}

but, this error keep appear after a few second loop :

> signedRequest error: {"code":-1003,"msg":"Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API."}

how to avoid that warning when using websocket ?

**Comment by jaggedsoft** [comment]
The problem is that depthCache needs to make a request when it first opens in order to download the current state of the order book. So you should delay a small amount, like .3 seconds before opening the next one

**Comment by andibastian** [comment]
owh .. i see . thankyou
