### ISSUE TITLE
Possibility to automatically reconnect after connection is closed

### ISSUE THREAD

**Issue by tkoen93** [jaggedsoft/php-binance-api#196]
First of all, thank you for this great work. Makes trading on binance a lot easier for me.

Since a few days I'm running into an issue with the websocket. Every now and then the websocket stops working and returning the following:
> ticker: WebSocket Connection closed! (1006 - Underlying connection closed)

When that happens I'm not receiving any data from the websocket anymore. After giving the command in the terminal (macosx) the script will start and connecting to the websocket. Is there any possibilty to automatically reconnect after the connection is being closed?

**Comment by jaggedsoft** [comment]
Hm, this library is supposed to automatically reconnect for you, but I think it might have a bug in that if it gets disconnected more than once it will stop trying

**Comment by tkoen93** [comment]
Thank you for replying this quickly!

Found this part that (probably) gives me the message in the terminal:

Line 1858-1861
`$ws->on('close', function ($code = null, $reason = null) {
                // WPCS: XSS OK.
                echo "ticker: WebSocket Connection closed! ({$code} - {$reason})" . PHP_EOL;
            });`

Can't find anything myself that looks like a reconnect, but that's maybe due to my own current skill.

**Comment by byjameson** [comment]
I have same problem too. i took this error ticker: WebSocket Connection closed! (1006 - Underlying connection closed). Is there anyone solve this problem?
