### ISSUE TITLE
PHP cancel function does not work

### ISSUE THREAD

**Issue by photobangkok** [jaggedsoft/php-binance-api#198]
**Title**
 PHP cancel api: I cannot make it work.
**Short Description:**
- PHP cancel does not pass parameters side,type,quantity....to api
  **Platform:**
- windows
**php version:**
- 5.4.45

**Long descrption**
**code**
```php
include "./radix.btm" ;
require_once('vendor/autoload.php'); 
require 'BinanceClass1.php';
$api = new Binance("$k","$s");
$answer = $api->cancel("BTCUSDT", "177688888");

The curl part in BinanceClass1  

    private function request($url, $params = [])
    {
        $headers[] = "User-Agent: Mozilla/4.0 (compatible; PHP Binance API)\r\n";
        $query = http_build_query($params, '', '&');
        return json_decode($this->http_request($this->base . $url . '?' . $query, $headers), true);
    }

    public function http_request($url, $headers, $data = array())
{
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
	If (strpos($url, 'v3/order') == true){
		curl_setopt($ch, CURLOPT_POST, 0);
		curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
		}
    if ($data) {
		curl_setopt($ch, CURLOPT_POST, 1);    
        curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    }
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
    curl_setopt($ch, CURLOPT_TIMEOUT, 5);
    curl_setopt($ch, CURLOPT_ENCODING, "");
    $content = curl_exec($ch);
    if (curl_errno($ch)) {
        $content = false;
    }
    curl_close($ch);
    return $content;
```
**result**
```
{
   Mandatory parameter \side\ was not sent,was empty/null,or malformed.
}
```

thank you

**Comment by dmzoneill** [comment]
Hi thanks for the feedback.

The latest version does not work on php 5.

Could you please try the latest version with php 7 and let us know if you are still having difficulty

Thanks

**Comment by jaggedsoft** [comment]
Thank you for the report
![image](https://user-images.githubusercontent.com/4283360/47211213-9d77cb00-d39d-11e8-8492-24c13f8aa287.png)

```php
    public function cancel(string $symbol, $orderid, $flags = [])
    {
        $params = [
            "symbol" => $symbol,
            "orderId" => $orderid,
        ];
        return $this->httpRequest("v3/order", "DELETE", array_merge($params, $flags), true);
    }
```

This is live in `v0.5.1` https://github.com/jaggedsoft/php-binance-api/commit/0a225ba290671d12a0618f0c5a54588a9cd72df1

Example:
`$answer = $api->cancel("BTCUSDT", "177688888", ["side"=>"sell"]);`

**Comment by photobangkok** [comment]
Tried to switch to php 7 on website but I have too many problems mostly with Thai language.

Is it possible to just do a fix to the function cancel in old BinanceClass using php5 ?
All the rest works fine.

**Comment by photobangkok** [comment]
There is no httpRequest() function in the binanceClass I have.  Mostly signedRequest()
https://github.com/baitercel/binance-api-php/blob/master/BinanceClass.php

**Comment by jaggedsoft** [comment]
BinanceClass.php is an old version of this library from over a year ago. I created it, but it is not maintained by me. Only the current version with httpRequest is supported

**Comment by photobangkok** [comment]
Already commented that using on latest classes there is no need to pass $side and array_merge.
also
This give you the false hope to get an History of all coin. Symbol is mandatory - I think-
 * history Get the complete account trade history for all or a specific currency
 *
 * $allHistory = $api->history();
