### ISSUE TITLE
Get the executed order volume in the status PARTIALLY_FILLED

### ISSUE THREAD

**Issue by rafaello9** [jaggedsoft/php-binance-api#201]
Hello!
I want to ask a question about the Partially Fulfilled Order, because I could not find the answer in the documentation myself.
If the Order is partially executed, then it has a “completed volume” and another “not completed volume”.
If I make such a request
$ my_order = $ api->orderStatus('XLMBTC', '1526001');
then in which variable you can get the "completed volume"?
$ my_order ['????????'] = "completed volume";

Or just write what answer the exchange gives in the event that the order status is PARTIALLY_FILLED
Thank!

**Comment by jaggedsoft** [comment]
This is an order status response
```js
{
  "symbol": "LTCBTC",
  "orderId": 1,
  "clientOrderId": "myOrder1",
  "price": "0.1",
  "origQty": "1.0",
  "executedQty": "0.0",
  "cummulativeQuoteQty": "0.0",
  "status": "NEW",
  "timeInForce": "GTC",
  "type": "LIMIT",
  "side": "BUY",
  "stopPrice": "0.0",
  "icebergQty": "0.0",
  "time": 1499827319559,
  "updateTime": 1499827319559,
  "isWorking": true
}
```

So you should be able to take `executedQty` and `origQty` to determine the fill rate
