### ISSUE TITLE
Difference between MIN_QTY and MIN_NOTIONAL

### ISSUE THREAD

**Issue by pedrocarvajal** [jaggedsoft/php-binance-api#205]
Difference between MIN_QTY and MIN_NOTIONAL

I have a question about the minimum opening of my operation.
for example the minimum in quantity is 2 but the "notional" says 3, then it will not let me open operations of error with the MIN_NOTIONAL

What is the difference between the two? the amount does not represent the minimum amount to invest? which represents the "notional"

**Comment by jaggedsoft** [comment]
minQty is the minimum amount you can order (quantity)
minNotional is the minimum value of your order. (price * quantity)

```js
// Check minimum order size
if ( price * quantity < minNotional ) {
    quantity = minNotional / price;
}
```
