### ISSUE TITLE
Last price

### ISSUE THREAD

**Issue by JuniorAugusto** [jaggedsoft/php-binance-api#206]
Good afternoon, is there any way to get the latest price via websockets

**Comment by jaggedsoft** [comment]
Hi friend, there are several ways to do this but the easiest is probably the miniTicker:
```php
$api->miniTicker(function($api, $ticker) {
	print_r($ticker);
});
```
This will return an array of all symbols once per second, and you can use their 'close' value as the last price

**Comment by JuniorAugusto** [comment]
sorry for the more am question in php.
I have the result using this code:
<?php
require 'php-binance-api.php';
require 'vendor/autoload.php';

$api = new Binance\API("bullsignals_api.json");

$api->miniTicker(function($api, $ticker) {
	print_r($ticker);
});
_____________________________________________________________________
More I can not get the update every second, would you have some example to provide me with?

**Comment by jaggedsoft** [comment]
I am currently in talks with Binance to improve the documentation and make the whole api easier to use. 
```php
$ticker = $api->prices();
echo "price of BTC: {$ticker['BTCUSDT']}\n";
// Now keep $ticker object updated:
$api->miniTicker(function($api, $miniTicker) {
    global $ticker;
    foreach ( $miniTicker as $obj ) {
        $ticker[$obj['symbol']] = $obj['close'];
    }
    echo "price of BTC: {$ticker['BTCUSDT']}\n";
});
// Now you can use $ticker[$symbol] anywhere in your program.
```

**Comment by JuniorAugusto** [comment]
thanks

**Comment by kaduiceman** [comment]
Good morning, the code worked perfectly, but I need to know how it will automatically update the values ​​of the respective currency. Is updating via refresh, div, iframe, how do you have the current value?
