### ISSUE TITLE
Automatically update

### ISSUE THREAD

**Issue by JuniorAugusto** [jaggedsoft/php-binance-api#208]
Good morning, this code worked perfectly, but I need to know how to automatically update it. Would it be via refresh, div, iframe, how do I get the current value?

`$ticker = $api->prices();`
`echo "price of BTC: {$ticker['BTCUSDT']}\n";`
`**// Now keep $ticker object updated:**`
`$api->miniTicker(function($api, $miniTicker) {`
`global $ticker;`
`foreach ( $miniTicker as $obj ) {`
`$ticker[$obj['symbol']] = $obj['close'];`
` }`    
` echo "price of BTC: {$ticker['BTCUSDT']}\n";
});`   
`// Now you can use $ticker[$symbol] anywhere in your program.`

**Comment by jaggedsoft** [comment]
I am very sorry but I can no longer provide updates or support to this project unless Binance agrees to continue sponsoring development.
