### ISSUE TITLE
Websocket trades method

### ISSUE THREAD

**Issue by Marc008** [jaggedsoft/php-binance-api#209]
This is more a question than an issue. I'm checking the trades method, and it looks like it's not the "[Trade Streams](https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#trade-streams)" but the "[Aggregate Trade Streams](https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#aggregate-trade-streams)", I'm trying to look for the difference between both of them, but I don't find any documentation.  Could you explain?

Anyway, I'm using the current trades method, and I'm getting duplicate results as you can see here:

> Symbol: BNBBTC:
> Array
> (
>     [price] => 0.00128760
>     [quantity] => 0.10000000
>     [timestamp] => 1543394580225
>     [maker] => false
>     [json] => Array
>         (
>             [e] => aggTrade
>             [E] => 1543394580227
>             [s] => BNBBTC
>             [a] => 27562537
>             [p] => 0.00128760
>             [q] => 0.10000000
>             [f] => 31626179
>             [l] => 31626179
>             [T] => 1543394580225
>             [m] => 
>             [M] => 1
>         )
> 
> )
> Symbol: BNBBTC:
> Array
> (
>     [price] => 0.00128760
>     [quantity] => 0.10000000
>     [timestamp] => 1543394580225
>     [maker] => false
>     [json] => Array
>         (
>             [e] => aggTrade
>             [E] => 1543394580227
>             [s] => BNBBTC
>             [a] => 27562537
>             [p] => 0.00128760
>             [q] => 0.10000000
>             [f] => 31626179
>             [l] => 31626179
>             [T] => 1543394580225
>             [m] => 
>             [M] => 1
>         )
> 
> )
> 

I have included the entire json in the trades output so I could debug better. As you can see there, both results are identical and checking other results, it looks like all results are duplicated. Is this normal?

Thanks in advance!

**Comment by jaggedsoft** [comment]
I believe the aggregate trade stream returns the combined sum for all orders in a period. The regular trade stream will return each individual order. This is my understanding:
If you buy 1000 BNB, the aggregate trade stream would have one result for 1000 BNB. However, the regular trade stream would trigger potentially hundreds of different individual orders that were filled.

**Comment by Marc008** [comment]
I just got this answer from their support:

"The Aggregate Trade Streams push trade information that is aggregated for a single taker order."

What about the duplications. Is this something that comes from Binance stream?
