### ISSUE TITLE
Asset Detail (USER_DATA) is missing on the API

### ISSUE THREAD

**Issue by got3nks** [jaggedsoft/php-binance-api#210]
https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md

```
Asset Detail (USER_DATA)

GET  /wapi/v3/assetDetail.html (HMAC SHA256)

Fetch asset detail.
```

**Comment by jaggedsoft** [comment]
Thank you very much for the report. My focus is currently on other things, but pull requests are very welcome.

**Comment by afsharsafavi** [comment]
I added this method. I sent pull request.

**Comment by ePascalC** [comment]
@jaggedsoft it looks like this one was merged, so I suppose the issue could be closed?
