### ISSUE TITLE
Buy and/or Sell order no quantity but all there is

### ISSUE THREAD

**Issue by vreesie18** [jaggedsoft/php-binance-api#211]
In my tiny bot I encounter often the problem that when I use the buy or sell API the amount I put into the quantity parameter field an amount that is often too high, so rejected by Binance.

My actions are always like buy LTC with everything I have on USDT or sell everything I have on LTC to USDT but have to put in a exact quantity parameter always that makes it hard.

So my question is, isn't there an API call that can sell or buy all there is in the wallet for a certain market (like LTCUSDT) ???

I hope I made myself clear on this one.

Thank you in advance

Andre

**Comment by jaggedsoft** [comment]
I agree with you. I sent a proposal to Binance to fix this but they turned it down. So I will not support this project anymore unless people send pull requests. Sorry

**Comment by vreesie18** [comment]
Too bad. Thanks for your response!
