### ISSUE TITLE
buy and sells return null

### ISSUE THREAD

**Issue by wesly1988** [jaggedsoft/php-binance-api#212]
**Title**
- buy and sells (problem)

**Description:**
Hi guys, 

First of all, Merry Christmas.

Strange problem here. 
I have installed the bot by composer on my AWS server. 
Everything works, even getting my current balance, but when I try to make a buy or sell I get a return NULL.

Have set the useServerTime() to make sure I use the right server time, but this doesn't seem to work. 
Also, have installed curl (normal + https) and make sure that it works. 

What could be the problem of this? Have search around, but couldn't find anything yet. 
  
**Platform:**
AWS

**php version:**
- 7.2.11

**curl version:**
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.36 zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets 

**code**
```
require '/var/www/html/new_trading/crontab/api/binance/vendor/autoload.php';

$api = new Binance\API(
    "public key",
    "secret"
);

# set server time
$api->useServerTime();

$quantity = 10;
$order = $api->marketBuy("PAXUSDT", $quantity);
var_dump($order) . "\n";
```

**result**
```
Always null
```

Help is highly appreciated.

Thank you

Wesley Schravendijk

**Comment by jaggedsoft** [comment]
Sorry friend, if you want support from Binance you must go through https://t.me/binance_api_english

I have made several proposals for improving the API and providing better support but they have shot them down.

**Comment by wesly1988** [comment]
Thank you for your reaction, have searched more and more and tried some new things. 
Seems that the code works perfectly on xampp and windows. 

The problems seem to be with my ec2 server. 
Have not found the solution yet, but still looking.

**Comment by wesly1988** [comment]
To give an update to people that have the same problem.
The problem was Centos 7, this script doesn't seem to work on this operating system. 

On other ubuntu, windows and linux it works.

**Comment by jaggedsoft** [comment]
That is very strange, I wonder why that could be. Best of luck to you friend, and merry christmas 🎄

**Comment by wesly1988** [comment]
Indeed, have tried it with all the same settings and versions, everywhere it works, but not on the Centos operating system. To be honest, I think it has to do something with the certificates. At least its working now. Merry Christmas, have a good one.
