### ISSUE TITLE
Cancel order not working

### ISSUE THREAD

**Issue by whitesiroi** [jaggedsoft/php-binance-api#213]
**Title**
- bug: $api->cancel($symbol, $orderId); stops working
  
**Platform:**
- macos High Sierra 10.13.6

**php version:**
- 7.1.9

**code**
```php
require 'vendor/autoload.php';
$api = new Binance\API("<api key>","<secret>");

$response = $api->cancel("MFTETH", 8654008);
var_dump($response); die();

array(2) {
  'code' =>
  int(-2011)
  'msg' =>
  string(13) "UNKNOWN_ORDER"
}
```

but if I execute  orderStatus() it shows that order does exist and I can still see it here  https://www.binance.com/userCenter/openOrders.html?lang=en

```php
$response = $api->orderStatus("MFTETH", 8654008);
var_dump($response); die();

array(16) {
  'symbol' =>
  string(6) "MFTETH"
  'orderId' =>
  int(8654008)
  'clientOrderId' =>
  string(22) "XXXXX"
  'price' =>
  string(10) "0.00001159"
  'origQty' =>
  string(14) "25843.00000000"
  'executedQty' =>
  string(10) "0.00000000"
  'cummulativeQuoteQty' =>
  string(10) "0.00000000"
  'status' =>
  string(8) "CANCELED"
  'timeInForce' =>
  string(3) "GTC"
  'type' =>
  string(5) "LIMIT"
  'side' =>
  string(3) "BUY"
  'stopPrice' =>
  string(10) "0.00000000"
  'icebergQty' =>
  string(10) "0.00000000"
  'time' =>
  int(1545897979461)
  'updateTime' =>
  int(1545898002342)
  'isWorking' =>
  bool(true)
}
```

thank you

**Comment by afsharsafavi** [comment]
I think this bug has a relation with #99  (cancel method uses POST method for httpRequest)
I solved it and now you can test the new code:
#216 
I tested it and orders have been cancelled without any problem.

**Comment by whitesiroi** [comment]
@afsharsafavi thank you, I found a bug but not sure how to commit/push to official repo.
https://github.com/jaggedsoft/php-binance-api/blob/master/php-binance-api.php
line 908    instead of $curlch should be $curl

thank you

**Comment by whitesiroi** [comment]
thank you very much
