### ISSUE TITLE
SiqnedRequest Error ?

### ISSUE THREAD

**Issue by oguzhankrcby** [jaggedsoft/php-binance-api#214]
Hi to all,

When i tried to withdraw some btc with api i got this error and i couldnt find any documentation about this error, can anyone help about it ?

Error :
signedRequest error: {"msg":"Success","success":true,"id":"c52c13c40a9e4c349b5d42685e2ee5c7"}

**Comment by jaggedsoft** [comment]
Doesn't look like an error, but it could be throwing an error message when it shouldn't

**Comment by oguzhankrcby** [comment]
> Doesn't look like an error, but it could be throwing an error message when it shouldn't

But withdraw doesnt get successfull, it doesnt work...

**Comment by jaggedsoft** [comment]
I would suggest checking your withdraw history page on binance or asking in their support: https://t.me/binance_api_english

Good luck!

**Comment by canyalos** [comment]
We check the withdrawal history.  there is nothing have. First we write binance support, they forward us to here.. I dont understand Who will help us and how can we fix the issue. thanks.
