### ISSUE TITLE
Get miniTicker for all symbols not working

### ISSUE THREAD

**Issue by robert-damon** [jaggedsoft/php-binance-api#215]
$api->miniTicker(function($api, $ticker) {
	print_r($ticker);
});

No return？

My code：
$api = new Binance\API(“”，“”）；
$api->miniTicker(function($api, $ticker) {
	print_r($ticker);
});

**Comment by jaggedsoft** [comment]
I am unable to provide further support, sorry. You must go through https://t.me/binance_api_english if someone from the community is unable to help you

**Comment by Stuperfied** [comment]
I just spent 3 days writing my code around this API only to find one of the most important parts is non functional and there is no support. This should either be fixed or a warning should be placed at the top of the readme file.

**Comment by ePascalC** [comment]
@robert-damon Can this be closed?
