### ISSUE TITLE
Allow to subscribe to multiple websocket endpoints with the same event loop

### ISSUE THREAD

**Issue by webqap** [jaggedsoft/php-binance-api#22]
Hi.

Currently when subscribing to a websocket endpoint, the loop runs straight away.

It would be nice if we could subscribe to multiple endpoints within the same event loop before running it. E.g. both depthcache and trades. Or depthcaches for multiple symbols etc.

**Comment by jaggedsoft** [comment]
Thank you for your report!
Are you saying that if you try and subscribe to two things at once, it only subscribes to one?

**Comment by webqap** [comment]
Because the event loop of the first subscription starts running straight away. The second event loop of the second subscription never runs. Ideally, you would want to run both subscriptions within the same event loop.

**Comment by jaggedsoft** [comment]
Thank you again for the report. Unfortunately my time is very limited at the moment but I will make sure this gets completed

**Comment by webqap** [comment]
No worries. There is no rush. I can write my own implementation to work around it. But thought you might want to know :)

Thank you for your work!
