### ISSUE TITLE
How to catch signedRequest error if symbol is invalid

### ISSUE THREAD

**Issue by dade80vr** [jaggedsoft/php-binance-api#221]
**Title**
- signedRequest error if symbol is invalid

**Short Description:**
- server got this error: signedRequest error: {"code":-1121,"msg":"Invalid symbol."}
  
**Platform:**
- macos

**php version:**
- 7.2.2

**Long descrption**
- How to catch error instead of output it?

**code**
```php
require 'vendor/autoload.php';
$api = new Binance\API("<api key>","<secret>");
$key = "EOP";
$price = $api->price($key."BTC");
```

**result**
```
signedRequest error: {"code":-1121,"msg":"Invalid symbol."}
```

thank you

**Comment by jaggedsoft** [comment]
The easiest solution is to not send invalid symbols.
I personally only operate on symbols that are listed on exchangeInfo https://api.binance.com/api/v1/exchangeInfo
and have volume

**Comment by ambainteligence** [comment]
Have this error on BNTBTC which is a valid symbol and available from exchange info.  Not only but many other symbols. 

PHP 7.2
Ubuntu 14

**Comment by dade80vr** [comment]
> The easiest solution is to not send invalid symbols.
> I personally only operate on symbols that are listed on exchangeInfo https://api.binance.com/api/v1/exchangeInfo
> and have volume

nice tip, thank you
