### ISSUE TITLE
api sell

### ISSUE THREAD

**Issue by tommmmy991** [jaggedsoft/php-binance-api#225]
**Title**
- bug: api sell , return amount off seling 
- feature: sell api
- enhancement: add this to existing features

**Short Description:**
I make some api to sell crypto , when i used it it's seem ok 
but i want to have the price of crypto when i seling it into Market 
i have this , on my return when i use    print_r
the probleme you see , i could not have the price , because it's in another array 

How can i reach another array 

[symbol] => NXSBTC
    [orderId] => 13528111
    [clientOrderId] => wkLLu9QVufUMkLXWGHYM5S
    [transactTime] => 1551961799469
    [price] => 0.00000000
    [origQty] => 40.00000000
    [executedQty] => 40.00000000
    [cummulativeQuoteQty] => 0.00334800
    [status] => FILLED
    [timeInForce] => GTC
    [type] => MARKET
    [side] => SELL
    [fills] => Array
        (
            [0] => Array
                (
                    [price] => 0.00008370
                    [qty] => 40.00000000
                    [commission] => 0.00064464
                    [commissionAsset] => BNB
                    [tradeId] => 1558630
                )

        )

)

**Platform:**
- linux

**php version:**
- 7.0.24

**Long descrption**
- Doing xyz results in ypr and failing when fph

**code**
```php
require 'vendor/autoload.php';
$api = new Binance\API("<api key>","<secret>");
$ticker = $api->prices();
print_r($ticker); // List prices of all symbols
echo "Price of BNB: {$ticker['BNBBTC']} BTC";
```

**result**
```
{
   "result":"result"
}
```

thank you

**Comment by jaggedsoft** [comment]
When you market buy with the parameter newOrderRespType set to "FULL" (i think this is automatic now, but it wasn't in the past) it returns the array with fills

you can loop through the array with a simple foreach loop to see the price/amount filled from each chunk of your order

**Comment by tommmmy991** [comment]
i have this 
symbol] => NXSBTC
[orderId] => 13528111
[clientOrderId] => wkLLu9QVufUMkLXWGHYM5S
[transactTime] => 1551961799469
[price] => 0.00000000
[origQty] => 40.00000000
[executedQty] => 40.00000000
[cummulativeQuoteQty] => 0.00334800
[status] => FILLED
[timeInForce] => GTC
[type] => MARKET
[side] => SELL
[fills] => Array
(
[0] => Array
(
[price] => 0.00008370
[qty] => 40.00000000
[commission] => 0.00064464
[commissionAsset] => BNB
[tradeId] => 1558630
)

    )
)

**Comment by ePascalC** [comment]
@jaggedsoft  I think this issue can be closed. I confirm that the price in the main array is 0 and that you need to look at the [fills] array.
Based on the above example, in a next sell, it could be that the first 30 are sold at 0.00008370 and the last 10 at 0.00008400. So the price needs to be taken from the [fills].
