### ISSUE TITLE
release v0.5.6: Missing argument in webSockets depth cache

### ISSUE THREAD

**Issue by ComeLC** [jaggedsoft/php-binance-api#226]
**Missing argument in webSockets depth cache**
- I'm using your wonderful API without difficulty, but I just did the v0.5.6 update, and now I have an error with the depthCache() method.
- I got the following error: "PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Binance\API::depth(), 1 passed in ..."

**php version:**
- 7.3.3

**The issue**
- php-binance-api.php line 1767: The second argument $limit is missing:
```
$this->depth($symbol);
```
**Proposition to solve it**
- Add second argument
```
$this->depth($symbol, 100);
```

**Comment by jaggedsoft** [comment]
Thank you for your report
It looks like it's correct in the code https://github.com/jaggedsoft/php-binance-api/edit/master/php-binance-api.php#L750

**Comment by jaggedsoft** [comment]
Resolved here thank you https://github.com/jaggedsoft/php-binance-api/pull/227/commits/21d8fc6a0c7007138d1c15201bfb114a346995c2

I will issue a new release at some point but if you need me to publish a new one soon I will

**Comment by ComeLC** [comment]
Don't worry there's no rush, I just downgraded to 0.5.5 in the meantime ;)
Thank you again for your work on the API.
