### ISSUE TITLE
Explain Volume candlesticks

### ISSUE THREAD

**Issue by yannick28** [jaggedsoft/php-binance-api#228]
Hello, could someone please explain with this example the meaning of the following fields:
* volume
* assetVolume
* baseVolume
* assetBuyVolume
* takerBuyVolume

The service that I am consulting is: candlesticks

Thank you

**Comment by jaggedsoft** [comment]
You will get good answers here https://t.me/binance_api_english

**Comment by ePascalC** [comment]
@jaggedsoft could be closed I suppose...
