### ISSUE TITLE
Signature for this request is not valid

### ISSUE THREAD

**Issue by mehrdadphp** [jaggedsoft/php-binance-api#230]
hi 

i am call ``withdraw`` method 

```php
try {
   $api->withdraw($asset, $address, $amount);
} catch (\Exception $e) {
     vardump($e);
}
```

return for request : 
```php 
signedRequest error: {"msg":"Signature for this request is not valid.","success":false}
```

**Can anyone help me?**

tank you

**Comment by Marc008** [comment]
Hello @mehrdadphp ,

I saw that response from Binance when my API key/secret pair was no longer valid.

Best.

**Comment by mehrdadphp** [comment]
tanks @Marc008 for answer 

It's strange to me that the rest of the methods work well, like ‍‍‍‍``deposit`` , ``withdrawaHistory`` and ...

just for ``withdraw`` problem . 
with key/secret use **nodejs** and test withdraw Worked well

**Comment by tedy5** [comment]
Same here. Everything else works except withdrawal.

**Comment by aliromero** [comment]
not work withdrawal :
{"msg":"Signature for this request is not valid.","success":false}

**Comment by Libre12** [comment]
Same here, and yes my API details are valid and correct (I just created and it's working for other functions).

There's something wrong with the withdraw function only.

Did anyone figure it out yet?

Does it have anything to do with the ca.pem file?

Any clues appreciated.

Thanks

**Comment by alfredogarc** [comment]
I have the same problem

**Comment by NicolaszHD** [comment]
i have this problem when i make
$binance->withdraw("XLM", $address, $pre, $memoid);

{"msg":"Signature for this request is not valid.","success":false}
one can help me??

**Comment by error-handling** [comment]
Funny that we put it in `try{}catch{}` (I did it too) thinking it throws an exception...
this library is just echoing errors!

**Comment by rxcod9** [comment]
Checkout this PR
https://github.com/jaggedsoft/php-binance-api/pull/248
Solved

**Comment by pfergi42** [comment]
This problem just started occurring for us. GetBalance, MarketBuy and MarketSell all work fine.

Only Withdraw is giving us:
`
signedRequest error: {"msg":"Signature for this request is not valid.","success":false}`

Anyone know why this would start happening all of a sudden?

**Comment by 2pd** [comment]
https://github.com/jaggedsoft/php-binance-api/blob/master/php-binance-api.php#L590
The default name `API Withdraw` with space caused this problem.
```php

# this should work
$response = $api->withdraw($asset, $address, $amount, null, 'my_address');
```

Reason:

In this `name` parameter, space has to be encoded into `%20`, but now i think it's encoded into `+`, which cause signature invalid.

**Comment by pfergi42** [comment]
> Reason:
> 
> In this `name` parameter, space has to be encoded into `%20`, but now i think it's encoded into `+`, which cause signature invalid.

Thank you @2pd! This solved the problem.  I'd suggest just replacing the space in the default "API Withdraw" with an underscore.

**Comment by MegaManSE** [comment]
This error appears to still happen in the latest version.  The latest version doesn't use the name parameter also.

![image](https://user-images.githubusercontent.com/2626835/88132392-5a1f4180-cbad-11ea-94f9-78a722c4ab3a.png)
