### ISSUE TITLE
specific symbol ticker

### ISSUE THREAD

**Issue by AMONRA75** [jaggedsoft/php-binance-api#233]
hi,
i need to get a specific symbol ticker
like this:

`
 [symbol] => LTCUSDT
            [close] => 182.85000000
            [open] => 192.62000000
            [high] => 195.25000000
            [low] => 173.08000000
            [volume] => 238603.66451000
            [quoteVolume] => 43782422.11276660
            [eventTime] => 1520497914289
`

please help me
tnx

**Comment by Stuperfied** [comment]
I would say to use miniTicker and simply pull the data from that array however miniTicker seems to be non functional currently. The code examples seem to refer to more functions which are not mentioned in the readme, you may find some answers there such as in prevday.php.

**Comment by AMONRA75** [comment]
when i try to get array from miniTicker i see many similar symbol value like ETHBTC [close] or others. why?
i need only info about specific symbol like:

[symbol] => LTCUSDT
            [close] => 182.85000000
            [open] => 192.62000000
            [high] => 195.25000000
            [low] => 173.08000000
            [volume] => 238603.66451000
            [quoteVolume] => 43782422.11276660
            [eventTime] => 1520497914289

**Comment by AMONRA75** [comment]
i made this code:

`
$api->miniTicker(function($api, $ticker) {
//	print_r($ticker);







foreach($ticker as $key => $value) { 
    
        $mykey = $key; 
        $myval = $value;  
        //echo $mykey. " - " .$myval['symbol']."<br>"; 


        if($myval['symbol'] == "ETHBTC"){ 
        
            echo $mykey. " - symbol: " .$myval['symbol']. " - close: "  .$myval['close']. " - open: "  .$myval['open']. " - high: "  .$myval['high']. " - low:  "  .$myval['low']. " - volume: "  .$myval['volume']. " - quotevolume: "  .$myval['quoteVolume']. " - eventtime: "  .$myval['eventTime']."<br>";
        }

    }


   

                  

});
`

but when i execute i see many row with values but i need one row with the value i choose

`
0 - symbol: ETHBTC - close: 0.03259500 - open: 0.03188300 - high: 0.03289200 - low: 0.03162500 - volume: 154471.54500000 - quotevolume: 4968.27324864 - eventtime: 1555570565627
0 - symbol: ETHBTC - close: 0.03259500 - open: 0.03187600 - high: 0.03289200 - low: 0.03162500 - volume: 154470.17800000 - quotevolume: 4968.22968951 - eventtime: 1555570567011
0 - symbol: ETHBTC - close: 0.03259500 - open: 0.03187700 - high: 0.03289200 - low: 0.03162500 - volume: 154471.50000000 - quotevolume: 4968.27342105 - eventtime: 1555570569774
0 - symbol: ETHBTC - close: 0.03259500 - open: 0.03187700 - high: 0.03289200 - low: 0.03162500 - volume: 154471.54000000 - quotevolume: 4968.27472485 - eventtime: 1555570570344
0 - symbol: ETHBTC - close: 0.03260000 - open: 0.03189000 - high: 0.03289200 - low: 0.03162500 - volume: 154471.66700000 - quotevolume: 4968.28109071 - eventtime: 1555570573105
0 - symbol: ETHBTC - close: 0.03259600 - open: 0.03189000 - high: 0.03289200 - low: 0.03162500 - volume: 154472.59100000 - quotevolume: 4968.31120994 - eventtime: 1555570574218
0 - symbol: ETHBTC - close: 0.03260000 - open: 0.03188000 - high: 0.03289200 - low: 0.03162500 - volume: 154472.50100000 - quotevolume: 4968.30836580 - eventtime: 1555570575259
0 - symbol: ETHBTC - close: 0.03261000 - open: 0.03188100 - high: 0.03289200 - low: 0.03162500 - volume: 154495.08800000 - quotevolume: 4969.04504108 - eventtime: 1555570577152
0 - symbol: ETHBTC - close: 0.03260000 - open: 0.03188100 - high: 0.03289200 - low: 0.03162500 - volume: 154495.14300000 - quotevolume: 4969.04683408 - eventtime: 1555570578736
0 - symbol: ETHBTC - close: 0.03259800 - open: 0.03188900 - high: 0.03289200 - low: 0.03162500 - volume: 154495.94400000 - quotevolume: 4969.07440289 - eventtime: 1555570580838
0 - symbol: ETHBTC - close: 0.03260700 - open: 0.03188900 - high: 0.03289200 - low: 0.03162500 - volume: 154497.64200000 - quotevolume: 4969.12976957 - eventtime: 1555570582253
0 - symbol: ETHBTC - close: 0.03260700 - open: 0.03188900 - high: 0.03289200 - low: 0.03162500 - volume: 154497.54400000 - quotevolume: 4969.12666958 - eventtime: 1555570585471
0 - symbol: ETHBTC - close: 0.03259600 - open: 0.03188900 - high: 0.03289200 - low: 0.03162500 - volume: 154497.60800000 - quotevolume: 4969.12879956 - eventtime: 1555570587421
`

**Comment by Stuperfied** [comment]
Im just figuring all this out myself. Funny we just both ran into the same problem, it seems that this is a sample of the live feed data as pairs are updating, likely also why i takes a while to execute as its recording a live sample.

I need to go out for a while but when I get back, i'll go hunting in the examples and try to find a better way. Will check back here soon.

**Comment by Stuperfied** [comment]
Found something.

`	  <?php 
	    echo "price change stats: <br />";
	    $prevDay = $api->prevDay("BNBBTC");
	    // print_r($prevDay);
		foreach ($prevDay as $key => $value) {
			echo $key, $value, '<br />';
		}
	    echo "BNB price change since yesterday: <br />".$prevDay['priceChangePercent']."%".PHP_EOL;
	  ?>`

Seems to contain the data required.

**Comment by AMONRA75** [comment]
> 
> 
> Found something.
> 
> ` <?php `
> ` echo "price change stats: <br />";`
> ` $prevDay = $api->prevDay("BNBBTC");`
> ` // print_r($prevDay);`
> ` foreach ($prevDay as $key => $value) {`
> ` echo $key, $value, '<br />';`
> ` }`
> ` echo "BNB price change since yesterday: <br />".$prevDay['priceChangePercent']."%".PHP_EOL;`
> ` ?>`
> 
> Seems to contain the data required.

work tnx!
