### ISSUE TITLE
clientOrderId

### ISSUE THREAD

**Issue by Stuperfied** [jaggedsoft/php-binance-api#234]
More of a request than an issue.
When placing an order I cant find anything in the docs about setting or getting the clientOrderId. Is it there and im just not seein git? At the moment im having to program clairvoyance into my code just to get it to store the orderid after creation.

Is there a way to set the clientOrderId which is not mentioned in the docs or can this be added? If it can't be added, is ther or can there at least be a way to capture the randomly generated one so we don't have to try and predict which one it is in the exchange after being placed.

**Comment by ePascalC** [comment]
@Stuperfied from what I read, you should add it as a parameter in your order:
You pass it as 'newClientOrderId' to the /api/v3/order endpoint, and thereafter it's returned with all the order-related responses. If you don't supply it at order creation time, binance creates a random one for you.
