### ISSUE TITLE
1021 timestamp ahead of server time.

### ISSUE THREAD

**Issue by Stuperfied** [jaggedsoft/php-binance-api#235]
**Title**
- bug: Timestamp ahead of server time
- feature: please add
- enhancement: add this to existing features

**Short Description:**
- signedRequest error: {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."} Error: your balances were empty or unset balanceData error: Please make sure your system time is synchronized: call $api->useServerTime() before this function ERROR: Invalid request. Please double check your API keys and permissions. 
Balances: 

ordersLen: 2
signedRequest error: {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."} 
  
**Platform:**
- windows

**php version:**
- 7.0.24

**Long descrption**
My code was working fine, then this happend. Then it was all of a sudden working fine again so I went on a holiday weekend but when I returned, this was happening again.

thank you

**Comment by Stuperfied** [comment]
This seems to have fixed it. Thinking this should be added to the readme and all example codes.
`$api->useServerTime();`

**Comment by jockegbg** [comment]
Just add that at the top fixed the issue for me
$api->useServerTime();
