### ISSUE TITLE
Filter failure: LOT_SIZE

### ISSUE THREAD

**Issue by Modrx** [jaggedsoft/php-binance-api#236]
How do I place a sell order using PHP? I am getting the following error:
Filter failure: LOT_SIZE"

$order = $api->sell("BNBBTC", $quantity, $price);

Thank you!

**Comment by jaggedsoft** [comment]
LOT_SIZE usually means you need to order more

**Comment by Modrx** [comment]
How can I calculate the quantity automatically using the following:

$quantity = $balances['BNB']['available'];
$price = $api->price("BNBBTC");
$order = $api->sell("BNBBTC", $quantity, $price);
