### ISSUE TITLE
Buy Quantity Error

### ISSUE THREAD

**Issue by Modrx** [jaggedsoft/php-binance-api#237]
I am getting the following error when trying to place a buy order:

Request error: {"code":-1100,"msg":"Illegal characters found in parameter 'quantity'; legal range is '^([0-9]{1,20})(\\.[0-9]{1,20})?$'."}

$price = $bookPrices['BATETH']['bid'];
$quantity = ($balances['ETH']['available']) / $price;
$order = $api->buy("BATETH", $quantity, $price);

The following is not working either:

$price = $bookPrices['BATETH']['bid'];
$quantity = ($balances['ETH']['available']) / $price;
$buyquantity = number_format($quantity, 5, '.', '');
$order = $api->buy("BATETH", $buyquantity, $price);

**Comment by ePascalC** [comment]
@Modrx 
number_format would return a string, so that cannot be correct...
Has your issue been fixed by now?

**Comment by ePascalC** [comment]
I suppose this was fixed, closing...
