### ISSUE TITLE
How do I check if a connection is succesfull

### ISSUE THREAD

**Issue by vreesie18** [jaggedsoft/php-binance-api#238]
How do I check if a connection is succesfull when I execute $api = new Binance\API( "myfile.json" ); ???
So succesfull in the sense of:
- api exists
- credentials are valid

Thank you!!

Regards.

**Comment by ePascalC** [comment]
Hi @vreesie18 
I would say that a call to $api->accountStatus() or $api->apiTradingStatus() might be a good reference
