### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 1

### ISSUE THREAD

**Issue by AMONRA75** [jaggedsoft/php-binance-api#239]
hi,
for some days I have seen this error that sometimes appears, what can it be?

`
Fatal error: Uncaught TypeError: Argument 1 passed to Binance\API::priceData() must be of the type array, null given, called in /opt/lampp/htdocs/binax5/vendor/jaggedsoft/php-binance-api/php-binance-api.php on line 631 and defined in /opt/lampp/htdocs/binax5/vendor/jaggedsoft/php-binance-api/php-binance-api.php:1343 Stack trace: #0 /opt/lampp/htdocs/binax5/vendor/jaggedsoft/php-binance-api/php-binance-api.php(631): Binance\API->priceData(NULL) #1 /opt/lampp/htdocs/binax5/info.php(8): Binance\API->prices() #2 {main} thrown in /opt/lampp/htdocs/binax5/vendor/jaggedsoft/php-binance-api/php-binance-api.php on line 1343
`

best regards

**Comment by ePascalC** [comment]
@AMONRA75 It looks like the first argument that you pass is sometimes NULL, so you will have to review your code.
