### ISSUE TITLE
Stop Loss orders not happening

### ISSUE THREAD

**Issue by thepaandu** [jaggedsoft/php-binance-api#24]
Hey, the issue is similar to the one found in your nodejs project.
Unable to place stoploss due to flags triggers.

**Comment by jaggedsoft** [comment]
Thank you for your report! We need to add the `type` flag to all stoploss orders:
STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT, TAKE_PROFIT_LIMIT

**Comment by thepaandu** [comment]
Can we have a temporary solution for it?
Thanks.

**Comment by jaggedsoft** [comment]
This is a stop loss that will market sell, but you can also use STOP_LOSS_LIMIT

```php
// When the stop is reached, a stop order becomes a market order
$type = "STOP_LOSS"; //STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT, TAKE_PROFIT_LIMIT
$quantity = 1;
$price = 0.5; // Try to sell it for 0.5 btc
$stopPrice = 0.4; // Sell immediately if price goes below 0.4 btc
$order = $api->sell("BNBBTC", $quantity, $price, $type, ["stopPrice"=>$stopPrice]);
print_r($order);
```
