### ISSUE TITLE
Margin Trading Integration.

### ISSUE THREAD

**Issue by quadricanna** [jaggedsoft/php-binance-api#243]
I've been trying to modify this wrapper to work with Binance new Margin API. I'm wondering if you have an update coming for Margin trading?

Thanks

**Comment by alanmassiveliar** [comment]
> I've been trying to modify this wrapper to work with Binance new Margin API. I'm wondering if you have an update coming for Margin trading?
> 
> Thanks

Binance no longer supports API development, therefore you'll see no support or updates here.
Could you share modified API for margin trading?

**Comment by camuig** [comment]
Here it is https://binance-docs.github.io/apidocs/spot/en/#margin-account-trade

**Comment by ericol** [comment]
@quadricanna what features do you want to implement? I managed to implement a couple on my own.

**Comment by ePascalC** [comment]
@quadricanna multiple sapi commands are already added. If you need a specific one, please open a new issue so we can work on that.
