### ISSUE TITLE
All orders api command

### ISSUE THREAD

**Issue by phreakske** [jaggedsoft/php-binance-api#246]
Get all account orders; active, canceled, or filled.

$orders = $api->orders("BNBUSDT");
print_r($orders);

If i use this example with my key and secret, i don't see all orders, but only all orders until february 2019, the newer orders aren't visible.

**Comment by ePascalC** [comment]
@phreakske You could 1) give startTime and endTime as optional parameters or 2) increase the limit to 1000 (maximum)
public function orders(string $symbol, int $limit = 500, int $fromOrderId = 0, array $params = [])

1)
```
$startTime = strtotime('2021-03-01 00:00:00')*1000;
$endTime = strtotime('2021-03-01 23:59:59')*1000;
$params = array('startTime' => $startTime, 'endTime' => $endTime);
$orders = $api->orders('BNBUSDT', 500, 0, $params);

```
2)
`$orders = $api->orders('BNBUSDT', 1000);`
