### ISSUE TITLE
It is "echo"ing errors (no exceptions thrown or errors returned) so we cannot handle errors

### ISSUE THREAD

**Issue by error-handling** [jaggedsoft/php-binance-api#247]
This API, instead of throwing an exception, or returning the error, literally echoes: `echo $error_text` all the errors in the library itself, so how should we handle errors (detect the error and show it appropriately within the design) and prevent it from echoing stuff on top of `<!DOCTYPE html>` (making the whole html invalid and breaking the design)?

I guess we have to either use

> ob_start();
> apiFunction(); // Use this API's methods here to avoid the echoes
> $output = ob_get_clean();

to prevent it from echoing errors (and then read the $output to detect what it is, which is just so much extra work for no reason), or rewrite the whole thing :)

**Comment by jaggedsoft** [comment]
This library will be taken down if it is no longer of any use.

**Comment by error-handling** [comment]
@jaggedsoft My apologies if I was rude in any way, I initially thought you're a company and Binance paid your company to make a functioning open source PHP API, and was mostly mad at Binance.

Had no idea this is a free project managed by a few people until after posting the issue.

I'm sure it is still useful to a lot of people and appreciated.

If I end up editing this (for error handling) will make a pull request as soon as its done.

Hope there is no hard feelings 👍
Best wishes.
