### ISSUE TITLE
Function PRICE shown in README does not exists

### ISSUE THREAD

**Issue by pilootchoum** [jaggedsoft/php-binance-api#249]
The following function : 

Get latest price of a symbol
$price = $api->price("BNBBTC");
echo "Price of BNB: {$price} BTC.".PHP_EOL;

Which is shown in documentation does not exists at all in the code,

Am i missing something?

**Comment by pilootchoum** [comment]
`public function price($symbol) {
        return $this->httpRequest( "v3/ticker/price?symbol=" . $symbol );
    }`

In case someone needs it.

**Comment by jaggedsoft** [comment]
Thanks for your help. I do see it in the code however
```php
    public function prices()
    {
        return $this->priceData($this->httpRequest("v3/ticker/price"));
    }
    /**
     * price get the latest price of a symbol
     *
     * $price = $api->price( "ETHBTC" );
     *
     * @return array with error message or array with symbol price
     * @throws \Exception
     */
    public function price(string $symbol)
    {
        $ticker = $this->httpRequest("v3/ticker/price", "GET", ["symbol" => $symbol]);
        return $ticker['price'];
    }
```

**Comment by pilootchoum** [comment]
> Thanks for your help. I do see it in the code however
> 
> ```
>     public function prices()
>     {
>         return $this->priceData($this->httpRequest("v3/ticker/price"));
>     }
>     /**
>      * price get the latest price of a symbol
>      *
>      * $price = $api->price( "ETHBTC" );
>      *
>      * @return array with error message or array with symbol price
>      * @throws \Exception
>      */
>     public function price(string $symbol)
>     {
>         $ticker = $this->httpRequest("v3/ticker/price", "GET", ["symbol" => $symbol]);
>         return $ticker['price'];
>     }
> ```

So I guess this is in the @dev version that it is missing, you should maybe remove it from the installation doc then.

Regards
