### ISSUE TITLE
invalid float parsing

### ISSUE THREAD

**Issue by michnovka** [jaggedsoft/php-binance-api#25]
I encountered this error with PHP:

```
Array
(
    [code] => -1100
    [msg] => Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'.
)
```

I was using

`$order = $api->sell($symbol."BTC", $spend, $price_desired, "LIMIT", $flags);`

$price_desired was float.

This is what fixed it:

`$order = $api->sell($symbol."BTC", $spend, number_format($price_desired,8,'.',''), "LIMIT", $flags);`

its because PHP treats that float as: float(1.1E-5) instead of 0.00011

please fix this in order function

**Comment by jaggedsoft** [comment]
Thank you for your report. This is up to you to do at the $price_desired level but I will probably add a built in function to handle it for you
