### ISSUE TITLE
PHP Notice:  Curl error: Failed to connect to api.binance.com port 443: Timed out

### ISSUE THREAD

**Issue by phreakske** [jaggedsoft/php-binance-api#250]
**Title**
- bug: Curl Error

**Short Description:**
PHP Notice:  Curl error: Failed to connect to api.binance.com port 443: Timed out
  
**Platform:**
- windows

**php version:**
- 7.3.7

**Long descrption**
PHP Notice:  Curl error: Failed to connect to api.binance.com port 443: Timed out
UndefError: your balances were empty or unset
ibalanceData error: Please make sure your system time is synchronized: call $api->useServerTime() before this function
nERROR: Invalid request. Please double check your API keys and permissions.

This started yesterday out of the blue, script ran for 3 months no problem.
curl gives nog specific error in the log files, certificate ok, created new api keys, servertime was ok, checked everything --> no change.
The connect stays for a few minutes then get interrupted. Script keeps on working.. 
I get the above every 5 minutes and every minute or so only this :
>> PHP Notice:  Curl error: Failed to connect to api.binance.com port 443: Timed out

**Comment by jaggedsoft** [comment]
Issue is on Binance's end, not this library. If there is better error handling we can do then we're open to suggestions

**Comment by phreakske** [comment]
Thanks for the update… 

 

Van: Jon Eyrick <notifications@github.com> 
Verzonden: zaterdag 28 september 2019 9:10
Aan: jaggedsoft/php-binance-api <php-binance-api@noreply.github.com>
CC: phreakske <phreakske@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [jaggedsoft/php-binance-api] PHP Notice: Curl error: Failed to connect to api.binance.com port 443: Timed out (#250)

 

Issue is on Binance's end, not this library. If there is better error handling we can do then we're open to suggestions

**Comment by jaggedsoft** [comment]
I ran into this issue a long time ago but it only happened if I was sending too many requests to binance. If I went over a certain number of requests per minute, their load balancer/firewall would temporarily block me. Only other thing I can think of

**Comment by phreakske** [comment]
Hi there,

 

It seems after 3 minutes connection is refused…  i’ve timed it with a stopwatch.. every 3 minutes, disconnect..

Every 3 minutes, active WebSocket connections will receive a ping. If you do not respond with a properly framed pong, your connection will be terminated.

For user data streams, if a keep-alive is not received at least once every 60 minutes, the listen key will expire. This is also detailed in our WAPI Documentation <https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md> .

Have they activated it for API use too ?

I think this could be the bug, but it’s weird, it ran for months perfectly, no code changed.

Sincerely,

Frank

 

 

 

Van: Jon Eyrick <notifications@github.com> 
Verzonden: zaterdag 28 september 2019 9:43
Aan: jaggedsoft/php-binance-api <php-binance-api@noreply.github.com>
CC: phreakske <phreakske@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [jaggedsoft/php-binance-api] PHP Notice: Curl error: Failed to connect to api.binance.com port 443: Timed out (#250)

 

I ran into this issue a long time ago but it only happened if I was sending too many requests to binance. If I went over a certain number of requests per minute, their load balancer/firewall would temporarily block me. Only other thing I can think of

**Comment by newprogrammeram** [comment]
i have the same problem
, i dont understand , need email and password and verify code , 
and if need how to enter them?

**Comment by phreakske** [comment]
Hi there,

If i have curl error, problem is loss of internet of wifi... and script crashes. Seems ISP updates internet modem at night. And then disconnects whole network. I'm looking for a backup solution with 4G now.

Or when binance are doing maintenance, you will get same error but that's normal.

Sincerely,

phreakske
