### ISSUE TITLE
Which part works asynchronously?

### ISSUE THREAD

**Issue by camuig** [jaggedsoft/php-binance-api#251]
Hi,

I've checked httpRequest method and here is simple curl request. Also I can't find any references to promises. So which part works asynchronously? Maybe I have to use another methods for async requests?

thank you

**Comment by jaggedsoft** [comment]
Websockets are likely the only part that could be considered "asynchronous" on the PHP version. I'd take the repository down but there's nothing else for PHP, maybe someone else can make it into something better.
