### ISSUE TITLE
Precision is over the maximum defined for this asset.

### ISSUE THREAD

**Issue by cyvitor** [jaggedsoft/php-binance-api#252]
HI!
Actually it's a doubt

I tried to make a purchase of the LINKBTC pair worth 0.0002863. Investing: 0.004 BTC.
The resulting gave 13.971358714635 LINK.
But this pair does not support decimal, and some do.
How can I tell which pair supports decimals?

**Comment by ePascalC** [comment]
@cyvitor please use $api->exchangeInfo() to find the info for the pair.
