### ISSUE TITLE
bug: marketSell() Call to undefined method Binance\API::numberOfDecimals()

### ISSUE THREAD

**Issue by petr-hejda** [jaggedsoft/php-binance-api#255]
**Title**
- bug: marketSell() Call to undefined method Binance\API::numberOfDecimals()

**php version:**
- 7.3.39

**Short escrption**
- Method `marketSell()` is calling non-existent method `numberOfDecimals()`
- The `numberOfDecimals()` call was added in this commit - https://github.com/jaggedsoft/php-binance-api/commit/368f5ef094657b6868cfd7499ae7c00436c3d51f

**code**
```php
require 'vendor/autoload.php';
$api = new Binance\API("<api key>","<secret>");
$api->marketSell("BNBBTC", 2.69);
```

** exception **
```
PHP Fatal error:  Uncaught Error: Call to undefined method Binance\API::numberOfDecimals() in ./vendor/jaggedsoft/php-binance-api/php-binance-api.php:341
Stack trace:
#0 ./check.php(121): Binance\API->marketSell('BNBBTC', 2.69) /* this is just my script */
#1 {main}
  thrown in ./vendor/jaggedsoft/php-binance-api/php-binance-api.php on line 341
```

**Comment by areebmajeed** [comment]
https://github.com/jaggedsoft/php-binance-api/pull/256
