### ISSUE TITLE
Balance check: Misschien BTC values/totals

### ISSUE THREAD

**Issue by timh77** [jaggedsoft/php-binance-api#26]
When checking my balance it seems the BTC value for every alt is missing, like this one but also for alts which have a total value of over 1 btc.

`$balances = $api->balances("BTC");
print_r($balances);

Result:
    [XVG] => Array
        (
            [available] => 0.66500000
            [onOrder] => 0.00000000
            [btcValue] => 0
            [btcTotal] => 0
        )`

**Comment by jaggedsoft** [comment]
If you want the calculated btc value you must pass it the $ticker parameter. I should be more clear as to what that parameter is

For now this is what I do:
```php
$ticker = $api->prices();
//print_r($ticker); // List prices of all symbols
//echo "Price of BNB: {$ticker['BNBBTC']} BTC\n";
$balances = $api->balances($ticker);
print_r($balances);
```
![image](https://user-images.githubusercontent.com/4283360/34739572-8b92bf12-f531-11e7-9f89-17985e35eea6.png)
Return is all symbols and their estimated btcValue. btcTotal includes the amount that's locked on open orders


You can also maintain an up to date $ticker object automatically with websockets, i'll provide an example when i have more time
