### ISSUE TITLE
"Too much request weight used"

### ISSUE THREAD

**Issue by Synthacon** [jaggedsoft/php-binance-api#260]
I get this error:
"Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API."

It's somehow connected to order and price request. 
$orders = $api->orders($pair);
$price  = $api->price($pair);

When I do this requests for each coin (5-10 coins) I get the error. I't does not happen each and every time, It might work fine for a day, but yesterday/ today when bitcoin had big moves I got this errors all the time. So is this problem in API code or is Binance API choking on the requests?

**Comment by 2pd** [comment]
You hit the binance API limit, lower the request rate or better use the websocket.
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md
