### ISSUE TITLE
Filter failure: MIN_NOTIONAL

### ISSUE THREAD

**Issue by Synthacon** [jaggedsoft/php-binance-api#263]
code:

$pair ="BTCUSDC";
$amount = "0.001";
$rate  = "7400";
        
$result= $api->sell($pair, $amount , $rate);

returns:

signedRequest error: {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"} array(2) { ["code"]=> int(-1013) ["msg"]=> string(28) "Filter failure: MIN_NOTIONAL" }

Am I doing something wrong or is this a bug?

**Comment by jaggedsoft** [comment]
means you're not selling enough
search past issues for MIN_NOTIONAL

**Comment by Synthacon** [comment]
Ok. thank you!

**Comment by aligtp** [comment]
Thanks, it is useful
