### ISSUE TITLE
LOT_SIZE Error

### ISSUE THREAD

**Issue by rhrahul** [jaggedsoft/php-binance-api#27]
Array
(
    [code] => -1013
    [msg] => Filter failure: LOT_SIZE
)

Error in placing Market Order
$order = $api->buy($pair, $quantity, 0, "MARKET");

**Comment by jaggedsoft** [comment]
This is short for saying $quantity too small

**Comment by jaggedsoft** [comment]
You can use `$api->exchangeInfo();` to pull the minimums for each pair

Here is how i do it in javascript, will make the same available for PHP when i have time
https://github.com/jaggedsoft/node-binance-api/issues/23

**Comment by rhrahul** [comment]
Thank @jaggedsoft 👍
