### ISSUE TITLE
hi Jaggedsoft, we would like to add multiple accounts to our bot. They will have their own API and secret keys though. Is it possible to open up more than one socket with different keys or can we use one websocket and access multiple user data to update in the system. Your help is much appreciated please..

### ISSUE THREAD

**Issue by asitha07** [jaggedsoft/php-binance-api#271]
**Title**
- bug: XYZ broken
- feature: please add
- enhancement: add this to existing features

**Short Description:**
- Unable to get a result from blah
  
**Platform:**
- windows
- linux
- macos

**php version:**
- 7.0.24

**Long descrption**
- Doing xyz results in ypr and failing when fph

**code**
```php
require 'vendor/autoload.php';
$api = new Binance\API("<api key>","<secret>");
$ticker = $api->prices();
print_r($ticker); // List prices of all symbols
echo "Price of BNB: {$ticker['BNBBTC']} BTC";
```

**result**
```
{
   "result":"result"
}
```

thank you

**Comment by jaggedsoft** [comment]
I think this might only be possible with https://github.com/jaggedsoft/node-binance-api which has a lot more capabilities

**Comment by asitha07** [comment]
Hi Jon;

Thank you very much for your prompt response.

We shall be grateful to you if you could kindly help us in doing a sample
code to multiple user data please.

Cheers
Asitha

**Comment by jaggedsoft** [comment]
In javascript it's very easy:
```js
const Binance = require('node-binance-api');
const instance1= new Binance().options({
  APIKEY: '<key1>',
  APISECRET: '<secret1>'
});
const instance2= new Binance().options({
  APIKEY: '<key2>',
  APISECRET: '<secret2>'
});
```

**Comment by asitha07** [comment]
Hi Jon;

You are excellent and thank you very much for helping.

We have been trying using PHP, but didn't succeed.

We will try using your Node API, hopefully the sample code for WebSocket
for user data is there right.

If you are into cryptocurrency trading, we can invite you and provide you
with a complimentary (free access to our system)

Cheers
Asitha
