### ISSUE TITLE
websocket timeouts

### ISSUE THREAD

**Issue by vreesie18** [jaggedsoft/php-binance-api#275]
On a regular basis a get the error like below. Seems like the websocket is timeout but this happens in about a half hour is which the websockter loop is almost 300 times triggered.

ERROR:
chart(LTCBTC,1m) WebSocket Connection closed! (1008 - Pong timeout)
	2020-03-12 08:45:25 Custom error: [8] Unknown: send of 5 bytes failed with errno=32 Broken pipe

My code:
$binance_api->chart([$Coin.$Market], $Period, function($binance_api, $symbol, $chart1) {
THINGS HAPPEN
 }

Is there a way to prevent these time-outs ?

Thanks in advance.

Regards,
Andre

**Comment by jaggedsoft** [comment]
Thank you for the report

Yeah PHP is really not meant for websockets unfortunately, I don't understand the ratchet event loop enough to fix it unless it's something easy like this:
I think binance lowered their keepalive time from 30 minutes to 3 minutes, so we might need to increase the speed of the timer as well.

My javascript library works much better for these sorts of things, if you just want to collect some json: https://github.com/jaggedsoft/node-binance-api

**Comment by vreesie18** [comment]
Okay, I'll give it a try. thanks!

**Comment by vreesie18** [comment]
One more question, what is the best way to close a websocket gracefully within php ?

**Comment by jaggedsoft** [comment]
there's a terminate function 

View endpoints first: print_r($api->subscriptions)
$api->terminate('ethbtc_kline@5m');

for using websockets in php: https://github.com/ratchetphp/Ratchet
