### ISSUE TITLE
How to place market buy with notional (fiat) amount

### ISSUE THREAD

**Issue by pfergi42** [jaggedsoft/php-binance-api#277]
**Title**
- bug: Can't issue Market Buy order with notional fiat amount
- feature: Please add MarketBuyNotional() function

**Short Description:**
- Unable to issue market buy order using USD amount. Only supports BTC amount.

**Comment by robsantini** [comment]
Not sure, but my [PR!321](https://github.com/jaggedsoft/php-binance-api/pull/321) should do exactly what you asked for.
