### ISSUE TITLE
Orders -- this does not work

### ISSUE THREAD

**Issue by jorejel** [jaggedsoft/php-binance-api#278]
**Title**
- bug: Orders

**Short Description:**
- this does not work
  
**Platform:**
- linux

**php version:**
- 7.0.24

**Long descrption**
- this does not work, Get all account orders; active, canceled, or filled.

**code**
```php
require 'vendor/autoload.php';
$api = new Binance\API("<api key>","<secret>");
$orders = $api->orders( "BNBBTC" ); 
print_r($orders);
```

**result**
```
{
   Error: {"code":-1104,"msg":"Not all sent parameters were read; read '4' parameter(s) but was sent '5'."}
}
```

thank you

**Comment by websa24** [comment]
I'm getting the same issue, PHP Version 7.3.9, other functions I have tested so far works fine ( user account balance ) latest prices ect.

**Comment by novustec** [comment]
Hello, I'm having the same error did anyone manage to correct?

**Comment by novustec** [comment]
I found the error, the if is incorrect.

Remove this line from php-binance-api.php:
if($fromOrderId > 0) $parameters[] = ["orderId" => $fromOrderId];

**Comment by jaggedsoft** [comment]
thank you novustec, fixed https://github.com/jaggedsoft/php-binance-api/commit/ecdabea05d685adc82444a0af08a33d311dc9019
