### ISSUE TITLE
Error - Parameter 'quantity' sent when not required

### ISSUE THREAD

**Issue by novustec** [jaggedsoft/php-binance-api#279]
**Title**
- bug: Market Order

**Short Description:**
- intermittent error
  
**Platform:**
- Linux

**php version:**
- PHP 7.0.33-0ubuntu0.16.04.14

**Long descrption**
I am placing a market order and I receive the error intermittently;

**code**
```
$order = $api->marketSell("$coin", "$qtd");
$print_r($order);
```

**result**
```
{
   signedRequest error: {"code":-1106,"msg":"Parameter 'quantity' sent when not required."}
}
```

thank you

**Comment by ePascalC** [comment]
Hi, I would not put $qtd between the double quotes, so better just use $order = $api->marketSell("$coin", $qtd);
If suppose this is solved already, but in case not, please open another issue.
