### ISSUE TITLE
bookprinces bids last 100

### ISSUE THREAD

**Issue by shellbr** [jaggedsoft/php-binance-api#28]
$bookPrices = $api->bookPrices();
echo "Bid price of ETH: {$bookprices['ETHBTC']['bid]}".PHP_EOL;
OK

as it would be for the list of the last 100?
echo "Bid price of ETH: {$bookprices['ETHBTC']['bids']['100']}".PHP_EOL;

**Comment by jaggedsoft** [comment]
`$recent = array_slice($bookprices['ETHBTC']['bid],-100);`

**Comment by shellbr** [comment]
It does not work, this is what I have.

<?php
require 'binance-api-single.php';
$api = new Binance("<key>","<secret>");
$ticker = $api->prices();
print_r($ticker); // List prices of all symbols 
echo "Price of BNB: {$ticker['BNBBTC']} BTC.".PHP_EOL;


$recent = $bookprices(['ETHBTC']['bid'],-100);
echo $recent;

**Comment by jaggedsoft** [comment]
bookPrices only returns the best bid / lowest ask
```php
$bookPrices = $api->bookPrices();
echo "Bid price of ETH: {$bookPrices['ETHBTC']['bid']}".PHP_EOL;
print_r($bookPrices['ETHBTC']);
```
![image](https://user-images.githubusercontent.com/4283360/34910248-e5df40e4-f865-11e7-97f1-ef24b6c2f375.png)

Sounds like what you want is the depth cache
Try this, it uses websockets and fires often

```php
$api->depthCache("ETHBTC", function($api, $symbol, $depth) {
	echo "{$symbol} depth cache update".PHP_EOL;
	//print_r($depth); // Print all depth data
	$limit = 11; // Show only the closest asks/bids
	$sorted = $api->sortDepth($symbol, $limit);
	$bid = $api->first($sorted['bids']);
	$ask = $api->first($sorted['asks']);
	echo $api->displayDepth($sorted);
	echo "ask: {$ask}".PHP_EOL;
	echo "bid: {$bid}".PHP_EOL;
});
```

![image](https://user-images.githubusercontent.com/4283360/34910268-2fd25b1e-f866-11e7-9bde-65b4a7398ed9.png)

**Comment by shellbr** [comment]
ok had tried, result in white
and need active some library or module in php
