### ISSUE TITLE
Is sapi services scheduled to be implemented?

### ISSUE THREAD

**Issue by mtb-pro** [jaggedsoft/php-binance-api#286]
As you know /sapi endpoints added to binance APIs. Will you plan to add its implementation to php-binance-api package? 

Thanks in advance

**Comment by jaggedsoft** [comment]
I don't have time to support anything other than the javascript API
https://github.com/jaggedsoft/node-binance-api

however binance has started working on an official API wrapper

**Comment by ePascalC** [comment]
@mtb-pro Several sapi calls have been added already. If there is a specific one you need, feel free to create a new issue.
