### ISSUE TITLE
Low prices are giving error. + FIX

### ISSUE THREAD

**Issue by webvoicenl** [jaggedsoft/php-binance-api#29]
small numers like 0.000098 will be formatted like this:  &price=9.82E-5
Raising the following error: Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'. 

Fix:
file: php-binance-api.php
line: 129 add following code:
if(isset($params['price']))
		{
			$params['price'] = number_format($params['price'], 8, '.', '');
		}
Binance useses 8 precision for all its coins.

I am sorry, I am not that familiar with forking and updating the code. maybe the creator can add this? ;)
Cheers

**Comment by jaggedsoft** [comment]
Thank you very much

**Comment by dmzoneill** [comment]
please assign this to me if its still valid

**Comment by jaggedsoft** [comment]
Yeah this needs to be done, either transparently in the order function, and/or provide a shortcut function for this:

`return number_format($price, 8, '.', '')`

**Comment by dmzoneill** [comment]
@jaggedsoft  @webvoicenl 

what do you think of this?

![image](https://user-images.githubusercontent.com/15192260/37686695-70603de6-2c90-11e8-91d0-22ca0e109c06.png)

**Comment by jaggedsoft** [comment]
Oh yeah, love it. Nice work.

**Comment by jaggedsoft** [comment]
Thanks!!

**Comment by dmzoneill** [comment]
I'll do a few more tests tomorrow before commiting..  sensitive change...
