### ISSUE TITLE
[QUESTION] Will there be support for the Binance Futures?

### ISSUE THREAD

**Issue by KonesoN** [jaggedsoft/php-binance-api#291]
Will there be support for the Binance Futures?

Thank you

**Comment by jaggedsoft** [comment]
I don't have time to maintain this library anymore, you can use the node api which offers complete support
https://github.com/jaggedsoft/node-binance-api

otherwise binance is coming out with their own official php library soon

**Comment by KonesoN** [comment]
I'm using PHP, node is not suitable

Thank you
