### ISSUE TITLE
String considered as arrya

### ISSUE THREAD

**Issue by smamet** [jaggedsoft/php-binance-api#302]
https://github.com/jaggedsoft/php-binance-api/blob/d79babaa73855f754c3a6d756be8b0d05e99c92e/php-binance-api.php#L1051

Hi, while reusing your code, I think you have an issue there. 

$header is a string not an associative array, so the if condition on the weight headers cannot work.

Just wanted to point this out.

**Comment by smamet** [comment]
Quick fix : (not the best regarding the other headers, but will be perfect for weight calculation)

```
private function httpHeadersToArray($header) {
        $lines = explode("\r\n", $header);
        $out = [];
        foreach ($lines as $l) {
            $l = trim($l);
            $tmp = explode(':', $l);
            if (count($tmp) == 2) {
                $out[trim($tmp[0])] = trim($tmp[1]);
            } else {
                $out[] = $l;
            }
        }
        return $out;
    }
```

**Comment by ePascalC** [comment]
@smamet fix merged.
