### ISSUE TITLE
Return only one crypto asset 

### ISSUE THREAD

**Issue by StevenJ59** [jaggedsoft/php-binance-api#311]
Hello all

I try to display the asset of only one crypto for have ideally  

 $api->balances("BTC");

-> 0.0000058

But it's doesn't work :(  i have this

$ Array ( [BTC] => Array ( [available] => 0.00000000 [onOrder] => 0.00000000 [btcValue] => 0 [btcTotal] => 0 ) [LTC] => Array ( [available] => 0.00000000 [onOrder] => 0.00000000 [btcValue] => 0 [btcTotal] => 0 ) [ETH] => Array ( [available] => 0.00000000 [onOrder] => 0.00000000 [btcValue] => 0 [btcTotal] => 0 ) [NEO] => Array ( [available] => 0.00000000 [onOrder] => 0.00000000 [btcValue] => 0 [btcTotal] => 0 ) [BNB] => Array ( [available] => 0.00000000 [onOrder] => 0.00000000 [btcValue] => 0 [btcTotal] => 0 ) [QTUM] => Array ( [available] => 0.00000000 [onOrder] => 0.00000000 [btcValue] => 0 [btcTotal] => 0 ) [EOS] => Array ( [available] => 0.00000000 [onOrder] => 0.00000000 [btcValue] =>............

I'm sorry if it's noob question i'm beginner  
Thanks you

**Comment by jaggedsoft** [comment]
you might have to do it like this

```php
$balances = $api->balances();
print_r($balances['BTC']);
echo "{$balances['BTC']['available']} BTC available";
```

**Comment by StevenJ59** [comment]
Hello thanks for you for u help and fast reply !
Have a good day
