### ISSUE TITLE
Binance.US

### ISSUE THREAD

**Issue by michael-mrm** [jaggedsoft/php-binance-api#318]
**Title**

- feature: please add support for binance.us let me know if you need help
- enhancement: same thing for binance.us

**Short Description:**
- signedRequest error: {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
  
**Platform:**
- linux

**php version:**
- 7.0.24

**Long descrption**
- same code not working for binance.us probably because the apis are setup differently between the two exchanges.

**code**
```
Deprecated: Required parameter $callback follows optional parameter $interval in /app/vendor/jaggedsoft/php-binance-api/php-binance-api.php on line 2090
signedRequest error: {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
```

**result**
```
{"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
```

thank you

**Comment by ePascalC** [comment]
@michael-mrm, the deprecated warning has been fixed some time ago. For binance.us use, you can refer to the FAQ: https://github.com/jaggedsoft/php-binance-api/wiki/FAQ#can-i-use-this-php-library-for-binanceus
