### ISSUE TITLE
Api With https://testnet.binancefuture.com

### ISSUE THREAD

**Issue by bousalem** [jaggedsoft/php-binance-api#319]
Hello;

Can I use this api with test platform (https://testnet.binancefuture.com)? and how can use it?

Thanks

**Comment by robsantini** [comment]
No, you can't. This library does not cover the futures platform.

**Comment by dmzoneill** [comment]
https://github.com/jaggedsoft/php-binance-api/commit/537fd7b241575d3aabfa4a00e6178e83eafd1afe
