### ISSUE TITLE
make raw request

### ISSUE THREAD

**Issue by Sparviero-Sughero** [jaggedsoft/php-binance-api#322]
**custom request**
- feature: a method to do custom requests
- enhancement: using binance's docs, it's possible to do whatever

**Short Description:**
- is not possible to use some binance's api features 
  
**Platform:**
- windows
- linux
- macos

**php version:**
- 7.0.24

**Long descrption**
- a simply method to create custom request

**code**
```
public function rawRequest(string $url, string $method = "GET", array $params = [], bool $signed = false) {
    return $this->httpRequest($url, $method, $params, $signed);
}
```

thank you

**Comment by dmzoneill** [comment]
@Sparviero-Sughero if you would like to produce a pull request, we would gladly accept.

Thanks

**Comment by Sparviero-Sughero** [comment]
ops, sorry
