### ISSUE TITLE
how to fix error -4007

### ISSUE THREAD

**Issue by ebrahimsalahi** [jaggedsoft/php-binance-api#325]
How To Fix Error ?

 signedRequest error: {"msg":"-4007=Address verification failed","success":false}

**Comment by ebrahimsalahi** [comment]
@blue73

**Comment by dmzoneill** [comment]
need to update the code with try catch blocks for this issue

**Comment by ebrahimsalahi** [comment]
Hello
I want to send Tether to a wallet address via api binance 
How should I do it?
Should I use this inventory withdrawal function?

Thanks for your help to me

**Comment by ebrahimsalahi** [comment]
```
$asset = "USDT";
$address = "TJM2*****TPdz";
$amount = 10;

try {
     $response = $api->withdraw($asset, $address, $amount );
} catch (Exception $e) {
    echo  $e->getMessage(), "\n";
}
var_dump($response);


Result :

signedRequest error: {"msg":"-4007=Address verification failed","success":false}

**Comment by ePascalC** [comment]
@ebrahimsalahi did you fix this? It really looks like the $address is incorrect...

**Comment by arashyarix** [comment]
anybody can fix this? 
I have the same problem.
