### ISSUE TITLE
Needs PHP 8 support 

### ISSUE THREAD

**Issue by compunect** [jaggedsoft/php-binance-api#326]
**Title**
- bug: Deprecated: Required parameter $callback follows optional parameter $interval in /binance/vendor/jaggedsoft/php-binance-api/php-binance-api.php on line 2009

**Short Description:**
The Api does not support the current PHP version.
I've no idea how big the scope of the problem is, the first deprecated warnings appear quite early
I believe this needs a full evaluation to bring the API up to date, without PHP 8 support it's destined to die
  
**php version:**
- 8.0

**Comment by dmzoneill** [comment]
hi Compunect,

I'm running php 8.0.3.
I'm yet to see any errors.
Could you provide examples of said issues.
Without any detailed reports, its hard to move this forward.

thank you

dmzoneill@dave-x1e2:~/src/php-binance-bot$ php --version
PHP 8.0.3 (cli) (built: Mar 10 2021 13:42:09) ( ZTS DEBUG )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies

**Comment by Antonsteb** [comment]
Hi, I ran the same error in laravle cron
Kernal:
`protected function schedule(Schedule $schedule)
    {
       $binanceService = new BinanceService($key, $secret);
        $schedule->call( $binanceService)->everyMinute();
    }`

BinanceService:
`class BinanceService
{
    private $apiKey;
    private $apiSecret;

    public function __construct($apiKey,$apiSecret)
    {
        $this->apiKey = $apiKey;
        $this->apiSecret = $apiSecret;
   }

    /**
     * @return AlgorithmEventDto[] array of algorithm events
     * @throws Exception
     */
    public function runAlgorithm(): array
    {
        $api = new Binance\API($this->apiKey, $this->apiSecret);   // in this string i get this error     

    }

    /**
     * for crone.
     */
    public function __invoke()
    {
        try {
           $this->runAlgorithm();
        } catch (Exception $e) {
            file_put_contents($this->errorPath,$e->getMessage(),FILE_APPEND);
        }
    }    
}`


I only get this error when running through cron.
If I do in Controller:
$binanceService = new BinanceService ($key, $secret);
$binanceService();
then there is no error.

php version: 8.0.3

**Comment by jianjye** [comment]
This issue should be related to this: https://stackoverflow.com/questions/65297279/required-parameter-xxx-follows-optional-parameter-yyy

```
public function chart($symbols, string $interval = "30m", callable $callback, $limit = 500) {}
```

Since `$callback` is not optional, it needs to be in front of $interval in PHP 8. Either that or we need to add a default to $callback to continue on this argument sequence.

**Comment by jianjye** [comment]
I have also encountered this error:

```
 ErrorException 

  uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero

  at vendor/jaggedsoft/php-binance-api/php-binance-api.php:1268
    1264▕         }
    1265▕         if (is_array($priceData)) {
    1266▕             uasort($balances, function ($opA, $opB) {
    1267▕                 return $opA['btcValue'] < $opB['btcValue'];
  ➜ 1268▕             });
    1269▕             $this->btc_value = $btc_value;
    1270▕             $this->btc_total = $btc_total;
    1271▕         }
    1272▕         return $balances;
```

The correct update should be to replace

```
Replace line 1267:
return $opA['btcValue'] < $opB['btcValue'];

With:
return ($opA['btcValue'] < $opB['btcValue']) ? -1 : 1;
```

**Comment by dmzoneill** [comment]
this should be resolved by

https://github.com/jaggedsoft/php-binance-api/pull/342

**Comment by ePascalC** [comment]
@dmzoneill I suppose that is 341 and not 342? For the 2nd PHP item from @jianjye , do you want to split it into another issue?

@jianjye Should it not return 0 and 1? According to https://www.php.net/manual/en/language.types.boolean.php -1 results in true! Or better, should it not be ? false : true to be more clear? (Haven't checked PHP 8 yet...)

**Comment by jianjye** [comment]
@ePascalC The `uasort` function would return boolean, but in its callback function it expects 0 (if equals), -1 or 1 if one is greater than another based on the doc's example: https://www.php.net/manual/en/function.uasort. Caveat: I have not used this function personally myself.

Sure we can separate this as a different issue.

**Comment by ePascalC** [comment]
@jianjye ah of course, you are right! Let me push that in. Thx.
