### ISSUE TITLE
error code":-1121

### ISSUE THREAD

**Issue by morteza4422** [jaggedsoft/php-binance-api#329]
i have problem when i want to convert my USDT to BNB i tried every method of below
marketBuy("BNBUSDT",58); , marketBuy("USDTBNB",58);
marketSell("USDTBNB",58) ,  marketSell("USDTBNB",58)
but none of them is work and i give error like this :
`**signedRequest error: {"code":-1121,"msg":"Invalid symbol."}**`
can some body help me ?

**Comment by ePascalC** [comment]
@morteza4422 
BNBUSDT should be the one working!
