### ISSUE TITLE
error in buying and selling

### ISSUE THREAD

**Issue by trk2010** [jaggedsoft/php-binance-api#33]
Hello,
I use codes that you share. I do most of my work with this library.

The php-binance-api.php library is in its original state

I'm experimenting with trial.php 

`$symbol = "XVGBTC";
$quantity = 1;
$price = 0.00001114;
$price = number_format($price,8,'.','');

$order = $api->buy($symbol, $quantity, $price);
print_r($order);`

the error message is as follows.
`Array ( [code] => -1013 [msg] => Filter failure: MIN_NOTIONAL )`

I am waiting for your help on how to solve this problem

**Comment by jaggedsoft** [comment]
This is short for saying $quantity too small

You can use `$api->exchangeInfo();` to pull the minimums for each pair

Quantity must exceed MIN_NOTIONAL
Here is how i do it in javascript, will make the same available for PHP when i have time
https://github.com/jaggedsoft/node-binance-api/issues/23
![example](https://image.ibb.co/bz5KAG/notationals.png)

**Comment by jaggedsoft** [comment]
If you ever are having problems with the API try testing the same order from the binance website
