### ISSUE TITLE
Can u help me

### ISSUE THREAD

**Issue by vancedapp** [jaggedsoft/php-binance-api#330]
$api->miniTicker(function($api, $ticker) {
	print_r($ticker);
});

**nullminiticker: Could not connect: Connection to stream.binance.com:9443 failed: Last error for IPv4: Connection to tcp://54.150.210.31:9443?hostname=stream.binance.com failed: Connection refused. Previous error for IPv6: DNS query for stream.binance.com did not return a valid answer (NOERROR / NODATA)

**Comment by dmzoneill** [comment]
This has nothing to do with the API.
PHP is asking your systems resolver for DNS A record for stream.binance.com.
On linux, systemd based systems uses systemd-resolved.

something is broken in your PHP/system
