### ISSUE TITLE
how to run below command in windows 

### ISSUE THREAD

**Issue by newprogrammeram** [jaggedsoft/php-binance-api#338]
how to run below command in windows need to bat file or what,
should change?

mkdir -vp ~/.config/jaggedsoft/
cat >  ~/.config/jaggedsoft/php-binance-api.json << EOF
{
    "api-key": "<api key>",
    "api-secret": "<secret>",
    "proto": "https",
    "address": "proxy.domain.com",
    "port": "1080"
}
EOF

**Comment by dmzoneill** [comment]
hi newprogrammeram,

Unfortunately, i haven't used windows in over a decade.
Google is your friend here:
https://www.google.com/search?q=linux+mkdir
https://www.google.com/search?q=linux+cat
