### ISSUE TITLE
KP3R no btcValue and no btcTotal

### ISSUE THREAD

**Issue by eppenga** [jaggedsoft/php-binance-api#339]
Hi there!

My setup works great but for some odd reason the coin KP3R does not have a btcValue and also no btcTotal when it is available and / or on order. 

Used this example:
$ticker = $api->prices(); 
$balances = $api->balances($ticker);

All other coins do deliver a btcValue and btcTotal in the array when there is a position on that coin, except for KP3R, although some amount (0.35339000) is onOrder it says btcTotal = 0 which is incorrect. For all other coins it works perfect!

[KP3R] => Array
--
  | (
  | [available] => 0.00000000
  | [onOrder] => 0.35339000
  | [btcValue] => 0
  | [btcTotal] => 0

Kind regards, Ebo

**Comment by ePascalC** [comment]
Hi @eppenga,
Have a look at your $ticker array. You will see that there is no KP3RBTC market. For KP3R only [KP3RBNB] => 0.94300000
and [KP3RBUSD] => 243.64000000 markets exist.
So there is indeed no BTC value as that market does not exist.

**Comment by ePascalC** [comment]
@dmzoneill could probably be closed now

**Comment by eppenga** [comment]
Aaah thanks @ePascalC ! That makes sense, what I have done for now to get the proper total value of my wallet at Binance is retrieve indeed the KP3RBUSD value, retrieve the BTCBUSD price and calculate back the BTC value.

Or are there better ways to get the correct and total value of my wallet at Binance in BTC?

**Comment by ePascalC** [comment]
@eppenga Yes and no: It's logical that the BTC value is at 0, but I agree there should be somewhere a value... I have my own 'mywallet' implementation and I now see that I need to adapt it based on your findings :-) I will have to add a check for the btcValue = 0 and then do a double step: KP3R to BUSD and BUSD to BTC to get an approximate btc value.
Let me see if I find something useful and then maybe propose an 'MyWallet' function in the API here.

**Comment by ePascalC** [comment]
Hi @eppenga This is what I have now. It returns me an array with BTC and EUR estimations (including symbols like HEGIC and KP3R that are not on BTC. Any input from anyone?

`function get_mywallet() {
    global $api;
    $ticker = $api->prices();
    $balances = $api->balances($ticker);
    $min_btc_to_show = 0.0001;
    $totbtc = $toteur = $otherbtc = $othereur = 0;
    $return = array();
    foreach( $balances as $symbol=>$arr ) {
        if ( $arr['available'] > 0 ) {
            if ($arr['available'] > 0 && $arr['btcValue'] == 0 && gettype($arr['btcValue']) == 'integer') {
                // if a symbol that you have is not on the BTC market, this routine will indicate you an approximate BTC value
                // if btcValue is an integer, it means there is no BTC market
                // if btcValue is a string then the value you have is so low that it results into 0.000000 BTC
                foreach ($ticker as $k=>$v) {
                    if ( substr($k,0,strlen($symbol)) == $symbol ) {
                        $new_symbol = substr($k,strlen($symbol));
                        $btc_market = $new_symbol . 'BTC';
                        if (isset($ticker[$btc_market])) {
                            $arr['btcValue'] = $arr['available'] * $v * $ticker[$btc_market];
                            break;
                        } 
                    }
                }
            }
            $eur = round($arr['btcValue'] * $ticker['BTCEUR'], 2);
            $toteur = $toteur + $eur;
            $totbtc = $totbtc + $arr['btcValue'];
            if ($arr['btcValue'] <= $min_btc_to_show) {
                $otherbtc = $otherbtc + $arr['btcValue'];
                $othereur = $othereur + $eur;
            } else {
                $return['valuta'][$symbol] = array(
                    'market' => $symbol,
                    'qty'    => $arr['available'],
                    'btc'    => $arr['btcValue'],
                    'eur'    => $eur
                    );
            }
        }
    }
    if ($otherbtc) {
            $return['valuta']['Other'] = array(
                'market' => 'Other',
                'qty'    => '',
                'btc'    => $otherbtc,
                'eur'    => $othereur
                );
    }
    $return['totbtc'] = $totbtc;
    $return['toteur'] = $toteur;
    
    return $return;
}`

**Comment by eppenga** [comment]
Aaah thanks so much! Much better than my own crappy PHP :)

**Comment by J87NL** [comment]
I faced a similar issue with SHIB/BTC which doesn't exist and desiced to write another method for this:
```
    public function getForeignTotal(string $currentAsset, string $foreignAsset, float $amount, array $ticker): float
    {
        // No need to lookup a price in the $ticker if assets are BTC/BTC of USDT/USDT:
        $foreignValue = ($currentAsset === $foreignAsset) ? 1 : ($ticker[$currentAsset.$foreignAsset] ?? null);

        // If a price was found we can do a simple calculation:
        if (!empty($foreignValue)) {
            return $amount * $foreignValue;
        }

        // Some keys are the other way around:
        if (!empty($ticker[$foreignAsset.$currentAsset])) {
            return $amount / $ticker[$foreignAsset.$currentAsset];
        }

        // If the combinations aren't found, try converting them against some others:
        foreach (['BTC', 'USDT', 'EUR', 'GBP'] as $asset) {
            if (array_key_exists($currentAsset.$asset, $ticker) && array_key_exists($foreignAsset.$asset, $ticker)) {
                $foreignTotal = $this->getForeignTotal($currentAsset, $asset, $amount, $ticker);
                return round($foreignTotal / $ticker[$foreignAsset.$asset], 8);
            }
        }

        // It may be better to throw an exception here.
        return 0;
    }
```

I call it like this:

```
        $ticker =  $api->prices();
        $allBalances = $api->balances($ticker);

        $filteredBalances = array_filter($allBalances, function ($value) {
            return (!empty((float) $value['available']) || !empty((float) $value['onOrder']));
        });

        foreach ($filteredBalances as $asset => $value) {
            $balances[$asset] = [
                'available' => (float) $value['available'],
                'onOrder' => (float) $value['onOrder'],
            ];

            $total = $value['available'] + $value['onOrder'];

            $balances[$asset]['btcValue'] = $this->getForeignTotal($asset, 'BTC', $value['available'], $ticker);
            $balances[$asset]['btcTotal'] = $this->getForeignTotal($asset, 'BTC', $total, $ticker);

            $balances[$asset]['usdValue'] = $this->getForeignTotal($asset, 'USDT', $value['available'], $ticker);
            $balances[$asset]['usdTotal'] = $this->getForeignTotal($asset, 'USDT', $total, $ticker);

            $balances[$asset]['eurValue'] = $this->getForeignTotal($asset, 'EUR', $value['available'], $ticker);
            $balances[$asset]['eurTotal'] = $this->getForeignTotal($asset, 'EUR', $total, $ticker);
        }

        return $balances ?? [];
```

Please note that the total (`array_sum(array_column($balances, 'btcValue'))`) differs from `$api->btc_total`.

I hope I helped someone!

**Comment by ePascalC** [comment]
Added to FAQ : https://github.com/jaggedsoft/php-binance-api/wiki/FAQ#some-assets-like-kp3r-hot-hegic-do-not-give-a-btc-value-in-the-balance
