### ISSUE TITLE
PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in ***/binance/vendor/jaggedsoft/php-binance-api/php-binance-api.php on line 132

### ISSUE THREAD

**Issue by pachalaa** [jaggedsoft/php-binance-api#34]
Hello,

I tried to put a market buy with that code in a php file : 

'<?php
require 'vendor/autoload.php';
$api = new Binance\API("*****","*****");

$quantity = 0.001;
$order = $api->marketBuy("BTCUSDT", $quantity);
?>'

And I get this code error : 

PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in ****/binance/vendor/jaggedsoft/php-binance-api/php-binance-api.php on line 132
PHP Warning:  file_get_contents(): Failed to enable crypto in ****/binance/vendor/jaggedsoft/php-binance-api/php-binance-api.php on line 132
PHP Warning:  file_get_contents(https://api.binance.com/api/v3/order?symbol=BTCUSDT&side=BUY&type=MARKET&quantity=0.001&recvWindow=60000&timestamp=1516474442097&signature=**********): failed to open stream: operation failed in ****/binance/vendor/jaggedsoft/php-binance-api/php-binance-api.php on line 132

Do you have an idea to fix it ?
Thanks

**Comment by pachalaa** [comment]
I upgraded to PHP7.0 and now the error changed to : 

failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in ****/vendor/jaggedsoft/php-binance-api/php-binance-api.php on line 132

**Comment by jaggedsoft** [comment]
I cannot reproduce. But the new version shows friendlier error messages

**Comment by pachalaa** [comment]
I get the exact same error with the new version... I was so happy to find your project but so sad I can't use it...

**Comment by pachalaa** [comment]
New version working like a charm thank you !!!
