### ISSUE TITLE
Enhancement: Switching v1/ to v3/ ?

### ISSUE THREAD

**Issue by ePascalC** [jaggedsoft/php-binance-api#343]
Hi,
I see that some functions are still using v1. I'm not sure when Binance would start phasing those out, but would it be wise to start thinking to move them all to v3?
Questions I have in mind:
1. Of course each function needs to be checked to make sure it returns exactly the same. v1/time and v3/time are returning the same
2. Is there a difference in authentication? Anybody has documentation on differences between v1, v2 and v3?
3. Is there a difference in weight?

If we can brainstorm a bit, I can propose some changes. Thanks!

**Comment by dmzoneill** [comment]
Hi @ePascalC 

Feel free to setup a new v3 branch.
I pushed a php unit test branch 2 years ago.
It probably needs one or 2 changes.  but it can be used to validate your changes.
https://github.com/jaggedsoft/php-binance-api/tree/gh-travis

**Comment by ePascalC** [comment]
I started with #347 for time, useServerTime and exchangeInfo.

**Comment by dmzoneill** [comment]
https://github.com/jaggedsoft/php-binance-api/pull/347

merged. closing
