### ISSUE TITLE
historicalTrades should use trades if no tradeId is set

### ISSUE THREAD

**Issue by ePascalC** [jaggedsoft/php-binance-api#348]
v3/historicalTrades has a weight of 5
v3/trades has a weight of 1
See https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#recent-trades-list and just below

So function historicalTrades should use v3/trades if $fromTradeId = -1 and v3/historicalTrades if $fromTradeId has a value.

I might come up with a pull request later this week, but if anybody wants to add it, please go ahead!

**Comment by lgrassini** [comment]
This commit is causing an `undefined variable` notice on line 913 since `$fromTradeId` was renamed to `$tradeId` in the function parameter. I'm going to create a new PR fixing this later today.
