### ISSUE TITLE
HTTP request failed! HTTP/1.1 400 Bad Request

### ISSUE THREAD

**Issue by cosfat** [jaggedsoft/php-binance-api#35]
Today this problem started.

           $api = new Binance\API("xxx", "yyy");

		$quantity = 1;

		$price = 0.0006;

		$api->sell("ARKBTC", $quantity, $price);`

Gives the below error code:

> Message: 'file_get_contents(https://api.binance.com/api/v3/order?symbol=ARKBTC&side=SELL&type=LIMIT&quantity=1&recvWindow=60000&price=0,0006&timeInForce=GTC&timestamp=1516659076390&signature=283e234a746f283e47fd6c283ca82734628734d6283746a2f8d374f627a8346e272c3): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request '

**Comment by jaggedsoft** [comment]
Hmm, someone else reported a similar issue. I would like to modify this library a bit to have better error handling and show more detail

**Comment by cosfat** [comment]
@jaggedsoft would you give us some suggest for temporarily handling the issue?

**Comment by cosfat** [comment]
SOLVED!

`
	public function order($side, $symbol, $quantity, $price, $type = "LIMIT", $flags = []) {
		$opt = [
			"symbol" => $symbol,
			"side" => $side,
			"type" => $type,
			"quantity" => $quantity,
			"recvWindow" => 10000
		];
		if ( $type == "LIMIT" ) {
			$opt["price"] = $price;
			$opt["timeInForce"] = "GTC";
		}
		if ( isset($flags['stopPrice']) ) $opt['stopPrice'] = $flags['stopPrice'];
		if ( isset($flags['icebergQty']) ) $opt['icebergQty'] = $flags['icebergQty'];
		return $this->signedRequest("v3/order", $opt, "POST");
	}`

Changing **recvWindow** from 60000 to 10000 just works like a charm.

**Comment by jaggedsoft** [comment]
Thanks!
Good to know, will add nice error messages to future versions
This happens when system time goes out of sync
I can also add a useServerTime option

**Comment by dxjones** [comment]
By the way, it should be documented somewhere that people running this code
should run NTP on their machine to avoid clock drift relative the the
binance server.

**Comment by jaggedsoft** [comment]
Thank you!!

Added error messages in `v0.0.11` https://github.com/jaggedsoft/php-binance-api/commit/ed531e66f9b1aae4a9de3967136bb094c4cc0ffb

Will add 'useServerTime' in future version. For now, increase recvWindow or synchronize clock
