### ISSUE TITLE
Readme.md Add to PHP Version

### ISSUE THREAD

**Issue by muratcakmaksoftware** [jaggedsoft/php-binance-api#360]
Can you add the stable php version information.
php 7.3 also works for me.

**Comment by dmzoneill** [comment]
Hi @muratcakmaksoftware 

Pull requests are welcome if you would like to contribute

https://github.com/jaggedsoft/php-binance-api/blob/0958e2e96f230b103ce31992701e478ae5805ad7/php-binance-api.php#L18
