### ISSUE TITLE
binance.us

### ISSUE THREAD

**Issue by macmiller** [jaggedsoft/php-binance-api#362]
**Title**
- feature: binance.us support

**Short Description:**
- BINANCE.US
  
**php version:**
- 7.0.24

**Long descrption**
- All I did was change line 32 in php-binance-api.php to
- 'https://api.binance.us/api' ....
and everything worked fine.  It can be a little confusing as I thought it might work with binance.us out of the box. 

    protected $base = 'https://api.binance.us/api/'; // /< REST endpoint for the currency exchange
thank you

**Comment by dmzoneill** [comment]
its the same data center

![image](https://user-images.githubusercontent.com/15192260/114313419-5db57880-9aee-11eb-8b91-a229e8c7a4de.png)

**Comment by macmiller** [comment]
Just to make sure to clarify the issue, when getting the API key you need to go to the binance.com or binance.us website depending where your account is.  For US citizens they can't open an account on binance.com.  If your keys are located on the binance.us server, then there will be a problem using the api scripts as is as you will get an unauthorized message as it is looking for the scripts on binance.com and not binance.us.  Otherwise the code works on either system as is, only the URL needs to be tweaked.

**Comment by ePascalC** [comment]
@macmiller is the API really the same on both platforms, no differences? Have you tried multiple API commands to make sure they all work, also wapi/sapi/stream?

**Comment by macmiller** [comment]
I am using the api with no changes but mostly just to get bitcoin price.  Also tried some test calls, eg time.  
main code I am using        $binance_api = new Binance\API($this->auth_binance_read[0],$this->auth_binance_read[1]);
        $ret = $this->binance_api->price("BTCUSD");
It works (with binance.us)  --  :)  Not doing anything more for now as I am just using this function and it does what I need.  I may try more later.  Thanks

    On Tuesday, April 13, 2021, 01:38:27 AM GMT+7, ePascalC ***@***.***> wrote:  
 
 


@macmiller is the API really the same on both platforms, no differences? Have you tried multiple API commands to make sure they all work, also wapi/sapi/stream?

**Comment by macmiller** [comment]
bad assumption ---> Otherwise the code works on either system as is (should say works for price function as it is all that I have really used)

**Comment by ePascalC** [comment]
Added this into our FAQ: https://github.com/jaggedsoft/php-binance-api/wiki/FAQ#can-i-use-this-php-library-for-binanceus
