### ISSUE TITLE
User data stream

### ISSUE THREAD

**Issue by AliAlican** [jaggedsoft/php-binance-api#365]
**I am not able to get the trigger conditions from this data stream**

Is there any way we can update the datastream to v3, or is there any other way to get the stopprice in this data stream?
  
@cobianzo

thank you

**Comment by cobianzo** [comment]
Hi AliAlican 
I abandoned this project time ago. I just cloned and used it in a couple of simple projects. I had to create some functions myself as it was incomplete. Next time, I'll probably use a nodejs API.
