### ISSUE TITLE
Question: Is this API wrapper compatible with Binance.US API?

### ISSUE THREAD

**Issue by sm4rtk1dz** [jaggedsoft/php-binance-api#366]
So I have this simple question that someone may know, Is this API wrapper compatible with Binance.US API?
I mean, if I change the endpoints, would it work? or it's something completely different?

**Comment by ePascalC** [comment]
@sm4rtk1dz Please see https://github.com/jaggedsoft/php-binance-api/issues/362
Some parts might be working, but not sure if it will all work.
Please test and let us know!
