### ISSUE TITLE
MIN_NOTIONAL

### ISSUE THREAD

**Issue by graz68a** [jaggedsoft/php-binance-api#367]
**Short Description:**
- Unable to sell a 
  
**Platform:**
- linux

**php version:**
- 7.0.24

**Long descrption**
If I try to buy suing API I have no problem

for example

``php
$quantity="25";
$order = $api->marketBuy("CHRUSDT", $quantity);
print_r($order);
```

If I try to sell the same quantity (once bought) using this

``php
$quantity="25";
$order = $api->marketSell("CHRUSDT", $quantity);
print_r($order);
```
I receive this error
Fatal error: Uncaught Exception: signedRequest error: {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"} in /home/william/public_html/coin/vendor/jaggedsoft/php-binance-api/php-binance-api.php:1224 Stack trace: #0 /home/william/public_html/coin/vendor/jaggedsoft/php-binance-api/php-binance-api.php(1301): Binance\API->httpRequest('v3/order', 'POST', Array, true) #1 /home/william/public_html/coin/vendor/jaggedsoft/php-binance-api/php-binance-api.php(450): Binance\API->order('SELL', 'CHRUSDT', 25, '0.00000000', 'MARKET', Array) #2 /home/william/public_html/coin/vendor/jaggedsoft/php-binance-api/bot7/bot7.php(34): Binance\API->marketSell('CHRUSDT', 25) #3 {main} thrown in /home/william/public_html/coin/vendor/jaggedsoft/php-binance-api/php-binance-api.php on line 1224

Any idea why cannot I sell ?

**Comment by graz68a** [comment]
do the problem happens because min order should be .001 BTC ( or 60 USDT ? )  Is it the limit only to sell (because I was able to buy 25 CHR) ?

**Comment by ePascalC** [comment]
@graz68a can you please explain what you want to do?
1) Do you want to buy 25 CHR, so for an amount of 9.78 USDT?
2) or you wanted to buy CHR for a total of 25 USDT?

**Comment by graz68a** [comment]
Thank you all, I solved , the problem was that CHR was less than minimal of 10 USDT

**Comment by gnzlst** [comment]
@ePascalC, can you please elaborate a bit further on how to buy for a total of 25 USDT using marketQuoteBuy()?

In this case the $quantity is 25 USDT?

**Comment by ePascalC** [comment]
@gnzlst marketQuoteBuy only has 2 mandatory parameters: symbol and quantity. So if you want to buy BTC for a max of 25 USDT, you would do marketQuoteBuy('BTCUSDT',25) and you will see that you have bought about 0.000647 BTC for 24.998765 USDT.
Hope that clarifies.

**Comment by gnzlst** [comment]
@ePascalC Thanks man. That clarifies it.

**Comment by gnzlst** [comment]
Hi, I succeeded buying using marketQuoteBuy, thanks.

Now I am trying to sell the same quantity bought and I am getting this error.
`signedRequest error: {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}`

The data that I am passing is: 
`[Ticker] => BTGUSDT, [Quantity] => 0.136, [Price] => 74.074, [Type] => STOP_LOSS_LIMIT, [StopPrice] => 71.851`

The MIN_NOTIONAL from exchangeInfo is: 10.00000000

The result of Price x Quantity is: 10.074064

Which is higher than the MIN_NOTIONAL. I know it is just a little bit higher, but it shouldn't be a problem, should it?

I sold the units from Binance website for an even lower amount:

73.900 x 0.136 = 10.0504

I've browsed other issues, but I haven't found anything like that. Can you think of any other reason of this?

Thanks in advance!

**Comment by gnzlst** [comment]
I think I got it. The STOP_LOSS_LIMIT order was not passing the filter. We need to consider both orders to pass the filter.
