### ISSUE TITLE
Fatal error: Default value for parameters with a class type hint can only be NULL in

### ISSUE THREAD

**Issue by allaf2** [jaggedsoft/php-binance-api#368]
Fatal error: Default value for parameters with a class type hint can only be NULL in
vendor/jaggedsoft/php-binance-api/php-binance-api.php on line 60

my code is :

require 'vendor/autoload.php';

$apiKey =      "my api ";
$secretKey = "my secret key";

$api = new Binance\API($apiKey,$secretKey);

$api->chart(["BNBBTC"], "15m", function($api, $symbol, $chart) {
	echo "{$symbol} chart update\n";
	print_r($chart);
});

i want to test web socket. what's the problem

**Comment by ePascalC** [comment]
That should be the PHP8 error. It was fixed already. If not, please get back to us.
