### ISSUE TITLE
Seperating a symbol

### ISSUE THREAD

**Issue by AliAlican** [jaggedsoft/php-binance-api#369]
Hello is there anyway to separate a binance symbol into two coins?

**Comment by ePascalC** [comment]
@AliAlican please check $api->exchangeInfo. You will find there the base asset and the quote asset.
![image](https://user-images.githubusercontent.com/18325208/115264215-63d2d700-a136-11eb-9f22-692e1e0cfad4.png)

**Comment by AliAlican** [comment]
Thank you very much this works perfectly fine
