### ISSUE TITLE
HOT , DENT - Wrong btcValue or btcTotal

### ISSUE THREAD

**Issue by dobrildobrilov** [jaggedsoft/php-binance-api#370]
Hello

HOT , DENT and probably other coins show wrong btcValue or btcTotal than this what is visible on WEB.

    $ticker = $api->prices();
    $balances = $api->balances($ticker);
    echo ($balances['HOT']['btcValue']);

**Comment by ePascalC** [comment]
Hi @dobrildobrilov , technically speaking the '0' that you get is correct as there is no HOT_BTC symbol, so it cannot give you a btc value.
I have shown in https://github.com/jaggedsoft/php-binance-api/issues/339 how I created my own wallet that will look for e.g, HOTUSDT and then use the BTCUSDT to give you an approximate value for those assets without BTC.
Hope it helps.

**Comment by dobrildobrilov** [comment]
Unfortunately I am not getting 0 as value but some value with is probably 5-7times less than this what I can see in WEB

**Comment by ePascalC** [comment]
See FAQ https://github.com/jaggedsoft/php-binance-api/wiki/FAQ#some-assets-like-kp3r-hot-hegic-do-not-give-a-btc-value-in-the-balance
