### ISSUE TITLE
How to get some trend information

### ISSUE THREAD

**Issue by graz68a** [jaggedsoft/php-binance-api#371]
**Title**
how to get symbol trend details 

Is there any way to get some trend detail information from Binance using php binance.

I know I can get  24hr symbol price change for example

```
$prevDay = $api->prevDay("BTCUSDT");
print_r($prevDay);
echo "BTCUSDT price change since yesterday: ".$prevDay['priceChangePercent']."%".PHP_EOL;
```

but If I would know more about the BTCUSDT trend in latest 6 hours is it possible ?  

Thank you

**Comment by ePascalC** [comment]
Hi @graz68a, you would probably need to go with the hourly candles or so. Check the example on https://github.com/jaggedsoft/php-binance-api/blob/master/examples/candles.php

**Comment by graz68a** [comment]
Thank you  ,  it was really useful . Do you know if there are rate limits , for example can I execute

$ticks = $api->candlesticks("ARPAUSDT", "1m");

all day each 6 seconds ?

**Comment by ePascalC** [comment]
If you run $api->exchangeInfo you will find your rate limits, most probably 1200 per minute.
Using the standard API for candlesticks like you show above has a weight of 1 (see https://binance-docs.github.io/apidocs/spot/en/#kline-candlestick-data), but if you want to get candlesticks constantly you better use a websocket (no weight) like https://binance-docs.github.io/apidocs/spot/en/#kline-candlestick-streams

**Comment by graz68a** [comment]
thank you ePascalC .

**Comment by graz68a** [comment]
ok I think you are talking about this

```
$api->miniTicker(function($api, $ticker) {
	print_r($ticker);
})
```

BTW 

```
$info = $api->exchangeInfo;
print_r($info);
```

returns nothing to me

**Comment by graz68a** [comment]
I received this

```
rateLimitType => REQUEST_WEIGHT
interval => MINUTE
intervalNum => 1
limit => 1200
```

does it mean that I have a limit of 1200 API requests per minute ? It seems a lot

**Comment by ePascalC** [comment]
> does it mean that I have a limit of 1200 API requests per minute ? It seems a lot
You have 1200 credits. Your candlesticks call is weight 1, but others have weight 5, 10, 40, etc. Depending on what you request the API, you will consume a different number of credits per call.
