### ISSUE TITLE
cpripto values conversion

### ISSUE THREAD

**Issue by graz68a** [jaggedsoft/php-binance-api#373]
Hello

is it possible to know USDT value of any other crypto using php binance API ?

For example I would know how many ADA are 100 USDT , can I do this with php binance API ?

Thank you

**Comment by ePascalC** [comment]
$api->price('ADAUSDT') gives you the current price.

**Comment by graz68a** [comment]
sorry , I already  know it , shame on me.
My question was the contrary ,   I would know how many USDT are 100 CHR 
or how many EUR are  100 CHR . Is it possible ?

**Comment by graz68a** [comment]
I found alternative way using this remote service , don't know if I could do the same with php binance

```

$valutax=str_replace("USDT","",$pair);
$url = "https://min-api.cryptocompare.com/data/price?fsym=USDT&tsyms=$valutax";
$res_pair = file_get_contents($url);
# {"CHR":3.475}
$res_pair = str_replace("{\"$valutax\":","",$res_pair);
$res_pair = str_replace("}","",$res_pair);
```

**Comment by graz68a** [comment]
Hello

cryptocompare.com stopped to provide me values (I should have surpassed the limit ) , there is no way to 
reiceve this data using php binance  ( e.g. I would know how many USDT are 100 CHR  using php binance api )?

**Comment by ePascalC** [comment]
Hi @graz68a,
$unitprice = $api->price('CHRUSDT'); // this is 1 CHR in USDT
$hundredCHRinUSDT = 100 * $unitprice;

**Comment by graz68a** [comment]
Thank you !
