### ISSUE TITLE
Typo error 'tickerStreamHandler' instead of 'executionHandler'

### ISSUE THREAD

**Issue by ikaler** [jaggedsoft/php-binance-api#379]
https://github.com/jaggedsoft/php-binance-api/blob/0958e2e96f230b103ce31992701e478ae5805ad7/php-binance-api.php#L1506

In the above line, it should be '**executionHandler**' instead of '**tickerStreamHandler**'

**Comment by ePascalC** [comment]
Fixed, thanks.
