### ISSUE TITLE
Change End Point

### ISSUE THREAD

**Issue by nrtszr** [jaggedsoft/php-binance-api#380]
i want to change url binance api

The base endpoint is: https://www.trbinance.com

how it is?

**Comment by nrtszr** [comment]
i want to change binance to trbinance.com

https://www.trbinance.com/apidocs/#api-document-description

**Comment by ePascalC** [comment]
Hi @nrtszr, the documentation is mentioning the standard api at binance.com, so no changes needed, everything should work.
HOWEVER further down on that API documentation page it is referring to binance.cc ???
So please be careful in proceeding!

**Comment by nrtszr** [comment]
i get binance api code to work
but i get trbinance.com api code don't work 


PHP Fatal error:  Uncaught Exception: signedRequest error: {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."} in D:\xampp\htdocs\binance\vendor\jaggedsoft\php-binance-api\php-binance-api.php:1224
Stack trace:
#0 D:\xampp\htdocs\binance\vendor\jaggedsoft\php-binance-api\php-binance-api.php(1301): Binance\API->httpRequest('v3/order', 'POST', Array, true)
#1 D:\xampp\htdocs\binance\vendor\jaggedsoft\php-binance-api\php-binance-api.php(247): Binance\API->order('BUY', 'BNBTRY', 1, '1.00000000', 'LIMIT', Array)
#2 D:\xampp\htdocs\binance\test.php(46): Binance\API->buy('BNBTRY', 1, 1)
#3 {main}
  thrown in D:\xampp\htdocs\binance\vendor\jaggedsoft\php-binance-api\php-binance-api.php on line 1224

Fatal error: Uncaught Exception: signedRequest error: {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."} in D:\xampp\htdocs\binance\vendor\jaggedsoft\php-binance-api\php-binance-api.php:1224
Stack trace:
#0 D:\xampp\htdocs\binance\vendor\jaggedsoft\php-binance-api\php-binance-api.php(1301): Binance\API->httpRequest('v3/order', 'POST', Array, true)
#1 D:\xampp\htdocs\binance\vendor\jaggedsoft\php-binance-api\php-binance-api.php(247): Binance\API->order('BUY', 'BNBTRY', 1, '1.00000000', 'LIMIT', Array)
#2 D:\xampp\htdocs\binance\test.php(46): Binance\API->buy('BNBTRY', 1, 1)
#3 {main}
  thrown in D:\xampp\htdocs\binance\vendor\jaggedsoft\php-binance-api\php-binance-api.php on line 1224

**Comment by nrtszr** [comment]
php .\al-sat.php
PHP Fatal error:  Uncaught Exception: signedRequest error: {"code":403,"msg":"unauthorized","timestamp":1619971506844} in D:\xampp\htdocs\al-sat\vendor\jaggedsoft\php-binance-api\php-binance-api.php:1224
Stack trace:
#0 D:\xampp\htdocs\al-sat\vendor\jaggedsoft\php-binance-api\php-binance-api.php(1301): Binance\API->httpRequest('v3/order', 'POST', Array, true)
#1 D:\xampp\htdocs\al-sat\vendor\jaggedsoft\php-binance-api\php-binance-api.php(247): Binance\API->order('BUY', 'VETTRY', 12, '3.14100000', 'LIMIT', Array)
#2 D:\xampp\htdocs\al-sat\al-sat.php(7): Binance\API->buy('VETTRY', 12, 3.141)
#3 {main}
  thrown in D:\xampp\htdocs\al-sat\vendor\jaggedsoft\php-binance-api\php-binance-api.php on line 1224

Fatal error: Uncaught Exception: signedRequest error: {"code":403,"msg":"unauthorized","timestamp":1619971506844} in D:\xampp\htdocs\al-sat\vendor\jaggedsoft\php-binance-api\php-binance-api.php:1224
Stack trace:
#0 D:\xampp\htdocs\al-sat\vendor\jaggedsoft\php-binance-api\php-binance-api.php(1301): Binance\API->httpRequest('v3/order', 'POST', Array, true)
#1 D:\xampp\htdocs\al-sat\vendor\jaggedsoft\php-binance-api\php-binance-api.php(247): Binance\API->order('BUY', 'VETTRY', 12, '3.14100000', 'LIMIT', Array)
#2 D:\xampp\htdocs\al-sat\al-sat.php(7): Binance\API->buy('VETTRY', 12, 3.141)
#3 {main}
  thrown in D:\xampp\htdocs\al-sat\vendor\jaggedsoft\php-binance-api\php-binance-api.php on line 1224

**Comment by demironur** [comment]
anyone find a solution to use trbinance api? i use https://api.binance.cc/api/v3 base url but still it does not work

**Comment by ePascalC** [comment]
@demironur I don't think we will be able to help you here, sorry. The API documentation on trbinance is not really clear. It gives examples like https://api.binance.cc/api/v3/depth but then also https://www.trbinance.com/open/v1/orders. I would suggest to try to get support directly from trbinance to get more information.

**Comment by demironur** [comment]
After trying couple days i am able to call trbinance api. In short, https://www.trbinance.com is for account spesific calls,  https://api.binance.cc/api/v3/ is for public calls. Also both expected and returned parameters are different from binance api.
