### ISSUE TITLE
Can I pass in variable API details?

### ISSUE THREAD

**Issue by CoinStacker** [jaggedsoft/php-binance-api#386]
Can I pass in variable API details?

Basically I want to be able to variably pass in the api_secret and api_key into the API class in php_binance-api.php . Currently ofcourse if you try and do this with a $_SESSSION variable for example you get the error **"Constant expression contains invalid operations"**.

I've left out a long description and some of the other fields because this isn't really a bug and hence some of the other info isn't too relevant I'm just wondering if anyone has any suggestions on how I could do this?

Look forward to hearing from you and thank you so much for the project.

CoinStacker Team

**Comment by dmzoneill** [comment]
Hi,

Could you kindly take a moment to review the construtor

https://github.com/jaggedsoft/php-binance-api/blob/dc8e6fd34cc305888a3c68f03013da49f9d797fd/php-binance-api.php#L77

note the default case in the switch statement.

**Comment by CoinStacker** [comment]
> Hi,
> 
> Could you kindly take a moment to review the construtor
> 
> https://github.com/jaggedsoft/php-binance-api/blob/dc8e6fd34cc305888a3c68f03013da49f9d797fd/php-binance-api.php#L77
> 
> note the default case in the switch statement.

@dmzoneill thank you so much for this. I should have been able to find it myself but I can't say i'm surprised I missed it.

**Comment by dmzoneill** [comment]
no problem
