### ISSUE TITLE
$limit is undefined, line 2666

### ISSUE THREAD

**Issue by blounolito** [jaggedsoft/php-binance-api#387]
**Title**
- bug: $limit in not defined

**Short Description:**
- function accountSnapshot(), when $startTime is defined, line 2666 will throw a notice ($limit not defined)
  
**Platform:**
- all

**php version:**
- whatever

**Comment by dmzoneill** [comment]
Pleas feel free to commit a fix if you would like to contribute

**Comment by ePascalC** [comment]
Well spotted, thanks!
Changed
        if ($nbrDays != 5)
            $params['limit'] = $limit;
To
        if ($nbrDays != 5)
            $params['limit'] = $nbrDays;
