### ISSUE TITLE
GET datas from server return 0 results

### ISSUE THREAD

**Issue by matthieugluszkowski** [jaggedsoft/php-binance-api#389]
GET datas from server return 0 results
I am doing this request : 
$api->candlesticks("GRTUSDT", "1h",1500,"1620241032000");
When I launch it from my localhost I get all the results

Array
(
    [1038529408] => Array
        (
            [open] => 1.53987
            [high] => 1.55667
            [low] => 1.53950
            [close] => 1.55636
            [volume] => 2063176.44882
            [openTime] => 1620241200000
            [closeTime] => 1620244799999
            [assetVolume] => 1332715
            [baseVolume] => 2063176.44882
            [trades] => 5943
            [assetBuyVolume] => 644728
            [takerBuyVolume] => 998211.01491
            [ignored] => 0
        )...

WHen I launch the same script from my own web server I get 0 result : 
Array
(
)

I have no error, just 0 result, someone has an idea?

thank you in advance!

**Comment by ePascalC** [comment]
@matthieugluszkowski limit is 1000, not 1500. Can you please try with 1000 ?
