### ISSUE TITLE
Buy with max available USDT

### ISSUE THREAD

**Issue by noorburki** [jaggedsoft/php-binance-api#397]
i want to buy with max available USDT. 

For example i have 50USDT.
and want to buy BNB when price is 350usdt of all available USDT.
How can i do this?

And same with sell order.
when i want to sell all BNB at a specific 

```php
require 'vendor/autoload.php';
$api = new Binance\API("<api key>","<secret>");
$price = 350;
$order = $api->buy('BNBUSDT',  MAXPOSSIBLE, $price);
Sell Order
$order = $api->sell('BNBUSDT',  MAX, $price);
```

thank you

**Comment by noorburki** [comment]
Another issue that i am facing is with stoploss:  

`$order = $api->sell('BNBBUSD', '0.05003872', 370, "STOP_LOSS_LIMIT", ["stopPrice"=>369]);`

this create error saying Uncaught Exception: signedRequest error: {"code":-1013,"msg":"Filter failure: LOT_SIZE"}

**Comment by over12** [comment]
I am in the same situation, I do not want to inform the amount but use my total USD account balance.

Does this action by the Binance platform exist, by the api too?

**Comment by seyitahmettanriver** [comment]
I searching ..
