### ISSUE TITLE
Opentime gets corrupted

### ISSUE THREAD

**Issue by mnording** [jaggedsoft/php-binance-api#4]
The putting the opentime as they array key does not work.  The value gets corrupted when trying to read the associative array using foreach($res as $key => $val)

Suggestion to add opentime as a value on the object instead

**Comment by jaggedsoft** [comment]
Thank you for the report! Could you please give me an example? I will be happy to fix this

**Comment by mnording** [comment]
Below is what is being returned from binance API
array(12) {
    [0]=>
    float(1511222400000)
    [1]=>
    string(10) "0.00001411"
    [2]=>
    string(10) "0.00006000"
    [3]=>
    string(10) "0.00000530"
    [4]=>
    string(10) "0.00001134"
    [5]=>
    string(18) "131643905.00000000"
    [6]=>
    float(1511308799999)
    [7]=>
    string(13) "1501.35973280"
    [8]=>
    int(17125)
    [9]=>
    string(17) "51362850.00000000"
    [10]=>
    string(12) "598.94269991"
    [11]=>
    string(18) "181700088.01121959"
  }

Here is what is being returned by the chartData method

array(5) {
    ["open"]=>
    string(10) "0.00001411"
    ["high"]=>
    string(10) "0.00006000"
    ["low"]=>
    string(10) "0.00000530"
    ["close"]=>
    string(10) "0.00001134"
    ["volume"]=>
    string(13) "1501.35973280"
  }
