### ISSUE TITLE
View orders for all currencies

### ISSUE THREAD

**Issue by EraldoOkado** [jaggedsoft/php-binance-api#405]
How do I display all order history for all currencies?

**Comment by ePascalC** [comment]
@EraldoOkado So far I did not find any call to Binance to do this. You can only do it symbol per symbol:
$api->history("BNBBTC");

**Comment by EraldoOkado** [comment]
I got the solver, creating a new array with the symbols of the coins I wanted, and I pass a foreach, but the application is very heavy, and loading takes about 30s.

**Comment by ePascalC** [comment]
@EraldoOkado just be careful not to go over the 1200 credits per minute or you could get your account locked

**Comment by seyitahmettanriver** [comment]
> @EraldoOkado just be careful not to go over the 1200 credits per minute or you could get your account locked

`1200 credits`  what is this ?

**Comment by ePascalC** [comment]
@seyitahmettanriver check exchangeInfo to find your limits:
https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#general-info-on-limits
