### ISSUE TITLE
WAPI will be discontinued

### ISSUE THREAD

**Issue by h-rafiee** [jaggedsoft/php-binance-api#408]
**Move to SAPI**
- feature: Please change all wapi to sapi version as documents said

**Short Description:**

A [binance API docs](https://binance-docs.github.io/apidocs/spot/en/#change-log) said On August 01, 2021 02:00 AM UTC the WAPI endpoints will be discontinued:
- GET /wapi/v3/systemStatus.html
- POST /wapi/v3/withdraw.html
- GET /wapi/v3/depositHistory.html
- GET /wapi/v3/withdrawHistory.html
- GET /wapi/v3/depositAddress.html
- GET /wapi/v3/accountStatus.html
- GET /wapi/v3/apiTradingStatus.html
- GET /wapi/v3/userAssetDribbletLog.html
- GET /wapi/v3/assetDetail.html
- GET /wapi/v3/tradeFee.html
- GET /wapi/v3/sub-account/list.html
- GET /wapi/v3/sub-account/transfer/history.html
- POST /wapi/v3/sub-account/transfer.html
- GET /wapi/v3/sub-account/assets.html
 

thank you

**Comment by ePascalC** [comment]
#363 is already opened for that.
