### ISSUE TITLE
Manditory timeInForce missing on STOP_LOSS_LIMIT order

### ISSUE THREAD

**Issue by LollyLover** [jaggedsoft/php-binance-api#41]
Hi,

I get the following error

signedRequest error: {"code":-1102,"msg":"Mandatory parameter 'timeInForce' was not sent, was empty/null, or malformed."}

When I try and do a stop loss order.

$order = $api->sell($pair, $newleftbalance, $stop, "STOP_LOSS_LIMIT", ["stopPrice"=>$stopprice]);

Any suggestions?

Thanks Steve

**Comment by 0dark0** [comment]
Here is a quick fix while waiting for jaggedsoft
Replace line 186 with this
if ( $type == "LIMIT" || $type == "STOP_LOSS_LIMIT") {

**Comment by jaggedsoft** [comment]
Thanks for the report :+1:

**Comment by jaggedsoft** [comment]
resolved in `v0.0.14` https://github.com/jaggedsoft/php-binance-api/commit/be2bb60742abea3ec304cf78df50e301723d7d6c
