### ISSUE TITLE
Not working for me "Invalid API-key, IP, or permissions for action

### ISSUE THREAD

**Issue by kizinho** [jaggedsoft/php-binance-api#419]
Exception
signedRequest error: {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}

IP access restrictions:
Unrestricted (Less Secure)  enabled

Enable Spot & Margin Trading

Enable Reading

help me after all this still getting errors

**Comment by ePascalC** [comment]
@kizinho , you will need to give a bit more information if you want help.
What command did you use? Can you share a piece of code (of course removing part of your API keys)

**Comment by kizinho** [comment]
$api = new Binance\API('api key', "secret key", true);
            $ticker = $api->prices();
            $balances = $api->balances($ticker);
            dd($balances);

**Comment by ePascalC** [comment]
Please check https://github.com/jaggedsoft/php-binance-api/wiki/Errors#-2015--invalid-api-key-ip-or-permissions-for-action

**Comment by mahdi4187** [comment]
add testnet to false this line 

`$api = new Binance\API('api key', "secret key", false);`
