### ISSUE TITLE
Uncaught TypeError: Return value of Binance\API

### ISSUE THREAD

**Issue by billydimitrov** [jaggedsoft/php-binance-api#422]
Uncaught TypeError: Return value of Binance\API

Just trying to migrate from old version of the class, because of the future Binance API changes at the end of the month.

Trying to use the current class no matter using php5 or 7 getting this fatal error. 

 Fatal error: Uncaught TypeError: Return value of Binance\API::setXMbxUsedWeight() must be an instance of Binance\void, none returned in
...
php-binance-api.php(1339): Binance\API->setXMbxUsedWeight(2) #1
...
php-binance-api.php(936): Binance\API->httpRequest('v3/ticker/price') #2
...
php-binance-api.php on line 2725

Using just the example as is

![image](https://user-images.githubusercontent.com/32612575/126609729-f7e14705-a728-48dc-9d38-4248dc6a179d.png)

the old version works perfect for me with all the futures without any issues.

thank you!

P.S. I found that is php version issue. Working with 7.2

Is it have any option to update the old version of the class working with php5 (because of the project) and just update for the removed futures?

**Comment by dmzoneill** [comment]
Hi,

Your excerpt is not complete, so its hard for me to determine whether this is an error with the code or as error in your code.
I believe you have removed lines as i can't find the specific function from where the error was thrown.

Assuming its your code for the moment. 
If you look at the code documentation, you will notice a number of them have 
@throws \Exception (example below).

Its up to you to capture the exception., using rry/catch
https://www.php.net/manual/en/language.exceptions.php

` /**
     * aggTrades get Market History / Aggregate Trades
     *
     * $trades = $api->aggTrades("BNBBTC");
     *
     * @param $symbol string the symbol to get the trade information for
     * @return array with error message or array of market history
     * @throws \Exception
     */`

**Comment by ePascalC** [comment]
@billydimitrov so if I understand correctly, it works on PHP 7.2?
For PHP 5, sorry but that is no longer supported.
What version of PHP 7 did you install where it did not work?

**Comment by billydimitrov** [comment]
Confirmed its not work on 7.1. First I saw in the file that its supported 7.0, but its work correct with 7.2. Without any problems. Can I receive the last version that support php 5?

**Comment by billydimitrov** [comment]
For this of you who cant migrate to php 7 but need to update binance changes from 1/8/21. I just make compatible php5 version of the class with the new changes. Anyone who need it can write me here or on telegram @billydimitrov
