### ISSUE TITLE
Bug: miniTicker doesn't work

### ISSUE THREAD

**Issue by piusidev** [jaggedsoft/php-binance-api#423]
Hello! Is my first time here, i have a problem with miniTicker.

**Platform:**
- linux

**php version:**
- 7.3.29

miniTicker does not respond, it just shows the pending status and nothing more, no log or anything like that. I even need to restart apache after that, because nothing else works correctly.

I tried see the logs in ```tail -f /var/log/apache2/error.log```, but is empty

**Code**
```php
$api->miniTicker(function($api, $ticker) {
    print_r($ticker);
});
```

**Response after JavaScript request**
```php
(pending)
```

**Comment by dmzoneill** [comment]
hi,

Can you run your code without Apache, such as

php yourscript.php 

provide further details.and provide a code excerpt.
thank you

**Comment by piusidev** [comment]
Without success, the solution i found is use the Websocket instead HTTP.
