### ISSUE TITLE
Bug: can't see open orders

### ISSUE THREAD

**Issue by piusidev** [jaggedsoft/php-binance-api#428]
I have buy some MARKET and LIMIT orders, but the openOrders return is empty.
  
**Platform:**
Ubuntu 20.04

**PHP Version:**
- 7.3.29

I call the openOrders endpoint but the return is empty, i have buy some orders in MARKET and LIMIT types, but i can't see this orders in openOrders.

I maked one loop for get all tickers and make one openOrder request for each ticker available, and all return empty. 

PS: When i call all orders an a ticker, that work perfectly.

**Code**
```php
$ticker = $_GET["ticker"];
$openorders = $api->openOrders($ticker);
echo json_encode($openorders);
```

**Result**
```
{
   []
}
```

Thanks

**Comment by ePascalC** [comment]
@piusidev Can you give an example of what $ticker contains?

**Comment by piusidev** [comment]
@ePascalC in $ticker variable only have a string with the ticker, example: BNBUSDT

**Comment by ePascalC** [comment]
@piusidev Correct me if I'm wrong, but I think a market order is never open. You launch it and it gets filled immediately (except special circumstances), so you will almost never see it in the open orders. Could that be your issue?

**Comment by piusidev** [comment]
@ePascalC Yep, probabily can be, but this happen with limit orders too, see this test order what i opened now:

```js
clientOrderId: "xxxxxx"
cummulativeQuoteQty: "26.37347200"
executedQty: "359.90000000"
fills: [{…}]
orderId: 741
orderListId: -1
origQty: "359.90000000"
price: "0.07328000"
side: "BUY"
status: "FILLED"
symbol: "TRXUSDT"
timeInForce: "GTC"
transactTime: 1628727827012
type: "LIMIT"
```

you have any idea why this happens?

**Comment by ePascalC** [comment]
@piusidev from the example, your status is 'Filled'. Open orders are orders that have been placed on the market but have yet to be filled. So if your order is in 'filled' state, it is not open and so you will not see it in the 'open' orders.
