### ISSUE TITLE
How can we use it for other TLD's such as .US ?

### ISSUE THREAD

**Issue by Prahapp** [jaggedsoft/php-binance-api#431]
Hello,

on Python library it is possible to pass tld and work with other tlds 

Would it be possible to implement to this wrapper ? 

https://python-binance.readthedocs.io/en/latest/overview.html#using-a-different-tld

**Comment by ePascalC** [comment]
Hi @Prahapp, see the discussion in #362
We are unsure if ALL functions work at 100%, but all basic functions seem to work by just changing binance.com to binance.us in the toplines of the code.
Please report back if any function would not work, thanks!

**Comment by ePascalC** [comment]
Added to FAQ https://github.com/jaggedsoft/php-binance-api/wiki/FAQ#can-i-use-this-php-library-for-binanceus
