### ISSUE TITLE
depthCache websocket error

### ISSUE THREAD

**Issue by mrsantran** [jaggedsoft/php-binance-api#44]
Bid price great than Ask price

![screen shot 2018-01-28 at 8 54 40 pm](https://user-images.githubusercontent.com/21286108/35482884-dfbc8af0-046d-11e8-95d4-0b089d68829b.png)

**Comment by jaggedsoft** [comment]
Having trouble seeing what is going wrong here

**Comment by mrsantran** [comment]
Many times return bids price great than asks price

**Comment by jaggedsoft** [comment]
I cannot reproduce this problem
Try using this code, this will display the order book like on their webpage. More importantly, the depth cache gets sorted before display

```php
$api->depthCache("ETHBTC", function($api, $symbol, $depth) {
	echo "{$symbol} depth cache update".PHP_EOL;
	//print_r($depth); // Print all depth data
	$limit = 11; // Show only the closest asks/bids
	$sorted = $api->sortDepth($symbol, $limit);
	$bid = $api->first($sorted['bids']);
	$ask = $api->first($sorted['asks']);
	echo $api->displayDepth($sorted);
	echo "ask: {$ask}".PHP_EOL;
	echo "bid: {$bid}".PHP_EOL;
});
```

**Comment by jaggedsoft** [comment]
![image](https://user-images.githubusercontent.com/4283360/35582354-70006a4c-05a3-11e8-88be-2539cbe3c960.png)
