### ISSUE TITLE
Fatal error: Uncaught Exception: signedRequest error: {"code":-4046,"msg":"No need to change margin type."}

### ISSUE THREAD

**Issue by designpositive** [jaggedsoft/php-binance-api#445]
Here is my code:

$cm_leverage = $api->futuresLeverage("TRXUSDT", "5");
$cm_margintype = $api->futuresMarginType("TRXUSDT", "CROSSED");

This error stops the other codes from working. How can I solve this?

**Comment by ePascalC** [comment]
Hi @designpositive , I do not see any function called futuresLeverage in the current code. But anyway, for any call you make, you should use standard PHP try/catch if a function can result in a fatal error.
