### ISSUE TITLE
Curl error: getaddrinfo() thread failed to start

### ISSUE THREAD

**Issue by info170** [jaggedsoft/php-binance-api#447]
**Get an error:** `Curl error: getaddrinfo() thread failed to start`  while executing API->candlesticks() method.

**Error message in laravel.log :**
 {"exception":"[object] (Exception(code: 0): Curl error: getaddrinfo() thread failed to start
 at /opt/bitnami/apache/htdocs/vendor/jaggedsoft/php-binance-api/php-binance-api.php:1319)
[stacktrace]
#0 /opt/bitnami/apache/htdocs/vendor/jaggedsoft/php-binance-api/php-binance-api.php(1489): Binance\\API->httpRequest()
#1 /opt/bitnami/apache/htdocs/app/Services/TraderService.php(525): Binance\\API->candlesticks()

**Platform:**  unix (aws lightsail)

**Code:**

```
//$symbols = array of 200 symbols
$timePeriod = 500;
foreach ($symbols as $symbol) {
    $candles = $api->candlesticks($symbol.'USDT', '1h', $timePeriod);
}
```

**Comment by ePascalC** [comment]
Hi @info170
That is a CURL error based on your bitnami server settings. Things to check:
1) You might not have enough RAM => increase
2) Running too many curl threads too fast so they cannot close in time => try slowing down or run only e.g. 20 to test

PS if you need all USDT ones, consider getting exchangeInfo and then loop all the symbols with quoteAsset="USDT"
