### ISSUE TITLE
dude: Get Response Headers

### ISSUE THREAD

**Issue by marcoas** [jaggedsoft/php-binance-api#454]
(Translated by Google)

Hello.
How to access HTTP headers from API response?

**Comment by ePascalC** [comment]
@marcoas
```
$candles = $api->candlesticks("BTCUSDT", "1h");
print_r($api->lastRequest['header']);
print_r($api->xMbxUsedWeight);

```
After you run any command (like get candlesticks) you could ask for the 'lastRequest' and from that array take the 'header' subarray.
If you just want the used Weight so far, you could also check xMbxUsedWeight

Hope this helps.

**Comment by marcoas** [comment]
Excellent
