### ISSUE TITLE
Pay to email

### ISSUE THREAD

**Issue by prodriguezdlt** [jaggedsoft/php-binance-api#455]
Hey, do you know if binance has an endpoint to send assets/crypto to another binance user by email? This is achieved in the webapp by going to "Spot Wallet" adnd on the top right corner theres a main menu with the options "Deposit" "Withdraw" "Pay" "Transfer"... The "Pay" button takes you to this functionality where you can send crypto to another binance user without fees by using either the telephone or email... 

Its really hand and i kinda want to use it but i dunno if theres an api endpoind for it, do you guys know?

**Comment by ePascalC** [comment]
Hi @prodriguezdlt , from reading the documentation, I only found a way to send from and to sub accounts: https://binance-docs.github.io/apidocs/spot/en/#universal-transfer-for-master-account

I suppose you are looking for transfer to a completely different master account, correct?

**Comment by prodriguezdlt** [comment]
Yeah im trying to do a pay transfer from one binance account to another... its possible on the app and also on web, but i cant find anything on the api :/

**Comment by ePascalC** [comment]
Indeed, nothing found on my side either... maybe one day!

**Comment by ePascalC** [comment]
@prodriguezdlt 
Response received on the Binance forum: https://dev.binance.vision/t/send-crypto-by-email/7262
