### ISSUE TITLE
Getting 20 currency pairs only

### ISSUE THREAD

**Issue by Firefighter-87** [jaggedsoft/php-binance-api#459]
**Getting 20 currency pairs only**
- bug: the alleged bug refers to the method prices() of the api class

**Short Description:**
- I'm following the example code but I'm getting 20 currency pairs only:

**Platform:**
- windows (xampp)

**php version:**
- both 7 and 8 versions

**code**
```php
$ticker = $api->prices();
print_r($ticker);
```

**result**
```
Array
(
    [BNBBUSD] => 585.00000000
    [BTCBUSD] => 50000.00000000
    [ETHBUSD] => 3999.00000000
    [LTCBUSD] => 154.47000000
    [TRXBUSD] => 0.09116000
    [XRPBUSD] => 0.82500000
    [BNBUSDT] => 558.13000000
    [BTCUSDT] => 48354.67000000
    [ETHUSDT] => 35214.16000000
    [LTCUSDT] => 1102.27000000
    [TRXUSDT] => 0.08681000
    [XRPUSDT] => 0.78760000
    [BNBBTC] => 0.01180000
    [ETHBTC] => 0.08419400
    [LTCBTC] => 0.00315800
    [TRXBTC] => 0.00000186
    [XRPBTC] => 0.00001719
    [LTCBNB] => 0.25170000
    [TRXBNB] => 0.00015640
    [XRPBNB] => 0.00144300
)
```
I think the list should be much longer
thank you

**Comment by ePascalC** [comment]
@Firefighter-87 All working fine, hundreds of responses. Please check your full code.

**Comment by Firefighter-87** [comment]
> @Firefighter-87 All working fine, hundreds of responses. Please check your full code.

I've just checked and I think I've found the "issue". I was addressing the API calls to the TESTNET base endpoint. When I set the regular base endpoint, everything works fine. My need was to test dozens of pairs per time. I'll have to carefully test on the regular endpoint.
