### ISSUE TITLE
Websocket

### ISSUE THREAD

**Issue by carllewis1980** [jaggedsoft/php-binance-api#47]
I can't get any of the websocket functions to work?

even the ones in the example page don't work for me. Can you give me any guidance?

**Comment by jaggedsoft** [comment]
Working fine here, curious what the problem could be
What version of php are you using?

**Comment by carllewis1980** [comment]
Thank you for the reply, any help will be much appreciated

 

I am running the new xampp so PHP 7.2.1.

 

I would rate myself as beginner so its probably me doing something wrong. I have tried to break it down to the simplest script but I can get anything to work. I get the following response…

 

Fatal error: Uncaught Error: Call to undefined method Binance::userData() in C:\xampp\htdocs\BinanceTradeBot\Test.php:36 Stack trace: #0 {main} thrown in C:\xampp\htdocs\BinanceTradeBot\Test.php on line 36

 

From the following script

 

 

 

// Works without composer, supports php 5.6

require 'binance-api-single.php';

require 'php-binance-api.php';

$api = new Binance("blah blah blah"," blah blah blah ");

 

$balance_update = function($api, $balances) {

        print_r($balances);

        echo "Balance update".PHP_EOL;

};

$order_update = function($api, $report) {

        echo "Order update".PHP_EOL;

        print_r($report);

        $price = $report['price'];

        $quantity = $report['quantity'];

        $symbol = $report['symbol'];

        $side = $report['side'];

        $orderType = $report['orderType'];

        $orderId = $report['orderId'];

        $orderStatus = $report['orderStatus'];

        $executionType = $report['orderStatus'];

        if ( $executionType == "NEW" ) {

                 if ( $executionType == "REJECTED" ) {

                         echo "Order Failed! Reason: {$report['rejectReason']}".PHP_EOL;

                 }

                 echo "{$symbol} {$side} {$orderType} ORDER #{$orderId} ({$orderStatus})".PHP_EOL;

                 echo "..price: {$price}, quantity: {$quantity}".PHP_EOL;

                 return;

        }

        //NEW, CANCELED, REPLACED, REJECTED, TRADE, EXPIRED

        echo "{$symbol} {$side} {$executionType} {$orderType} ORDER #{$orderId}".PHP_EOL;

};

$api->userData($balance_update, $order_update);

 

 

I can’t find the function userdata anywhere within the files downloaded.

 

Also, can I ask you, is websocket quicker than the requests? Can you access the socket data information to make calculations?

**Comment by jaggedsoft** [comment]
I can't support the version without composer. That one is really old and is only provided as an example

The version with composer is very much improved if you can get it working

**Comment by carllewis1980** [comment]
Hi Jaggedsoft... me again!!!

Sorry i'm probably becoming a pain in the arse.

i am after advice... i have the following setup. i have my websockets on separate pages. they update a mysql database, then i can access all the info anywhere on any of my pages by accessing the mysql database.

This was working fine until lunch time today, now the candlestick only updates the first load of information (500 lines), then wont update new information created.
if i refresh the candlestick page it will add the new info. but i need this to be automatic.

has something changed today with the info returned?

i would really really appreciate your help.

**Comment by jaggedsoft** [comment]
As far as I can tell, nothing has changed. I'll see if I can make time to troubleshoot what's going on

**Comment by carllewis1980** [comment]
thank you...

i was really happy this morning. My bot was starting to work properly, it kicked in at the drop last night and brought back in lower... i was just about to put the deposit down on a new lambo... then it stopped working :-(

**Comment by carllewis1980** [comment]
heres my current code, after trying a zillion different combinations...

$api->chart([$symbol], $time, function($api, $symbol, $chart) {

$keys = array_keys($chart);

foreach ($keys as &$value) {
    $open = $chart[$value]['open'];
    $high = $chart[$value]['high'];
    $low = $chart[$value]['low'];
    $close = $chart[$value]['close'];
    $volume = $chart[$value]['volume'];


if ((isset($chart[$value]['openTime'])) && (isset($chart[$value]['closeTime']))) {
$openTime = $chart[$value]['openTime'];
$closeTime = $chart[$value]['closeTime'];

global $conn;
//$sql = "INSERT INTO btcusdt5m (openTime, close)
//VALUES ('" . $openTime . "', '" . $close . "')";
//$conn->query($sql);

$sql = "
INSERT INTO btcusdt5m(openTime, close)
VALUES ('" . $openTime . "', '" . $close . "')
ON DUPLICATE KEY UPDATE openTime = '" . $openTime . "', close = '" . $close . "'
";
//$conn->query($sql);

if ($conn->query($sql) === TRUE) {
    echo $openTime . " - " . $close . " - New record created successfully or updated<BR>";
} else {
    echo $openTime . " - " . $close . " - Error: " . $sql . "<br>" . $conn->error;
}


} else {
    //echo "Not added<BR>";
}



}//Foreach End

});

**Comment by carllewis1980** [comment]
i have found a way round it, for now
self refresh wasn't working, so i have loaded the file within an iframe, then refreshed the iframe from the parent.
this might also solve the issue when binance cuts the connection after 24hrs of use...

**Comment by khoatran** [comment]
Hi, 
I've got the same problem with the latest version of the code. It shows me the error "Undefined method userData". I also check the code in all versions and cannot see this method anywhere.
Can you explain how to make it works?

Thanks,

**Comment by dmzoneill** [comment]
userData was removed over 2 months ago in this commit:

https://github.com/jaggedsoft/php-binance-api/commit/d025f078a84265ace2cee371d0a44376d15c2dde

**Comment by jaggedsoft** [comment]
Thanks. I believe userData was removed by mistake somehow, and needs to be added again

**Comment by jaggedsoft** [comment]
Fixed https://github.com/jaggedsoft/php-binance-api/commit/09011880abfa68b0d222f364e1c3c5636d41038f
Available in `v0.1.7`
