### ISSUE TITLE
The problem of buying a large number of wallets

### ISSUE THREAD

**Issue by Sadam-beshr** [jaggedsoft/php-binance-api#475]
I used a repeat buying ring for everyone who subscribed to me in a certain currency.. If the number of subscribers is 100 subscribers...there is a difference between the purchase from the first person to the last....Is there a solution to buy for everyone without using the order limit. I want to use the market purchase for everyone at the same time ... knowing that the time difference between buying for the first subscriber until the last subscriber is 3 minutes ... which is a very big time ...... What is the correct way to buy for all subscribers at once

`for($i=0;$i<=$cou;$i++){$myapi = new Binance\API($api_key,$api_secret);$order =$myapi->buy($symbol, $quantity, 0, "MARKET");}`
The problem is that there is a difference between the time of buying the first wallet and the last one..... What is the solution to buying all the wallets at once at one price?

**Comment by ePascalC** [comment]
Hi @Sadam-beshr, the only solution I see is to buy in market price in 1 action the value of all wallets together and after that split it internally onto the different wallets.
