### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by carllewis1980** [jaggedsoft/php-binance-api#49]
I have the composer version now... but can't get this to work either.... :-(

I'm just trying with your examples

Fatal error: Uncaught Error: Class 'React\EventLoop\Factory' not found in C:\xampp\htdocs\BinanceComposer\examples\php-binance-api.php:536 Stack trace: #0 C:\xampp\htdocs\BinanceComposer\examples\example.php(89): Binance\API->trades(Array, Object(Closure)) #1 {main} thrown in C:\xampp\htdocs\BinanceComposer\examples\php-binance-api.php on line 536

**Comment by jaggedsoft** [comment]
Composer should have installed the necessary dependencies for you

try this from inside your project directory
`composer install ratchet/pawl`

or if that doesn't work

`composer install ratchet/pawl --save`

**Comment by jaggedsoft** [comment]
If you get stuck start over in a new project directory

`composer require "jaggedsoft/php-binance-api @dev"`

then make your bot.php file and verify it works
```php
require 'vendor/autoload.php';
$api = new Binance\API("<api key>","<secret>");

$ticker = $api->prices();
print_r($ticker); // List prices of all symbols
echo "Price of BNB: {$ticker['BNBBTC']} BTC.".PHP_EOL;
```

**Comment by jaggedsoft** [comment]
btw, the javascript version of this library is much easier to use if you are comfortable with that
https://github.com/jaggedsoft/node-binance-api/

**Comment by carllewis1980** [comment]
Hi

 

I have managed to create a trading bot, using your package. but not manged to get the websocket parts to work.

 

I have just wiped it clean and started again. This time I noticed this error message on loading….

 

  - Installing jaggedsoft/php-binance-api (dev-master 556c522): Cloning 556c522500

    Failed to download jaggedsoft/php-binance-api from source: Failed to clone https://github.com/jaggedsoft/php-binance-api.git, git was not found, check that it is installed and in your PATH env.

 

'git' is not recognized as an internal or external command,

 

I have tried composer remove “jaggedsoft/php-binance-api @dev” to then try and reload it, but I get this message

 

C:\Users\Carl>composer remove "jaggedsoft/php-binance-api @dev"

jaggedsoft/php-binance-api @dev is not required in your composer.json and has not been removed

Package "jaggedsoft/php-binance-api @dev" listed for update is not installed. Ignoring.

Loading composer repositories with package information

Updating dependencies (including require-dev)

Nothing to install or update

Generating autoload files

 

I’m guessing it hasn’t loaded properly

**Comment by jaggedsoft** [comment]
'git' is not recognized as an internal or external command,

You need to install git

**Comment by carllewis1980** [comment]
I know you know what what you are talking about... but sometimes the people you are talking to don’t.

So got is another extension I need to install?

**Comment by jaggedsoft** [comment]
Normally it's installed when you install composer

https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
For me on linux it is `sudo apt-get install git-all`

For windows and mac instructions they explain it in the link

**Comment by carllewis1980** [comment]
Thank you for your guidance, fingers crossed this will solve the issue.

**Comment by carllewis1980** [comment]
I have installed git… but I have been trying to reinstall composer require "jaggedsoft/php-binance-api @dev"

 

But I can remember how to do the full reinstall again, the above command only does a parsal install… can you help?

**Comment by jaggedsoft** [comment]
Try `composer require "jaggedsoft/php-binance-api"` from your project directory
If you have trouble after try this
`composer require "jaggedsoft/php-binance-api @dev"`

**Comment by jaggedsoft** [comment]
There is another PHP API that you may have better luck with
https://github.com/larislackers/php-binance

Or  you can try setting up a $5 VPS (vultr, digitalocean, etc) running debian linux and deploy your bot there, that is what I do

**Comment by carllewis1980** [comment]
I have spent so much time understanding and building a program with your setup, I cant change to something else now

 

And its too slow on normal HTTP requests… I need to get websockets working…

**Comment by carllewis1980** [comment]
Its working!!!!

 

Woo hoo – bed time. I can play with it in the morning

**Comment by carllewis1980** [comment]
Hi – I managed to get it working last night, which is great. I set the php time limit to 0, connected via the websocket and getting the massive stream of data.

 

Today I have been trying ways to use this new found stream of data at my finger tips, But I can’t find a way to turn the lastest info from an array into useable data. Are you able to give me advice on how to use it? Even just point me in the right direction and I can google that would be great…

 

Starting off small I just wanted to build a counter showing the latest trade.

 

// Trade Updates via WebSocket

$api->trades(["BTCUSDT"], function($api, $symbol, $trades) {

    //echo "{$symbol} trades update".PHP_EOL;

    $_SESSION['BitcoinPrice'] = $trades['price'];

    //Echo $_SESSION['BitcoinPrice'] . "<Br>";

});

 

 

Any help will be much appreciated 

 

Thank you

**Comment by jaggedsoft** [comment]
Simple example
```php
$api->trades(["BTCUSDT"], function($api, $symbol, $trades) {
	echo "BTCUSDT: \${$trades['price']}".PHP_EOL;
});
```

Access a variable outside the function (keep a global $ticker object)
```php
$ticker = [];
$api->trades(["BTCUSDT"], function($api, $symbol, $trades) {
	global $ticker;
	$ticker[$symbol] = $trades['price'];
	echo "BTCUSDT: \${$ticker[$symbol]}".PHP_EOL;
});
```

**Comment by carllewis1980** [comment]
I’ll have a play after the kids are in bed.

Thank you

**Comment by carllewis1980** [comment]
Banging my head against a wall here…

 

I can get the function as its own file, but as soon as I run it in with my other, with other php script it grinds to a halt. Should I be using your functions below as a separate file and calling them as a function, separate from my script?

**Comment by carllewis1980** [comment]
This is doing my head in…. Do I use curl to grab the latest data to use in my script?

 

Its my last resort…
