### ISSUE TITLE
'Name' parameter is required for withdrawals 

### ISSUE THREAD

**Issue by pachalaa** [jaggedsoft/php-binance-api#50]
Hello,

It seems that the name parameter, showed non mandatory on api doc, is in fact mandatory for withdrawals. When I try one I get the following error message : `Name is empty.`

For those who are trying to do withdrawals and having the same issue, replace the public function withdraw in **php-binance-api.php line 65** with that one : 

```
public function withdraw($asset, $address, $amount, $addressTag = false, $name) {           
$options = ["asset"=>$asset, "address"=>$address, "amount"=>$amount, "name"=>$name, "wapi"=>true];
                if ( $addressTag ) $options['addressTag'] = $addressTag;
                return $this->signedRequest("v3/withdraw.html", $options, "POST");
        }
```

And to initiate the withdrawal, just add the name parameter like this : 

```
$asset = "BTC";
$address = "1C5gqLRs96Xq4V2ZZAR1347yUCpHie7sa";
$amount = 0.2;
$name = "whatever";
$response = $api->withdraw($asset, $address, $amount, $name);
print_r($response);
```

It save the destination address in your withdrawal dashboard with a name... 

Bye !

**Comment by jaggedsoft** [comment]
Thank you very much for the report! I have made this default to "API Withdraw" now

**Comment by pachalaa** [comment]
You're welcome !
