### ISSUE TITLE
Example with 'TAKE_PROFIT_LIMIT'

### ISSUE THREAD

**Issue by Penn0r** [jaggedsoft/php-binance-api#53]
Hi,

Any possibility of showing how TAKE_PROFIT_LIMIT works? An example would be so helpful

**Comment by jaggedsoft** [comment]
I'll work on providing one, for now this is my understanding

```php
$type = "TAKE_PROFIT_LIMIT "; // Set the type STOP_LOSS (market) or STOP_LOSS_LIMIT, and TAKE_PROFIT (market) or TAKE_PROFIT_LIMIT
$quantity = 1;
$stopPrice = 0.6; // Trigger to take profits at 0.6 btc
$price = 0.5; // Sell down as low as 0.5 btc
$order = $api->sell("BNBBTC", $quantity, $price, $type, ["stopPrice"=>$stopPrice]);
```

Take profits will sell at whatever price you set in the price field
But it is only triggered once the price hits stopPrice

So the lower you make 'price' the more likely you are to close your orders
you could probably make that number really low and it would act just like a market sell

https://support.kraken.com/hc/en-us/articles/203053226-Take-Profit-Orders

**Comment by Penn0r** [comment]
This looks just like a limit order to me. I don't see any difference at all

An order with at stop at 0.6 and limit price of 0.5,  isn't this identical to your example?
