### ISSUE TITLE
Sell Limit doesn't work

### ISSUE THREAD

**Issue by cryptonic203** [jaggedsoft/php-binance-api#55]
Code:

require 'vendor/autoload.php';
$api = new Binance\API("XJ**apikey**WZ","y**secret**Z");
$quantity = 20;
$price = 0.00105;
$order = $api->sell("XRPETH", $quantity, $price);

It returns:
 signedRequest error: {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}

What should I do?

**Comment by jaggedsoft** [comment]
Synchronize your server time
or do this:

#### useServerTime Method 1
```php
$api = new Binance\API("<key>", "<secret>", ['useServerTime'=>true]);
```
#### useServerTime Method 2
```php
//Call this before running any functions
$api->useServerTime();
```

**Comment by cryptonic203** [comment]
I synchronized time, everything worked. Thank you so much.
