### ISSUE TITLE
Setting a buy order

### ISSUE THREAD

**Issue by carllewis1980** [jaggedsoft/php-binance-api#56]
Hi

How do i set a buy order for once the coin reaches a certain amount.

Say bitcoin is at 8470 and i want to set it to buy if it reaches 8510?

Which one would i use?
STOP_LOSS (market)
STOP_LOSS_LIMIT
TAKE_PROFIT (market)
TAKE_PROFIT_LIMIT

**Comment by 0dark0** [comment]
None!

They are SELL orders. If you want to buy, use BUY LIMIT or BUY MARKET order.

Here is what I would do

$price = current market price;

if $price >= '8510';

then do a BUY LIMIT/MARKET order;

**Comment by jaggedsoft** [comment]
Thanks 0dark0 for helping :+1: 

Yes, all you need is to place a 'limit' buy order for 8510.
A stop_loss_limit will sell something you own if the price drops below a certain point
A take_profit_limit will sell something you own if the price goes above a certain point

**Comment by RacingStatistics** [comment]
Sorry to open this one up, but the answer has not really been given.
Although 'placing a limit buy when price >= x' sounds nice, it's not the automatic method like 'STOP_LOSS_LIMIT' is.

If I have a script which monitors every 5 minutes and places stop-limit markers for both BUY and SELL, you need a functionality such as 'STOP_LOSS_LIMIT' but for BUY.

If you look at the binance interface, these 'stop-limits' for buy can be placed there. Just haven't found a way to do those through the API / this lib.

Hope you can help!

**Comment by jaggedsoft** [comment]
@RacingStatistics Hi there, most things that you can do from the binance interface are supported by this library.
```php
$flags = ['stopPrice' => 7444.77, 'newOrderRespType' => 'FULL'];
$amount = 0.002;
$order = $api->order('SELL', 'BTCUSDT', $amount, 0, 'STOP_LOSS_LIMIT', $flags);
```

Just reverse the logic for buying.
Binance does not allow both a BUY and a SELL stoploss at the same time though.

**Comment by RacingStatistics** [comment]
huh... now it works...
I got a '_order would trigger immediately_' earlier when I tried...

Anyway, this now works like a charm 👍 

$api->buy('NULSBTC', 20, 0.00018500, "STOP_LOSS_LIMIT", [ "stopPrice" => 0.00019000 ]);

Creates a stop-limit buy order for 20 NULS when the price goes above 19000 sats and from that moment on tries to buy it for 18500 sats.

Thanks for your reply and overall very handy library jaggedsoft!!

**Comment by gnzlst** [comment]
Hi @jaggedsoft 

I am sorry to open this again, but I cannot understand how you create a STOP_LOSS_LIMIT sell order with a price of 0.

> ```
> $flags = ['stopPrice' => 7444.77, 'newOrderRespType' => 'FULL'];
> $amount = 0.002;
> $order = $api->order('SELL', 'BTCUSDT', $amount, 0, 'STOP_LOSS_LIMIT', $flags);
> ```

I tried, but it just throws and "Invalid price" exception.
