### ISSUE TITLE
getting ServerTime option when using aJax to call api

### ISSUE THREAD

**Issue by MrDevBC** [jaggedsoft/php-binance-api#57]
I have the api and key save in database. when I click on the button save..
it run the ajax and connect to api and connect data, but it throw back this error and I have already set the time option:

$api = new Binance\API($api, $apiSecret, ['useServerTime' => true]);

Error:
balanceData error: Please make sure your system time is synchronized, or pass the useServerTime option.

**Comment by jaggedsoft** [comment]
There may be some other error being returned such as incorrect key

You can also tryremoving the useServerTime part of the options and call this before running the balance function
`$api->useServerTime();`
But ultimately synchronizing the system time will solve it most of the time

**Comment by MrDevBC** [comment]
I have even try hard coding the api and secret along with $api->useServerTime(); and still no go and other idea?

**Comment by jaggedsoft** [comment]
Sorry.. no clue. It's working over here

You might have more success with the javascript version of this library, it's much easier to use
https://github.com/jaggedsoft/node-binance-api

**Comment by MrDevBC** [comment]
Jaggedsoft,
So this code I have here works offline but when uploading it onto a hosting it doesn't work? any idea?

![error_1](https://user-images.githubusercontent.com/22015455/36075951-6d7044e4-0f0a-11e8-83fe-fe50e029cfec.jpg)
![error_2](https://user-images.githubusercontent.com/22015455/36075952-6d88eba2-0f0a-11e8-9f4c-18c56ab62604.jpg)

**Comment by jaggedsoft** [comment]
Sounds like a composer issue
My project will not work unless I specifically include:
```
require 'vendor/autoload.php';
```

**Comment by MrDevBC** [comment]
I don't think the autoload is the issue. all the autoload.php is just loading the class file

**Comment by jaggedsoft** [comment]
That's not true. It needs to load ratchet/pawl and other dependencies as well

**Comment by jaggedsoft** [comment]
Try `composer require ratchet/pawl` from your project directory, it might work then
