### ISSUE TITLE
[HELP] Am I doing this right?

### ISSUE THREAD

**Issue by MrDevBC** [jaggedsoft/php-binance-api#59]
$CryptoCoins = array();

$api->ticker(false, function($api, $symbol, $ticker) use($CryptoCoins) {

    echo '<pre>';
    $CryptoSymbol = $ticker['symbol'];

    if ( array_key_exists($CryptoSymbol, $CryptoCoins) )  {
      // Update Price
        //$newtest[$ticker['symbol']] = array('percentChange' => $ticker['percentChange']);
        echo 'exist';
    } else {
        $CryptoCoins[$CryptoSymbol] = array('percentChange' => $ticker['percentChange'] );
        echo 'ADD: ' . $CryptoSymbol;
    }
    print_r($CryptoCoins);
   echo '</pre>';
});

**Comment by riddlemd** [comment]
Did you ever get this sorted out?

**Comment by MrDevBC** [comment]
Not really.. I guess the web sockets value always get replaced...
