### ISSUE TITLE
Fatal error with method Binance::depositAddress() 

### ISSUE THREAD

**Issue by eugypalu** [jaggedsoft/php-binance-api#62]
Hi,
I'm getting an error when trying to use the depositAddress method

$depositAddress = $api->depositAddress("VEN");
print_r($depositAddress);

This is the error:

Fatal error: Uncaught Error: Call to undefined method Binance::depositAddress()
Stack trace:
#0 {main}

**Comment by jaggedsoft** [comment]
Thanks! This might be fixed in v0.0.15 if you update with `composer update`

**Comment by eugypalu** [comment]
composer update does not solve the problem

**Comment by dmzoneill** [comment]
Reopening.. will triage after work..  thanks for the report... it may be related to the curl upgrade.  check back shortly

**Comment by eugypalu** [comment]
Hi, after the latest updates everything works. thank you
