### ISSUE TITLE
How to get a list of order history?

### ISSUE THREAD

**Issue by sumihiro** [jaggedsoft/php-binance-api#7]
I would like to get a list like this page.
https://www.binance.com/userCenter/orderHistory.html
It summarizes the contents of the transaction for each currency pair.

I know that I can retrieve my history by specifying the currency in the next method.
$api->history("BNBBTC");
But I do not know how to get a list of "all the currencies I used".

How can I get a list of "all my currencies"?

**Comment by jaggedsoft** [comment]
Yes, thank you for your suggestion!
Unfortunately as of right now this is not possible. However I will suggest it to the binance dev team
There is also `$api->orders("BNBBTC")` however it still requires a symbol.

![image](https://user-images.githubusercontent.com/4283360/34126445-719cd902-e3ee-11e7-9501-1cc1659167fb.png)

**Comment by sumihiro** [comment]
@jaggedsoft 
I appreciate your advice.
This function is an essential function for asset management service which I am making.
Support for Binance is strongly desired in this service.
I hope that Binance's development team will be able to create it early.

If necessary, I will tell my request to the development team myself. Please tell me the channel.
