### ISSUE TITLE
btcTotal empty after last commit

### ISSUE THREAD

**Issue by dade80vr** [jaggedsoft/php-binance-api#70]
Hi, i got **btcTotal** empty after [last commit](https://github.com/jaggedsoft/php-binance-api/commit/f6036494b5c07f502b6be308741d81915cfbb52d)

```
    [BNB] => Array
        (
            [available] => 1.22424343
            [onOrder] => 0.00000000
            [btcValue] => 0
            [btcTotal] => 0
        )
```
Why?

And is possible to know btcValue directly in this array result?
Thanks.

**Comment by jaggedsoft** [comment]
Working for me. Make sure to pass a valid $ticker object
```php
$ticker = $api->prices();
$balances = $api->balances($ticker, true);
foreach ( $balances as $symbol => $obj ) {
	$btc = $obj['btcTotal'];
	if ( $btc <= .001 ) continue;
	echo "{$symbol}: {$btc}\n";
}
echo number_format($api->btc_value,8,'.','')."\n";
```

**Comment by dmzoneill** [comment]
I saw this earlier on in the week.. it's related to missing operand in one of the function calls and the lack of type checking.. I fixed it previously... can you checkout again? I'll take a look later this evening to make sure..

**Comment by jaggedsoft** [comment]
Definitely working for me at least for right now. There's a chance we were getting a request error from binance and not displaying it

**Comment by dade80vr** [comment]
Problem appeared when pulled last commit from binance-exchange/php-binance-api.
Deleted the repo and cloned **jaggedsoft**/php-binance-api works fine (???).

**Comment by jaggedsoft** [comment]
Thanks for the report! Let us know if you have any problems. I'm still really busy the next few weeks, after I want to make a big push to improve all any shortcomings and make the library easier to use
