### ISSUE TITLE
unit tests for api validation

### ISSUE THREAD

**Issue by dmzoneill** [jaggedsoft/php-binance-api#71]
Setup free plan - https://travis-ci.com/plans

- unit tests
- continuous validation of api using travis or some other CI, for validating commits

**Comment by dmzoneill** [comment]
@jaggedsoft 

can you please login to https://travis-ci.com/ and setup a free account
1) create account on https://travis-ci.com/
2) link the php binance repo  to travis
3) you may need to add a .travis file like
   https://github.com/dmzoneill/android-digiweb-usage/blob/master/.travis.yml

Once you do that, i can do everything else as a collaborator 
https://stackoverflow.com/questions/25857012/is-it-possible-to-set-up-travis-for-a-project-for-which-you-are-a-collaborator

4) test/BinaceTest.php then will run prior to every pull request to validate nasty code like mine!

thanks
dave

**Comment by jaggedsoft** [comment]
Thanks Dave, just says it needs a `.travis.yml` file in the repository, not sure exactly what that should look like

**Comment by dmzoneill** [comment]
Excellent man.. added build status to the read me. The unit tests are empty stubs atm... returning true.. so it's false positive at the moment

**Comment by dmzoneill** [comment]
after conferring with binance on their terms of service.  They have authorized me to create a secondary account with the intention of using a public key and secret.

key: z5RQZ9n8JcS3HLDQmPpfLQIGGQN6TTs5pCP5CTnn4nYk2ImFcew49v4ZrmP3MGl5
secret: ZqePF1DcLb6Oa0CfcLWH0Tva59y8qBBIqu789JEY27jq0RkOKXpNl9992By1PN9Z

lets see how long before someone gets the account banned!

There is no money in the account folks!
