### ISSUE TITLE
Cancel order not working

### ISSUE THREAD

**Issue by omar8792** [jaggedsoft/php-binance-api#72]
Hi, seems that the cancel order it's no working.

Looking in the code, it seems related to merge of function "signedRequest" into "httpRequest".
Infact the cancel order need to use the method "DELETE" but in the code is set default "GET" and the only check of this parameters in the curl it's at line 205:
`if($method == "POST") {`
`   curl_setopt($ch, CURLOPT_POST, true);`
`   //curl_setopt($ch, CURLOPT_POSTFIELDS, $query);`
`}`

can be fixed with this line of code for example:
`
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $method);` at line 189

**Comment by mrsantran** [comment]
`public function cancel($symbol, $orderid) {
		return $this->httpRequest("v3/order", "DELETE", ["symbol"=>$symbol, "orderId"=>$orderid], true);
	} `
Its work. You can compare you local lib with github lib.

**Comment by dmzoneill** [comment]
hi

Many thanks for this bug fix

https://github.com/jaggedsoft/php-binance-api/commit/a8804eb95a6104ae830723c0110ff0bcda46407d

**Comment by jaggedsoft** [comment]
Thanks for the report @ fixed in release `v0.1.2`
Keep up the good work 👍
