### ISSUE TITLE
jaggedsoft & dxjones

### ISSUE THREAD

**Issue by dmzoneill** [jaggedsoft/php-binance-api#76]
the travis-ci test automation now tests the primary functions.  i will continue to add more tests.

https://travis-ci.org/jaggedsoft/php-binance-api/

the build now runs against pull requests also.
If the basic tests fail, there is probably something wrong, with the pull request code
please close this issue per your discretion

enjoy

**Comment by jaggedsoft** [comment]
@dmzoneill Keep up the great work, friend. I'm very busy lately so sorry that I'm not around more, but your work is very much appreciated and I will find a way to return the favor in the future.
