### ISSUE TITLE
HTTP/1.1 400 Bad Request

### ISSUE THREAD

**Issue by markolofsen** [jaggedsoft/php-binance-api#8]
**I got an error when try to place order.**

```
         $api = new API($apiKey,$apiSecret);
         $quantity = 1;
         $price = 0.0005;
         $order = $api->buy("BNBBTC", $quantity, $price);
```

```
PHP Warning – yii\base\ErrorException
file_get_contents(https://api.binance.com/api/v3/order?symbol=BNBBTC
&amp;side=BUY&amp;type=LIMIT&amp;quantity=1&amp;recvWindow=60000
&amp;price=0.0005&amp;timeInForce=GTC
&amp;timestamp=1513645254232
&amp;signature=*******): 
failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
```

**Comment by jaggedsoft** [comment]
What version of PHP are you using?

**Comment by markolofsen** [comment]
Two different: PHP 7.0 and 5.5

**Comment by bgold0** [comment]
I'm getting the same issue. PHP 5.3.38

**Comment by markolofsen** [comment]
@bgold0 nope, but I think that problem in urlencode function of file_get_contents() method...

**Comment by jaggedsoft** [comment]
This issue has possibly been fixed in the latest release, please keep my updated
Thank you for the report!

I can confirm that I am also running into this problem, I might have to switch to to cURL but I originally didn't want to add an extra dependency

Encoding is not the issue
The server is returning a 400 error code even though we are sending the correct parameters
One thing that is strange is that if we tell file_get_contents to ignore errors then it seems to work

**Comment by markolofsen** [comment]
@jaggedsoft 

**New strange errors when I do:**
```
$api = new API(***,***);
$order = $api->buy("BNBBTC", 1, 0.0005);
```

**Errors:**
```
An Error occurred while handling another error:
exception 'yii\web\HeadersAlreadySentException' with message 'Headers already sent in .../yii2/api/controllers/ApiController.php on line 77.' in .../yii2/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 .../yii2/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 .../yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(124): yii\web\Response->send()
#2 .../yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
exception 'yii\web\HeadersAlreadySentException' with message 'Headers already sent in .../yii2/api/controllers/ApiController.php on line 77.' in .../yii2/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 .../yii2/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 .../yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Response->send()
#2 .../yii2/api/web/index.php(17): yii\base\Application->run()
#3 {main}
```

**Comment by jaggedsoft** [comment]
I would love to help, but I have no experience with the yii framework so can not provide input there

**Comment by markolofsen** [comment]
@jaggedsoft I made a mistake) Now everything ok

**Comment by aharley40** [comment]
@jaggedsoft I'd wish i'd posted that it works when you turn error reporting off :p. 

If anyone finds a cleaner fix in the future please update!

**Comment by jaggedsoft** [comment]
This appears to be a problem with the binance api incorrectly reporting a 400 response code. Not much I can do about it at this point
Even though mine are returning with a 400 response all the calls are working
