### ISSUE TITLE
Timestamp for this request is outside of the recvWindow.

### ISSUE THREAD

**Issue by wesly1988** [jaggedsoft/php-binance-api#83]
Hi,

Love the bot, works like a charm, just got one problem. 
Keep getting the following error. 

Array ( [code] => -1021 [msg] => Timestamp for this request is outside of the recvWindow. )

Tried everything as explained, but keep getting the error.

`signedRequest error: {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
signedRequest error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
balanceData error: Please make sure your system time is synchronized, or pass the useServerTime option.
useServerTime Method 1
$api = new Binance\API("<key>", "<secret>", ['useServerTime'=>true]);
useServerTime Method 2
//Call this before running any functions
$api->useServerTime();`

The above solution didn't work for me. 

Get the following error

Fatal error: Uncaught Error: Call to undefined method Binance::useServerTime() in /home/social/domains/[********]/public_html/cronjob/binance/test.php:21

What am I doing wrong? 
Somehow the fuction useServerTime() isn't accessible. 

Thank you in advance!

**Comment by wesly1988** [comment]
solved!
Somehow I was still including the old api!

Problem is fixed.

**Comment by jaggedsoft** [comment]
Glad to hear it. Let us know if you have any trouble 👍

**Comment by vimoda** [comment]
> solved!
> Somehow I was still including the old api!
> 
> Problem is fixed.


What is the version you used?
