### ISSUE TITLE
orders "STOP_LOSS" - "TAKE_PROFIT" - "ICEBERG" --- STOP-LIMIT

### ISSUE THREAD

**Issue by wadalino** [jaggedsoft/php-binance-api#86]
only SELL order that run is when LIMIT without args. 
Stop-loss, Take-profit or Iceberg not works: 
1.Stop-Loss: signedRequest error: {"code":-1013,"msg":"Stop loss orders are not supported for this symbol."}
2.Take-Profit: signedRequest error: {"code":-1013,"msg":"Take profit orders are not supported for this symbol."} 
3.Iceberg: siple not works: array(0) { } 

.... how i send a SELL STOP-LIMIT order ?

**Comment by jaggedsoft** [comment]
Must view `exchangeInfo()` to see which symbols support these types of orders
![image](https://user-images.githubusercontent.com/4283360/36249988-528054dc-11f1-11e8-90b8-c6002f2639f0.png)
