### ISSUE TITLE
yii2 integration

### ISSUE THREAD

**Issue by JOHNFFFEE** [jaggedsoft/php-binance-api#87]
I am working with YII2 framework and trying to install your extension but I am getting this error " Problem 1
    - jaggedsoft/php-binance-api 0.0.1 requires jaggedsoft/php-binance-api dev-master -> satisfiable by jaggedsoft/php-binance-api[dev-master].  "

any idea how to solve it ?

**Comment by jaggedsoft** [comment]
Not sure what causes this error
but that's why you have to add "@dev" at the end, like this:
`composer require "jaggedsoft/php-binance-api @dev"`

Would love to know myself

**Comment by dmzoneill** [comment]
i'm personally not convinced by the composer.json, it doesn't work.  I wasn't sure if i was doing something wrong..

if you run

```
COMPOSER=composer-test.json composer -vvv install --no-interaction --no-suggest
```

you'll get better results with the test composer-test.json

Since ye have both raised my concerns about that file.. ill take an action to fix it.  

@jaggedsoft

**Comment by JOHNFFFEE** [comment]
thank you,

 please let me know when it will be fixed


Yonatan Touboul
Founder, PostIot

0523594630<tel:0523594630> | yo.nitu@hotmail.com<mailto:yo.nitu@hotmail.com>



Tel-Aviv
[https://s3.amazonaws.com/images.wisestamp.com/social_icons/square/facebook.png]<http://www.facebook.com/yonatan.touboul>       [https://s3.amazonaws.com/images.wisestamp.com/social_icons/square/linkedin.png] <http://www.linkedin.com/in/yonatan-touboul-4b870964/>


Create your own email signature<https://www.wisestamp.com?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own>

________________________________
מאת: Dave <notifications@github.com>
‏‏נשלח: יום שישי 23 מרץ 2018 16:17:48
‏‏אל: jaggedsoft/php-binance-api
עותק: JOHNFFFEE; Author
‏‏נושא: Re: [jaggedsoft/php-binance-api] yii2 integration (#87)


i'm personally not convinced by the composer.json, it doesn't work. I wasn't sure if i was doing something wrong..

if you run

COMPOSER=composer-test.json composer -vvv install --no-interaction --no-suggest


you'll get better results with the test composer-test.json

Since ye have both raised my concerns about that file.. ill take an action to fix it.

@jaggedsoft<https://github.com/jaggedsoft>

**Comment by jaggedsoft** [comment]
Possibly related to https://github.com/jaggedsoft/php-binance-api/issues/16
Please try `composer require "jaggedsoft/php-binance-api dev-master"` and let me know if it works
