### ISSUE TITLE
Call to undefined method Binance\API::apiRequest()

### ISSUE THREAD

**Issue by DevObs1** [jaggedsoft/php-binance-api#88]
Release : 0.1.7
Error : Call to undefined method Binance\API::apiRequest() in php-binance-api.php:737 Stack trace: #0

Is this an error on my side? Or the function is missing in the class Binance (php-binance-api.php) ?

**Comment by jaggedsoft** [comment]
Thanks! Fixed https://github.com/jaggedsoft/php-binance-api/commit/2e357397f06532933a6cac7a87eb2a797c089c82
Available in `v0.1.8`

**Comment by jaggedsoft** [comment]
If for some reason this doesn't work, remove the `true` at the end. I believe this type or request does not need to be signed

**Comment by DevObs1** [comment]
Thank you for your responsiveness
Nevertheless, you have corrected that line 730. It remains the line 737 as shown in the stacktrace

**Comment by jaggedsoft** [comment]
Maybe you had an older version then. I replaced every instance of `apiRequest` which was the old method (using file_get_contents instead of cURL)

**Comment by DevObs1** [comment]
I have the latest version.
There is still line 737 with the call to the apiRequest function. Did you commit ?
https://github.com/jaggedsoft/php-binance-api/blob/master/php-binance-api.php

![image](https://user-images.githubusercontent.com/31596745/37871097-fc738a06-2fe5-11e8-8042-ab9b36c79ad8.png)

+ The 0.1.8 commit only affects the keepAlive function : 

![image](https://user-images.githubusercontent.com/31596745/37871117-77ac6ecc-2fe6-11e8-8589-9c73c130bce5.png)

**Comment by jaggedsoft** [comment]
Thanks, fixed in https://github.com/jaggedsoft/php-binance-api/commit/0fbd8bd992bccfc4cf5730c535cdfab6d6efa650 and updated release `v0.1.8`
