### ISSUE TITLE
Order creation doesn't work

### ISSUE THREAD

**Issue by juesem** [jaggedsoft/php-binance-api#89]
Order creation from php results in a server response "400 Bad Request" although the generated curl statement can be executed from console properly. Order deletion is fine as well as the former single api. Composer installation also fine. Any thoughts or hints?

$symbol = "BTCUSDT";
$quantity = 0.5;
$price = 9441.1;
$order = $api->sell($symbol, $quantity, $price);
print_r ($order);

$ php composer.phar require "jaggedsoft/php-binance-api @dev"
./composer.json has been updated                             
Loading composer repositories with package information
Updating dependencies (including require-dev)                
Package operations: 33 installs, 0 updates, 0 removals
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing ratchet/rfc6455 (v0.2.3): Loading from cache
  - Installing evenement/evenement (v3.0.1): Loading from cache
  - Installing react/event-loop (v0.4.3): Loading from cache
  - Installing react/stream (v0.7.7): Loading from cache
  - Installing react/promise (v2.5.1): Loading from cache
  - Installing react/promise-timer (v1.2.1): Loading from cache
  - Installing react/cache (v0.4.2): Loading from cache
  - Installing react/dns (v0.4.13): Loading from cache
  - Installing react/socket (v0.8.10): Loading from cache
  - Installing ratchet/pawl (v0.3.1): Loading from cache
  - Installing symfony/yaml (v3.4.6): Loading from cache
  - Installing sebastian/version (1.0.6): Loading from cache
  - Installing sebastian/global-state (1.1.1): Loading from cache
  - Installing sebastian/recursion-context (1.0.5): Loading from cache
  - Installing sebastian/exporter (1.2.2): Loading from cache
  - Installing sebastian/environment (1.3.8): Loading from cache
  - Installing sebastian/diff (1.4.3): Loading from cache
  - Installing sebastian/comparator (1.2.4): Loading from cache
  - Installing doctrine/instantiator (1.1.0): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (2.3.8): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing phpunit/php-token-stream (1.4.12): Loading from cache
  - Installing phpunit/php-code-coverage (2.2.4): Loading from cache
  - Installing webmozart/assert (1.3.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
  - Installing phpspec/prophecy (1.7.5): Loading from cache
  - Installing phpunit/phpunit (4.8.36): Loading from cache
react/event-loop suggests installing ext-libevent (>=0.1.0)
react/event-loop suggests installing ext-event (~1.0)
react/event-loop suggests installing ext-libev (*)
ratchet/pawl suggests installing reactivex/rxphp (~2.0)
symfony/yaml suggests installing symfony/console (For validating YAML files using the lint command)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Writing lock file
Generating optimized autoload files

**Comment by dmzoneill** [comment]
Hi

Thanks for your time to submit this issue.
We validated a number of these requests, one just this week, about failures to make orders. 

Is it just sell orders that are giving you trouble?  

Thanks in advance!

**Comment by juesem** [comment]
Hi Dave,

 

both order types are affected, sell and buy, limit and market.

 

Thanks

 

Juergen

 

Von: Dave [mailto:notifications@github.com] 
Gesendet: Mittwoch, 28. März 2018 10:20
An: jaggedsoft/php-binance-api <php-binance-api@noreply.github.com>
Cc: juesem <juesem@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [jaggedsoft/php-binance-api] Order creation doesn't work (#89)

 

Hi

Thanks for your time to submit this issue.
We validated a number of these requests, one just this week, about failures to make orders.

Is it just sell orders that are giving you trouble?

Thanks in advance!

**Comment by dmzoneill** [comment]
Hi

market order works fine, second time this week I'm buying BNB.

```
dave@dave-laptop:~/Desktop/crypto/php-binance-api/examples$ php test.php 
Array
(
    [symbol] => BNBBTC
    [orderId] => 34923937
    [clientOrderId] => ugapPLU2UMUGWicmyVIAML
    [transactTime] => 1522259981053
    [price] => 0.00000000
    [origQty] => 1.00000000
    [executedQty] => 1.00000000
    [status] => FILLED
    [timeInForce] => GTC
    [type] => MARKET
    [side] => BUY
)

dave@dave-laptop:~/Desktop/crypto/php-binance-api/examples$ cat test.php 
<?php

require '../php-binance-api.php';

// @see home_directory_config.php
// // use config from ~/.confg/jaggedsoft/php-binance-api.json
$api = new Binance\API();
//
// Place a MARKET order
$quantity = 1;
$order = $api->buy("BNBBTC", $quantity, 0, "MARKET");
print_r($order);
```

**Comment by dmzoneill** [comment]
an a sell order for validation of both sell and buy

**code**
```
dave@dave-laptop:~/Desktop/crypto/php-binance-api/examples$ cat test.php 
<?php

require '../php-binance-api.php';

// @see home_directory_config.php
// // use config from ~/.confg/jaggedsoft/php-binance-api.json
$api = new Binance\API();
//
// Place a MARKET order
$quantity = 1;
$order = $api->sell("BNBBTC", $quantity, 0, "MARKET");
print_r($order);
```

**result**
```
Array
(
    [symbol] => BNBBTC
    [orderId] => 34928617
    [clientOrderId] => 4DZ4xLvWF3U92ZocUGoZ5J
    [transactTime] => 1522261958809
    [price] => 0.00000000
    [origQty] => 1.00000000
    [executedQty] => 1.00000000
    [status] => FILLED
    [timeInForce] => GTC
    [type] => MARKET
    [side] => SELL
)
```

**Comment by juesem** [comment]
I will look into it again and get you posted.

 

Thanks

 

Von: Dave [mailto:notifications@github.com] 
Gesendet: Mittwoch, 28. März 2018 20:34
An: jaggedsoft/php-binance-api <php-binance-api@noreply.github.com>
Cc: juesem <juesem@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [jaggedsoft/php-binance-api] Order creation doesn't work (#89)

 

an a sell order for validation of both sell and buy

code

dave@dave-laptop:~/Desktop/crypto/php-binance-api/examples$ cat test.php 
<?php
 
require '../php-binance-api.php';
 
// @see home_directory_config.php
// // use config from ~/.confg/jaggedsoft/php-binance-api.json
$api = new Binance\API();
//
// Place a MARKET order
$quantity = 1;
$order = $api->sell("BNBBTC", $quantity, 0, "MARKET");
print_r($order);

result

Array
(
    [symbol] => BNBBTC
    [orderId] => 34928617
    [clientOrderId] => 4DZ4xLvWF3U92ZocUGoZ5J
    [transactTime] => 1522261958809
    [price] => 0.00000000
    [origQty] => 1.00000000
    [executedQty] => 1.00000000
    [status] => FILLED
    [timeInForce] => GTC
    [type] => MARKET
    [side] => SELL
)

**Comment by dmzoneill** [comment]
excellent man, if you can provide any further information, that would be great!!!
