### ISSUE TITLE
Multiple (not only one, not all) symbols syntax WebSocket API

### ISSUE THREAD

**Issue by vreesie18** [jaggedsoft/php-binance-api#92]
What is the correct syntax for getting the data of 2 symbols. I tried the syntax below but that is not working. It seems that I am getting only the data of the fisrt symbol. Please advice..!! 

	$arrSymbols = array('BTCUSDT','LTCUSDT');
	
	$binance_api->trades($arrSymbols, function($binance_api, $symbol, $trades) {
		echo "{$symbol} trades update".PHP_EOL;
		print_r($trades);
	});

**Comment by jaggedsoft** [comment]
That format worked last time I tested this

Binance has changed some things: https://github.com/jaggedsoft/node-binance-api/issues/164
^ We need to implement the "Combined websocket stream" like node-binance-api
