### ISSUE TITLE
Issue with stopping web socket with $loop variable

### ISSUE THREAD

**Issue by vreesie18** [jaggedsoft/php-binance-api#95]
I am trying to use the functionality to stop running a started web socket ($loop), chart web socket is this case, but I get somes errors (seel below) and cann't figure out why.  Anyone ?! 

My Code:
		$binance_api->chart([$Coin."USDT"], $Period, function($binance_api, $symbol, $chart, $loop) {
			global $Coin, $Period, $LoopCounter;	
			if ($LoopCounter>0) {
				$loop->stop();
			}

My Error:
Warning: Missing argument 4 for {closure}() in /var/www/efy.nl/honda_unit_candlestick_data.php on line 139

Fatal error: Uncaught Error: Call to undefined method Binance\API::terminate() in /var/www/xxxxx/xxxxx.php:148 Stack trace: #0 [internal function]: {closure}(Object(Binance\API), 'BTCUSDT', Array) #1

**Comment by dmzoneill** [comment]
Re-download the php-binance.php again.. You seem to be working off an old version
