### ISSUE TITLE
Ticker

### ISSUE THREAD

**Issue by wybitnygracz** [jaggedsoft/php-binance-api#96]
If I use the function for example ->ticker, my script works correctly for about 2.5 minutes, then script stop adding records to the database and I see the page 

"Internal Server Error The server encountered an internal error or misconfiguration and was unable to complete your request.". 

What should i check, do to ensure that the connection does not expire?

**Comment by jaggedsoft** [comment]
Sorry I can not provide support for the project, it was never meant to run as a web app, instead from the server side where you can see error messages.

**Comment by jaggedsoft** [comment]
You probably need to set `max_execution_time(0);`
