### ISSUE TITLE
Can't buy or sell

### ISSUE THREAD

**Issue by quacos** [jaggedsoft/php-binance-api#99]
I am trying to do just marketSell or marketBuy, but I have NULL in return and Binance API returns
"400 ERROR
The request could not be satisfied."

**Comment by jaggedsoft** [comment]
Hmm first time seeing this error

**Comment by dmzoneill** [comment]
400s according to binance rest Ali mean server error

![screenshot_20180403-190942](https://user-images.githubusercontent.com/15192260/38267249-ceece23c-3772-11e8-948f-f3ae3baf7a89.jpg)

**Comment by quacos** [comment]
balances and exchangeInfo do work

**Comment by quacos** [comment]
OK guys, it seems that Binance doesn't allow operations from my Hetzner cloud instance. From local Linux installation it worked flawlessly.

**Comment by dmzoneill** [comment]
Excellent man.. glad you found the solution and making us aware of that binance may be blocking cloud providers etc..

**Comment by walfridosp** [comment]
Hi guys, I'm having the same issue, my server is hosted in Google Cloud, is there any solution for this?

**Comment by jaggedsoft** [comment]
@walfridosp Need more information. If possible make a new issue
Have orders worked for you before? Have they just recently stopped?
Can you share some code (like what your order code looks like?)
Are you sure "test mode" is not enabled?

**Comment by jaggedsoft** [comment]
@walfridosp Can you please help us test this? This will test if it's related to SSL
Make a json config file somewhere with your data in it: (binance.json)
```json
{
    "api-key": "<api key>",
    "api-secret": "<secret>",
    "curlOpts": {
	    "CURLOPT_SSL_VERIFYPEER": 0
    }
}
```

```php
$api = new Binance\API("binance.json");
$quantity = 0.02;
$order = $api->marketBuy("BTCUSDT", $quantity, ["newOrderRespType" => "FULL"]);
print_r($order);
```

What we're doing here is two things:
- Checking result with SSL disabled
- Requesting complete order detail with newOrderRespType

**Comment by walfridosp** [comment]
@jaggedsoft thanks for the quick reply.

Let me test this and will get back to you, but I think you are in the right direction here because I remember I use "CURLOPT_SSL_VERIFYPEER": 0 in other services too.

Give me some minutes and will let you know.

Thanks

**Comment by walfridosp** [comment]
@jaggedsoft I have tried using the JSON config file, but no luck, still having the same error NULL.
I went to the code to check what was the real error curl_exec($ch) was generating and I got this:

```
400 ERROR
The request could not be satisfied.
Bad request. 
Generated by cloudfront (CloudFront)
Request ID: gylQpEM5XrJP........................................AOcSudQ==
```

Does this give you and idea of what is happening?

**Comment by quacos** [comment]
@walfridosp Binance blacklisted your IP

**Comment by jaggedsoft** [comment]
@walfridosp I really wish I could provide some insight here. Until I am able to test this on a google cloud instance I am out of ideas. I think there is some issue specific to this type of configuration that we need to account for, but I have no idea what it is. If you can post the complete response it might be able to give some more insight

**Comment by walfridosp** [comment]
@jaggedsoft Please let me know if you are able to replicate this from a Google Cloud server, I will try to provide more information of my tests.

@quacos I saw you had similar issue before, did you just change the IP or you moved your project out of your Hetzner cloud instance?

Thanks!

**Comment by quacos** [comment]
@walfridosp I did change IP

**Comment by walfridosp** [comment]
@jaggedsoft Did you have time for setting up the Google Cloud instance?

I have done some research but no luck so far, it seems to be related to your CloudFront configuration... if that make sense.

Please update me when you find something.

Thanks

**Comment by dmzoneill** [comment]
i have a GCE account, can you tell which region etc you are deploying to.

![image](https://user-images.githubusercontent.com/15192260/38814370-45e3d678-4189-11e8-8481-8b548abff0b0.png)

**Comment by quacos** [comment]
@walfridosp just try from another Google Cloud instance.

CloudFront is not related to @jaggedsoft, it's related to Binance. And Binance is blocking your specific IP.

**Comment by walfridosp** [comment]
@dmzoneill The instance is this zone: asia-southeast1-a

@quacos will try changing the Google Could instance.

Thanks!

**Comment by walfridosp** [comment]
@dmzoneill @quacos I have tried with a different Google Cloud instances, which are in zone: asia-east1-a and us-central1-a.

The result I'm getting is the same "NULL", from localhost it works perfectly or if I do a bad request like for example:

```
$order = $api->marketBuy("BTCUSDT", 10, ["newOrderRespType" => "FULL"]);
```

I get the error message:
```
signedRequest error: {"code":-2010,"msg":"Account has insufficient balance for requested action."} array(2) { ["code"]=> int(-2010) ["msg"]=> string(54) "Account has insufficient balance for requested action." }
```

but from the server the only thing I get for all requests is NULL, and this other error if I print the result of curl_exec($ch);

```
400 ERROR
The request could not be satisfied.
Bad request. 
Generated by cloudfront (CloudFront)
Request ID: gylQpEM5XrJP........................................AOcSudQ==
```

I'm running out of ideas, any other suggestion from you guys?

Thanks!

**Comment by afsharsafavi** [comment]
maybe you should use useServerTime true flag in construct

**Comment by walfridosp** [comment]
@afsharsafavi testing it now, will let you know, thanks!

**Comment by walfridosp** [comment]
@afsharsafavi Nope, useServerTime didn't help, still getting the same result "NULL".

BTW, I'm not using composer, but I just updated to the latest version of the library, so I don't think is related to that.

```
$output = curl_exec($curl);
```
Prints the same:
```
400 ERROR
The request could not be satisfied.
Bad request. 
Generated by cloudfront (CloudFront)
Request ID: Lu5uNpqKwMPH172hDphGdb1WEXSca-JyP358Y2Az1TyFItkRGd423Q==
```

Let me know if you have any other idea I can test.
Thanks.

**Comment by afsharsafavi** [comment]
My comment is not related to composer!
php-binance-api in default use your system time.
I think you have difference in timezone or timestamp with binance server timeserver.
you can set true flag in php-binance-api constructor and I think it can solve your problem.
$api = new Binance\API('you_api_key','your_secret_key',array('useServerTime'=>true));

**Comment by walfridosp** [comment]
@afsharsafavi yes, that's what I tried, I set the useServerTime to true, but I got the same result. Just mentioned I wasn't composer to say I'm using the latest version.

Thanks

**Comment by slcma** [comment]
@walfridosp did you find a solution? I'm having the same issue.

I can get balances fine and open orders, etc... but when I try to place a buy order, I get the 400 error.

My code is custom php but the account has .05 BTC and if I try to post this (an order I know will not execute as price is very low):
https://api.binance.com/api/v3/order?timestamp=1526473088633&symbol=ETHBTC&price=0.04220550&side=BUY&newClientOrderId=buy0&timeInForce=GTC&type=LIMIT&quantity=0.01184679&signature=...

BTW, the timestamp is the server's time

I get this result:
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>400 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Bad request.

<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: vFEbi_OCzq8yJePJKlhGEWOeQ91tR_QPVD2m3SIXqFrdG-BTLYI9Xg==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>

Any ideas? Is my amount too low? 0.0005 BTC, what is Binance limit?

**Comment by walfridosp** [comment]
@slcma I haven't find a solution yet, that's the same error I get, but for you it might be because the amount is too low, minimum amount for BTCUSDT is 0.1

You can check the limits here:
[https://api.binance.com/api/v1/exchangeInfo](url)

Try with 0.1 and let me know if it works.

**Comment by dmzoneill** [comment]
$api->exchangeInfo() has an array of the symbols and their valid tranction types, Market, Limit, Iceberg etc and also the amount and increments valid.  

You would typically get a filter error for what ye are suggesting
## -9xxx Filter failures
Error message | Description
------------ | ------------
"Filter failure: PRICE_FILTER" | `price` is too high, too low, and/or not following the tick size rule for the symbol.
"Filter failure: LOT_SIZE" | `quantity` is too high, too low, and/or not following the step size rule for the symbol.
"Filter failure: MIN_NOTIONAL" | `price` * `quantity` is too low to be a valid order for the symbol.
"Filter failure: MAX_NUM_ORDERS" | Account has too many open orders on the symbol.
"Filter failure: MAX_ALGO_ORDERS" | Account has too many open stop loss and/or take profit orders on the symbol.
"Filter failure: EXCHANGE_MAX_NUM_ORDERS" | Account has too many open orders on the exchange.
"Filter failure: EXCHANGE_MAX_ALGO_ORDERS" | Account has too many open stop loss and/or take profit orders on the exchange.

a 400 error suggests something wrong the the connection for this request.

Prices, openorders etc dont require valid keys, making an order requires valid keys and trading is enabled

![image](https://user-images.githubusercontent.com/15192260/40119734-5479cf46-5915-11e8-833e-fb42cf1851c9.png)

**Comment by dmzoneill** [comment]
hey can you create a new issue here

https://github.com/jaggedsoft/php-binance-api/issues/new

please fill out the required details, we can work your issue once we have the details

**Comment by slcma** [comment]
@dmzoneill I was just going through creating it and then realized you might expect me to be using this your specific php API code - I did not find your code until doing this google search and have already built an application using my own code. 

I am quite convinced that the issue is not related to the code but would you require me to reproduce it with your code before submitting it as an issue? 

I don't think it is related to the code - just the API call is not working and Cloudfare is responding with the 400 error.

**Comment by slcma** [comment]
I'll use the library - I was actually wondering about the CA thing - that certainly could explain it.

**Comment by slcma** [comment]
Before re-factoring all my code I thought I'd try the curl from command line and got an error instead so I am sure it's my code then.. or a missing curl option... or an extra one :)

Thanks for pointing me in the right direction

```
curl -X POST -H 'X-MBX-APIKEY: $key' -d 'timestamp=1526508559488&symbol=ETHBTC&price=0.04212400&side=BUY&newClientOrderId=buy13396&timeInForce=GTC&type=LIMIT&quantity=0.00791314&signature=$sig' https://api.binance.com/api/v3/order | tee json.out
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   258    0    47  100   211    164    738 --:--:-- --:--:-- --:--:--   740
{"code":-1013,"msg":"Filter failure: LOT_SIZE"}
```

**Comment by dmzoneill** [comment]
look like you have answered your own question then :), good luck with your code.

**Comment by jeansergegagnon** [comment]
SOLVED
Took a while, but figured it out - I was not able to use your library because I'm on PHP 5 but for anyone else who finds this thread, the reason I was getting the error was because I was using code like this:

```
$ch = curl_init($url.'?'.$query);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/4.0 (compatible; PHP '.$this->name.' MyCryptoAutoBot; '.php_uname('a').'; PHP/'.phpversion().')');
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
if ($method == "POST") {
        curl_setopt($ch, CURLOPT_POST, true);
} else if ($method == "DELETE") {
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $method);
}
curl_setopt($ch, CURLOPT_HEADER, false);
curl_setopt($ch, CURLOPT_TIMEOUT, 60);
$res = curl_exec($ch);
```

instead of

```
$ch = curl_init();
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/4.0 (compatible; PHP '.$this->name.' MyCryptoAutoBot; '.php_uname('a').'; PHP/'.phpversion().')');
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
if ($method == "POST") {
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $query);
        curl_setopt($ch, CURLOPT_URL, $url);
} else if ($method == "DELETE") {
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $method);
        curl_setopt($ch, CURLOPT_URL, $url . '?' . $query);
} else {
        curl_setopt($ch, CURLOPT_URL, $url . '?' . $query);
}
curl_setopt($ch, CURLOPT_HEADER, false);
curl_setopt($ch, CURLOPT_TIMEOUT, 60);
$res = curl_exec($ch);
```

Basically, putting the URL in the curl_init instead of using the CURLOPT_URL and the CURLOPT_POSTFIELDS.

It's weird though as I thought curl automatically handled that when the method was POST and your code even has that commented out, so not sure if it's a PHP 5 issue.

Anyway, it works for me with the empty curl_init.

Hope this helps someone else.

**Comment by ScorpioT1000** [comment]
@jeansergegagnon Thanks it works for mee to.

My problem was missing CURLOPT_POSTFIELDS. I'm using query fields instead of the body.
CURLOPT_POSTFIELDS must be set to an empty string at least

**Comment by jeansergegagnon** [comment]
Awesome, glad my post helped.

**Comment by y0un1verse** [comment]
@jaggedsoft , @walfridosp I had the same issue fixed.

Two different servers (CentOS 7 / PHP 7.1): Balances, Ticker, even Order cancel work fine. Only Buy and Sell produces 404 error. Changing curl options did not help.
Localhost (Windows / PHP 7.1): Everything works fine.

Localhost and one of the servers have same IP. So in my case it was not an IP problem.
Changing OS from CentOS 7 to Ubuntu 16 (PHP 7.0) at the server solved everything.

Yet I don't understand what is wrong with CentOS, but the OS was the issue.

**Comment by pozitivexx** [comment]
> 
> 
> @jaggedsoft , @walfridosp I had the same issue fixed.
> 
> Two different servers (CentOS 7 / PHP 7.1): Balances, Ticker, even Order cancel work fine. Only Buy and Sell produces 404 error. Changing curl options did not help.
> Localhost (Windows / PHP 7.1): Everything works fine.
> 
> Localhost and one of the servers have same IP. So in my case it was not an IP problem.
> Changing OS from CentOS 7 to Ubuntu 16 (PHP 7.0) at the server solved everything.
> 
> Yet I don't understand what is wrong with CentOS, but the OS was the issue.

I have same system and same problem.

while connecting in userData() 
 Connection #0 to host api.binance.com left intact
* About to connect() to api.binance.com port 443 (#1)
*   Trying 54.239.168.180...
* Connected to api.binance.com (54.239.168.180) port 443 (#1)
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=*.binance.com,OU=IT,O=Binance Holdings Limited,L=Grand Cayman,C=KY
*       start date: Feb 27 00:00:00 2018 GMT
*       expire date: Feb 27 12:00:00 2020 GMT
*       common name: *.binance.com
*       issuer: CN=GeoTrust RSA CA 2018,OU=www.digicert.com,O=DigiCert Inc,C=US
> POST /api/v1/userDataStream HTTP/1.1
User-Agent: User-Agent: Mozilla/4.0 (compatible; PHP Binance API)
Host: api.binance.com
Accept: */*
X-MBX-APIKEY: xxx
Content-Length: -1
Content-Type: application/x-www-form-urlencoded
Expect: 100-continue

< HTTP/1.1 400 Bad Request
< Server: CloudFront
< Date: Fri, 26 Oct 2018 12:36:57 GMT
< Content-Type: text/html
< Content-Length: 556
< Connection: close
< X-Cache: Error from cloudfront
< Via: 1.1 xxx.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: xxx==
<
* Closing connection 1

< Date: Fri, 26 Oct 2018 12:36:10 GMT
< Content-Type: text/html
< Content-Length: 556
< Connection: close
< X-Cache: Error from cloudfront

**Comment by brunoposco** [comment]
Guys, I'm having the same issue, locally works well. I tried modifying what @jeansergegagnon mentions but it did not work. Someone found a solution? Thanks!

**Comment by pozitivexx** [comment]
I'm waiting soluotion too.

31 Eki 2018 Çar 22:11 tarihinde brunoposco <notifications@github.com> şunu
yazdı:

**Comment by afsharsafavi** [comment]
I solved this problem.
Now you can use new code:
https://github.com/jaggedsoft/php-binance-api/pull/216
